apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb-sn/build_test/k8s
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: urlshorten-service-pb-ctr
  name: urlshorten-service-pb-ctr
spec:
  ports:
  - name: '12364'
    port: 12364
    targetPort: 12345
  - name: '12345'
    port: 12345
    targetPort: 12345
  selector:
    io.kompose.service: urlshorten-service-pb-ctr
