// Blueprint: Auto-generated by GRPC Plugin
package grpc

import (
	"context"
	"time"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
	"blueprint/goproc/usertimeline_service_cgpb_proc/ot"
	"github.com/blueprint-uservices/blueprint/examples/dsb_sn/workflow/socialnetwork"
)

type PostStorageService_GRPCClient struct {
	ot.PostStorageService_OTServerWrapperInterface
	Client PostStorageService_OTServerWrapperInterfaceClient // The actual GRPC-generated client
	Timeout time.Duration
}

func New_PostStorageService_GRPCClient(ctx context.Context, serverAddress string) (*PostStorageService_GRPCClient, error) {
	var opts []grpc.DialOption
	opts = append(opts, grpc.WithTransportCredentials(insecure.NewCredentials()))
	duration, err := time.ParseDuration("1s")
	if err != nil {
		return nil, err
	}
	opts = append(opts, grpc.WithTimeout(duration))
	conn, err := grpc.Dial(serverAddress, opts...)
	if err != nil {
		return nil, err
	}

	c := &PostStorageService_GRPCClient{}
	c.Client = NewPostStorageService_OTServerWrapperInterfaceClient(conn)
	c.Timeout = duration
	return c, nil
}


func (client *PostStorageService_GRPCClient) ReadPost(ctx context.Context, reqID int64, postID int64, traceCtx string) (ret0 socialnetwork.Post, err error) {
	// Create and marshall the GRPC Request object
	req := &PostStorageService_OTServerWrapperInterface_ReadPost_Request{}
	req.marshall(reqID, postID, traceCtx)

	// Configure the client-side request timeout
	ctx, cancel := context.WithTimeout(ctx, client.Timeout)
	defer cancel()

	// Make the remote call
	rsp, err := client.Client.ReadPost(ctx, req)
	if err == nil {
		err = ctx.Err()
	}
	if err != nil {
		return
	}

	ret0 =  rsp.unmarshall()
	return
}

func (client *PostStorageService_GRPCClient) ReadPosts(ctx context.Context, reqID int64, postIDs []int64, traceCtx string) (ret0 []socialnetwork.Post, err error) {
	// Create and marshall the GRPC Request object
	req := &PostStorageService_OTServerWrapperInterface_ReadPosts_Request{}
	req.marshall(reqID, postIDs, traceCtx)

	// Configure the client-side request timeout
	ctx, cancel := context.WithTimeout(ctx, client.Timeout)
	defer cancel()

	// Make the remote call
	rsp, err := client.Client.ReadPosts(ctx, req)
	if err == nil {
		err = ctx.Err()
	}
	if err != nil {
		return
	}

	ret0 =  rsp.unmarshall()
	return
}

func (client *PostStorageService_GRPCClient) StorePost(ctx context.Context, reqID int64, post socialnetwork.Post, traceCtx string) (err error) {
	// Create and marshall the GRPC Request object
	req := &PostStorageService_OTServerWrapperInterface_StorePost_Request{}
	req.marshall(reqID, post, traceCtx)

	// Configure the client-side request timeout
	ctx, cancel := context.WithTimeout(ctx, client.Timeout)
	defer cancel()

	// Make the remote call
	rsp, err := client.Client.StorePost(ctx, req)
	if err == nil {
		err = ctx.Err()
	}
	if err != nil {
		return
	}

	 rsp.unmarshall()
	return
}

