// Blueprint: Auto-generated by Retries Plugin
package retries

import (
	"github.com/blueprint-uservices/blueprint/examples/dsb_sn/workflow/socialnetwork"
	"context"
)

type TextService_RetrierClient struct {
	Client socialnetwork.TextService
	MaxTries int
}

func New_TextService_RetrierClient (ctx context.Context, client socialnetwork.TextService) (*TextService_RetrierClient, error) {
	handler := &TextService_RetrierClient{}
	handler.Client = client
	handler.MaxTries = 3
	return handler, nil
}


func (client *TextService_RetrierClient) ComposeText(ctx context.Context, reqID int64, text string) (ret0 string, ret1 []socialnetwork.UserMention, ret2 []socialnetwork.URL, err error) {
	for i := 0; i < client.MaxTries; i++ {
		ret0, ret1, ret2, err = client.Client.ComposeText(ctx, reqID, text)
		if err == nil {
			return
		}
	}
	return
}

