// post_storage_service_cgpb_proc runs the post_storage_service_cgpb_proc Golang process.
//
// post_storage_service_cgpb_proc is auto-generated by Blueprint's goproc plugin (goproc/goprocgen/main.go.go)
//
// Usage:
//
//   go run main.go --post_cache_cgpb.dial_addr=value --post_db_cgpb.dial_addr=value --otelcol_cgpb.dial_addr=value --post_storage_service_cgpb.grpc.bind_addr=value 
//
// Optional env: GC_INTERVAL_SEC=N (e.g. 30, 1, 0.5, 0.1) to run GC every N seconds; fractional seconds supported. Omit or <=0 for default GC.
//
// post_storage_service_cgpb_proc requires the following arguments are passed:
//
//   --post_cache_cgpb.dial_addr
//       Auto-generated by Blueprint IR node:
//       post_cache_cgpb.dial_addr = AddressConfig()
//
//   --post_db_cgpb.dial_addr
//       Auto-generated by Blueprint IR node:
//       post_db_cgpb.dial_addr = AddressConfig()
//
//   --otelcol_cgpb.dial_addr
//       Auto-generated by Blueprint IR node:
//       otelcol_cgpb.dial_addr = AddressConfig()
//
//   --post_storage_service_cgpb.grpc.bind_addr
//       Auto-generated by Blueprint IR node:
//       post_storage_service_cgpb.grpc.bind_addr = AddressConfig()
//
// post_storage_service_cgpb_proc will instantiate the following IR nodes:
//   post_storage_service_cgpb_proc.stdoutmetriccollector
//   post_storage_service_cgpb_proc.logger
//   post_cache_cgpb.client
//   post_db_cgpb.client
//   post_storage_service_cgpb
//   otelcol_cgpb.client
//   post_storage_service_cgpb.server.ot
//   post_storage_service_cgpb.grpc_server
package main

import (
	"context"
	"os"
	"runtime"
	"strconv"
	"time"

	"log/slog"
)

func main() {
	// Optional: run GC on a fixed interval to normalize GC frequency (e.g. across tracing vs no-tracing).
	// Set GC_INTERVAL_SEC to a positive number (e.g. 30, 1, 0.5, 0.1) to trigger runtime.GC() every N seconds; unset or <=0 to leave default GC behavior.
	if sec := os.Getenv("GC_INTERVAL_SEC"); sec != "" {
		if secVal, err := strconv.ParseFloat(sec, 64); err == nil && secVal > 0 && secVal < 1e15 {
			interval := time.Duration(secVal * float64(time.Second))
			if interval > 0 {
				go func() {
					ticker := time.NewTicker(interval)
					defer ticker.Stop()
					for range ticker.C {
						runtime.GC()
					}
				}()
			}
		}
	}
	slog.Info("Running post_storage_service_cgpb_proc")
	n, err := New_post_storage_service_cgpb_proc("post_storage_service_cgpb_proc").Build(context.Background())
	if err != nil {
		slog.Error(err.Error())
		os.Exit(1)
	}
	n.Await()
	slog.Info("post_storage_service_cgpb_proc exiting")
}