apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_cgpb_ctl/k8s
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: usertimeline-service-cgpb-es-ctr
  name: usertimeline-service-cgpb-es-ctr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: usertimeline-service-cgpb-es-ctr
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_cgpb_ctl/k8s
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: usertimeline-service-cgpb-es-ctr
    spec:
      containers:
      - env:
        - name: BRIDGE_KIND
          value: cgpb
        - name: GC_INTERVAL_SEC
          value: '0'
        - name: GOGC
          value: '100'
        - name: OTELCOL_CGPB_ES_DIAL_ADDR
          value: otelcol-cgpb-es-ctr:4317
        - name: POST_STORAGE_SERVICE_CGPB_ES_GRPC_DIAL_ADDR
          value: post-storage-service-cgpb-es-ctr:12345
        - name: USERTIMELINE_CACHE_CGPB_ES_DIAL_ADDR
          value: usertimeline-cache-cgpb-es-ctr:6379
        - name: USERTIMELINE_DB_CGPB_ES_DIAL_ADDR
          value: usertimeline-db-cgpb-es-ctr:27017
        - name: USERTIMELINE_SERVICE_CGPB_ES_GRPC_BIND_ADDR
          value: 0.0.0.0:12345
        - name: OTLP_RETRY
          value: 'off'
        - name: GOMAXPROCS
          value: '8'
        image: 10.10.1.1:30000/usertimeline-service-cgpb-es-ctr:latest
        name: usertimeline-service-cgpb-es-ctr
        ports:
        - containerPort: 12345
          protocol: TCP
        resources:
          requests:
            cpu: 8000m
          limits:
            cpu: 8000m
      hostname: usertimeline-service-cgpb-es-ctr
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: node-3
