apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_v_es/k8s
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: elasticsearch-v-es-ctr
  name: elasticsearch-v-es-ctr
spec:
  ports:
  - name: '12347'
    port: 12347
    targetPort: 9200
  - name: '9200'
    port: 9200
    targetPort: 9200
  selector:
    io.kompose.service: elasticsearch-v-es-ctr
