apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_v6/k8s
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: hometimeline-cache-v6-ctr
  name: hometimeline-cache-v6-ctr
spec:
  ports:
  - name: '12347'
    port: 12347
    targetPort: 6379
  - name: '6379'
    port: 6379
    targetPort: 6379
  selector:
    io.kompose.service: hometimeline-cache-v6-ctr
