apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_nt4/k8s
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: usermention-service-nt4-ctr
  name: usermention-service-nt4-ctr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: usermention-service-nt4-ctr
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_nt4/k8s
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: usermention-service-nt4-ctr
    spec:
      containers:
      - env:
        - name: USERMENTION_SERVICE_NT4_GRPC_BIND_ADDR
          value: 0.0.0.0:12345
        - name: USER_CACHE_NT4_DIAL_ADDR
          value: user-cache-nt4-ctr:6379
        - name: USER_DB_NT4_DIAL_ADDR
          value: user-db-nt4-ctr:27017
        image: 10.10.1.1:30000/usermention-service-nt4-ctr:latest
        name: usermention-service-nt4-ctr
        ports:
        - containerPort: 12345
          protocol: TCP
        resources:
          requests:
            cpu: 4000m
      hostname: usermention-service-nt4-ctr
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: node-3
