// urlshorten_service_sb2_proc runs the urlshorten_service_sb2_proc Golang process.
//
// urlshorten_service_sb2_proc is auto-generated by Blueprint's goproc plugin (goproc/goprocgen/main.go.go)
//
// Usage:
//
//   go run main.go --urlshorten_db_sb2.dial_addr=value --otelcol_sb2.dial_addr=value --urlshorten_service_sb2.grpc.bind_addr=value 
//
// urlshorten_service_sb2_proc requires the following arguments are passed:
//
//   --urlshorten_db_sb2.dial_addr
//       Auto-generated by Blueprint IR node:
//       urlshorten_db_sb2.dial_addr = AddressConfig()
//
//   --otelcol_sb2.dial_addr
//       Auto-generated by Blueprint IR node:
//       otelcol_sb2.dial_addr = AddressConfig()
//
//   --urlshorten_service_sb2.grpc.bind_addr
//       Auto-generated by Blueprint IR node:
//       urlshorten_service_sb2.grpc.bind_addr = AddressConfig()
//
// urlshorten_service_sb2_proc will instantiate the following IR nodes:
//   urlshorten_service_sb2_proc.stdoutmetriccollector
//   urlshorten_service_sb2_proc.logger
//   urlshorten_db_sb2.client
//   urlshorten_service_sb2
//   otelcol_sb2.client
//   urlshorten_service_sb2.server.ot
//   urlshorten_service_sb2.grpc_server
package main

import (
	"context"
	"os"

	"log/slog"
)

func main() {
	slog.Info("Running urlshorten_service_sb2_proc")
	n, err := New_urlshorten_service_sb2_proc("urlshorten_service_sb2_proc").Build(context.Background())
	if err != nil {
		slog.Error(err.Error())
		os.Exit(1)
	}
	n.Await()
	slog.Info("urlshorten_service_sb2_proc exiting")
}