apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_pb_ctl/k8s
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: user-service-pb-es-ctr
  name: user-service-pb-es-ctr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-service-pb-es-ctr
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_pb_ctl/k8s
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: user-service-pb-es-ctr
    spec:
      containers:
      - env:
        - name: BRIDGE_KIND
          value: pb
        - name: GC_INTERVAL_SEC
          value: '0'
        - name: GOGC
          value: '100'
        - name: OTELCOL_PB_ES_DIAL_ADDR
          value: otelcol-pb-es-ctr:4317
        - name: SOCIALGRAPH_SERVICE_PB_ES_GRPC_DIAL_ADDR
          value: socialgraph-service-pb-es-ctr:12345
        - name: USER_CACHE_PB_ES_DIAL_ADDR
          value: user-cache-pb-es-ctr:6379
        - name: USER_DB_PB_ES_DIAL_ADDR
          value: user-db-pb-es-ctr:27017
        - name: USER_SERVICE_PB_ES_GRPC_BIND_ADDR
          value: 0.0.0.0:12345
        - name: OTLP_RETRY
          value: 'off'
        - name: GOMAXPROCS
          value: '8'
        image: 10.10.1.1:30000/user-service-pb-es-ctr:latest
        name: user-service-pb-es-ctr
        ports:
        - containerPort: 12345
          protocol: TCP
        resources:
          requests:
            cpu: 8000m
          limits:
            cpu: 8000m
      hostname: user-service-pb-es-ctr
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: node-8
