apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_v3/k8s
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: otelcol-v3-ctr
  name: otelcol-v3-ctr
spec:
  internalTrafficPolicy: Local
  ports:
  - name: '12353'
    port: 12353
    targetPort: 4317
  - name: '12354'
    port: 12354
    targetPort: 8080
  - name: '4317'
    port: 4317
    targetPort: 4317
  - name: '8080'
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: otelcol-v3-ctr
