// Blueprint: Auto-generated by GRPC Plugin marshallgen.go
package grpc

import (
	"github.com/blueprint-uservices/blueprint/examples/dsb_sn/workflow/socialnetwork"
)

// Client-side function to pack UserService.ComposeCreatorWithUserId args into a GRPC UserService_ComposeCreatorWithUserId_Request struct
func (msg *UserService_ComposeCreatorWithUserId_Request) marshall(reqID int64, userID int64, username string) *UserService_ComposeCreatorWithUserId_Request {
	msg.ReqID = int64(reqID)
	msg.UserID = int64(userID)
	msg.Username = string(username)
	return msg
}

// Server-side function to unpack UserService.ComposeCreatorWithUserId args from a GRPC UserService_ComposeCreatorWithUserId_Request struct
func (msg *UserService_ComposeCreatorWithUserId_Request) unmarshall() (reqID int64, userID int64, username string) {
	reqID = int64(msg.ReqID)
	userID = int64(msg.UserID)
	username = string(msg.Username)
	return
}

// Server-side function to pack UserService.ComposeCreatorWithUserId retvals into a GRPC UserService_ComposeCreatorWithUserId_Response struct
func (msg *UserService_ComposeCreatorWithUserId_Response) marshall(ret0 socialnetwork.Creator) *UserService_ComposeCreatorWithUserId_Response {
	msg.Ret0 = new(UserService_Creator).marshall(&ret0)
	return msg
}

// Client-side function to unpack UserService.ComposeCreatorWithUserId retvals from a GRPC UserService_ComposeCreatorWithUserId_Response struct
func (msg *UserService_ComposeCreatorWithUserId_Response) unmarshall() (ret0 socialnetwork.Creator) {
	msg.Ret0.unmarshall(&ret0)
	return
}

// Client-side function to pack UserService.ComposeCreatorWithUsername args into a GRPC UserService_ComposeCreatorWithUsername_Request struct
func (msg *UserService_ComposeCreatorWithUsername_Request) marshall(reqID int64, username string) *UserService_ComposeCreatorWithUsername_Request {
	msg.ReqID = int64(reqID)
	msg.Username = string(username)
	return msg
}

// Server-side function to unpack UserService.ComposeCreatorWithUsername args from a GRPC UserService_ComposeCreatorWithUsername_Request struct
func (msg *UserService_ComposeCreatorWithUsername_Request) unmarshall() (reqID int64, username string) {
	reqID = int64(msg.ReqID)
	username = string(msg.Username)
	return
}

// Server-side function to pack UserService.ComposeCreatorWithUsername retvals into a GRPC UserService_ComposeCreatorWithUsername_Response struct
func (msg *UserService_ComposeCreatorWithUsername_Response) marshall(ret0 socialnetwork.Creator) *UserService_ComposeCreatorWithUsername_Response {
	msg.Ret0 = new(UserService_Creator).marshall(&ret0)
	return msg
}

// Client-side function to unpack UserService.ComposeCreatorWithUsername retvals from a GRPC UserService_ComposeCreatorWithUsername_Response struct
func (msg *UserService_ComposeCreatorWithUsername_Response) unmarshall() (ret0 socialnetwork.Creator) {
	msg.Ret0.unmarshall(&ret0)
	return
}

// Client-side function to pack UserService.Login args into a GRPC UserService_Login_Request struct
func (msg *UserService_Login_Request) marshall(reqID int64, username string, password string) *UserService_Login_Request {
	msg.ReqID = int64(reqID)
	msg.Username = string(username)
	msg.Password = string(password)
	return msg
}

// Server-side function to unpack UserService.Login args from a GRPC UserService_Login_Request struct
func (msg *UserService_Login_Request) unmarshall() (reqID int64, username string, password string) {
	reqID = int64(msg.ReqID)
	username = string(msg.Username)
	password = string(msg.Password)
	return
}

// Server-side function to pack UserService.Login retvals into a GRPC UserService_Login_Response struct
func (msg *UserService_Login_Response) marshall(ret0 string) *UserService_Login_Response {
	msg.Ret0 = string(ret0)
	return msg
}

// Client-side function to unpack UserService.Login retvals from a GRPC UserService_Login_Response struct
func (msg *UserService_Login_Response) unmarshall() (ret0 string) {
	ret0 = string(msg.Ret0)
	return
}

// Client-side function to pack UserService.RegisterUser args into a GRPC UserService_RegisterUser_Request struct
func (msg *UserService_RegisterUser_Request) marshall(reqID int64, firstName string, lastName string, username string, password string) *UserService_RegisterUser_Request {
	msg.ReqID = int64(reqID)
	msg.FirstName = string(firstName)
	msg.LastName = string(lastName)
	msg.Username = string(username)
	msg.Password = string(password)
	return msg
}

// Server-side function to unpack UserService.RegisterUser args from a GRPC UserService_RegisterUser_Request struct
func (msg *UserService_RegisterUser_Request) unmarshall() (reqID int64, firstName string, lastName string, username string, password string) {
	reqID = int64(msg.ReqID)
	firstName = string(msg.FirstName)
	lastName = string(msg.LastName)
	username = string(msg.Username)
	password = string(msg.Password)
	return
}

// Server-side function to pack UserService.RegisterUser retvals into a GRPC UserService_RegisterUser_Response struct
func (msg *UserService_RegisterUser_Response) marshall() *UserService_RegisterUser_Response {
	return msg
}

// Client-side function to unpack UserService.RegisterUser retvals from a GRPC UserService_RegisterUser_Response struct
func (msg *UserService_RegisterUser_Response) unmarshall() () {
	return
}

// Client-side function to pack UserService.RegisterUserWithId args into a GRPC UserService_RegisterUserWithId_Request struct
func (msg *UserService_RegisterUserWithId_Request) marshall(reqID int64, firstName string, lastName string, username string, password string, userID int64) *UserService_RegisterUserWithId_Request {
	msg.ReqID = int64(reqID)
	msg.FirstName = string(firstName)
	msg.LastName = string(lastName)
	msg.Username = string(username)
	msg.Password = string(password)
	msg.UserID = int64(userID)
	return msg
}

// Server-side function to unpack UserService.RegisterUserWithId args from a GRPC UserService_RegisterUserWithId_Request struct
func (msg *UserService_RegisterUserWithId_Request) unmarshall() (reqID int64, firstName string, lastName string, username string, password string, userID int64) {
	reqID = int64(msg.ReqID)
	firstName = string(msg.FirstName)
	lastName = string(msg.LastName)
	username = string(msg.Username)
	password = string(msg.Password)
	userID = int64(msg.UserID)
	return
}

// Server-side function to pack UserService.RegisterUserWithId retvals into a GRPC UserService_RegisterUserWithId_Response struct
func (msg *UserService_RegisterUserWithId_Response) marshall() *UserService_RegisterUserWithId_Response {
	return msg
}

// Client-side function to unpack UserService.RegisterUserWithId retvals from a GRPC UserService_RegisterUserWithId_Response struct
func (msg *UserService_RegisterUserWithId_Response) unmarshall() () {
	return
}


// Utility function to pack socialnetwork.Creator into a GRPC UserService_Creator message
func (msg *UserService_Creator) marshall(obj *socialnetwork.Creator) *UserService_Creator {
	msg.UserID = int64(obj.UserID)
	msg.Username = string(obj.Username)
	return msg
}

// Utility function to unpack socialnetwork.Creator from a GRPC UserService_Creator message
func (msg *UserService_Creator) unmarshall(obj *socialnetwork.Creator) {
	obj.UserID = int64(msg.UserID)
	obj.Username = string(msg.Username)
}

