apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_cgpb/k8s
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: otelcol-cgpb-ctr
  name: otelcol-cgpb-ctr
spec:
  selector:
    matchLabels:
      io.kompose.service: otelcol-cgpb-ctr
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_cgpb/k8s
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: otelcol-cgpb-ctr
    spec:
      containers:
      - env:
        - name: JAEGER_CGPB_OTLP_DIAL_ADDR
          value: jaeger-cgpb-ctr:4317
        image: 10.10.1.1:30000/otelcol-cgpb-ctr:latest
        name: otelcol-cgpb-ctr
        ports:
        - containerPort: 4317
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
      hostname: otelcol-cgpb-ctr
      restartPolicy: Always
