apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_cgpb/k8s
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: post-db-cgpb-ctr
  name: post-db-cgpb-ctr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: post-db-cgpb-ctr
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_cgpb/k8s
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: post-db-cgpb-ctr
    spec:
      containers:
      - image: 10.10.1.1:30000/mongo:4.4
        name: post-db-cgpb-ctr
        ports:
        - containerPort: 27017
          protocol: TCP
      hostname: post-db-cgpb-ctr
      restartPolicy: Always
