apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_cgpb/k8s
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: socialgraph-service-cgpb-ctr
  name: socialgraph-service-cgpb-ctr
spec:
  ports:
  - name: '12360'
    port: 12360
    targetPort: 12345
  - name: '12345'
    port: 12345
    targetPort: 12345
  selector:
    io.kompose.service: socialgraph-service-cgpb-ctr
