apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_cgpb/k8s
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: user-cache-cgpb-ctr
  name: user-cache-cgpb-ctr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-cache-cgpb-ctr
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_cgpb/k8s
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: user-cache-cgpb-ctr
    spec:
      containers:
      - image: 10.10.1.1:30000/redis:latest
        name: user-cache-cgpb-ctr
        ports:
        - containerPort: 6379
          protocol: TCP
        resources:
          requests:
            cpu: 3000m
      hostname: user-cache-cgpb-ctr
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: node-8
