apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_cgpb/k8s
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: wrk2api-service-cgpb-ctr
  name: wrk2api-service-cgpb-ctr
spec:
  selector:
    matchLabels:
      io.kompose.service: wrk2api-service-cgpb-ctr
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_cgpb/k8s
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: wrk2api-service-cgpb-ctr
    spec:
      containers:
      - env:
        - name: COMPOSEPOST_SERVICE_CGPB_GRPC_DIAL_ADDR
          value: composepost-service-cgpb-ctr:12345
        - name: HOMETIMELINE_SERVICE_CGPB_GRPC_DIAL_ADDR
          value: hometimeline-service-cgpb-ctr:12345
        - name: OTELCOL_CGPB_DIAL_ADDR
          value: otelcol-cgpb-ctr:4317
        - name: SOCIALGRAPH_SERVICE_CGPB_GRPC_DIAL_ADDR
          value: socialgraph-service-cgpb-ctr:12345
        - name: USERTIMELINE_SERVICE_CGPB_GRPC_DIAL_ADDR
          value: usertimeline-service-cgpb-ctr:12345
        - name: USER_SERVICE_CGPB_GRPC_DIAL_ADDR
          value: user-service-cgpb-ctr:12345
        - name: WRK2API_SERVICE_CGPB_HTTP_BIND_ADDR
          value: 0.0.0.0:2000
        image: 10.10.1.1:30000/wrk2api-service-cgpb-ctr:latest
        name: wrk2api-service-cgpb-ctr
        ports:
        - containerPort: 2000
          protocol: TCP
      hostname: wrk2api-service-cgpb-ctr
      restartPolicy: Always
