// This file is auto-generated by the Blueprint clientpool plugin
package pool

import (
	"github.com/blueprint-uservices/blueprint/runtime/plugins/golang"
	"blueprint/testclients/ot"
	"github.com/blueprint-uservices/blueprint/examples/dsb_sn/workflow/socialnetwork"
	"context"
	"fmt"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/clientpool"
)

type UrlShortenService_OTClientWrapperInterface_ClientPool struct {
	clients *clientpool.ClientPool[ot.UrlShortenService_OTClientWrapperInterface]
}

func New_UrlShortenService_Pool(parent *golang.Namespace) *UrlShortenService_OTClientWrapperInterface_ClientPool {
	i := 0
	createClient := func() (ot.UrlShortenService_OTClientWrapperInterface, error) {
		clientName := fmt.Sprintf("urlshorten_service_v4.clientpool.%v", i)
		n, err := New_UrlShortenService_PoolClient(clientName).BuildWithParent(parent)
		if err != nil {
			return nil, err
		}
		i++
		var client ot.UrlShortenService_OTClientWrapperInterface
		err = n.Get("urlshorten_service_v4.client.ot", &client)
		return client, err
	}
	clients := clientpool.NewClientPool(20, createClient)
	return &UrlShortenService_OTClientWrapperInterface_ClientPool{clients: clients}
}


func (pool *UrlShortenService_OTClientWrapperInterface_ClientPool) ComposeUrls(ctx context.Context, reqID int64, urls []string) (ret0 []socialnetwork.URL, err error) {
	client, err := pool.clients.Pop(ctx)
	if err != nil {
		return
	}
	defer pool.clients.Push(client)
	return client.ComposeUrls(ctx, reqID, urls)
}

func (pool *UrlShortenService_OTClientWrapperInterface_ClientPool) GetExtendedUrls(ctx context.Context, reqID int64, shortenedUrls []string) (ret0 []string, err error) {
	client, err := pool.clients.Pop(ctx)
	if err != nil {
		return
	}
	defer pool.clients.Push(client)
	return client.GetExtendedUrls(ctx, reqID, shortenedUrls)
}



