apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_pb/k8s
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: jaeger-pb-ctr
  name: jaeger-pb-ctr
spec:
  ports:
  - name: '12349'
    port: 12349
    targetPort: 14268
  - name: '12350'
    port: 12350
    targetPort: 4317
  - name: '12351'
    port: 12351
    targetPort: 16686
  - name: '4317'
    port: 4317
    targetPort: 4317
  - name: '14268'
    port: 14268
    targetPort: 14268
  - name: '16686'
    port: 16686
    targetPort: 16686
  selector:
    io.kompose.service: jaeger-pb-ctr
