apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_pb/k8s
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: social-db-pb-ctr
  name: social-db-pb-ctr
spec:
  ports:
  - name: '12359'
    port: 12359
    targetPort: 27017
  - name: '27017'
    port: 27017
    targetPort: 27017
  selector:
    io.kompose.service: social-db-pb-ctr
