// Blueprint: Auto-generated by Retries Plugin
package retries

import (
	"blueprint/goproc/composepost_service_cgpb_es_nw_proc/ot"
	"context"

	"github.com/blueprint-uservices/blueprint/examples/dsb_sn/workflow/snnw"
)

type TextService_RetrierClient struct {
	Client   ot.TextService_OTClientWrapperInterface
	MaxTries int
}

func New_TextService_RetrierClient(ctx context.Context, client ot.TextService_OTClientWrapperInterface) (*TextService_RetrierClient, error) {
	handler := &TextService_RetrierClient{}
	handler.Client = client
	handler.MaxTries = 3
	return handler, nil
}

func (client *TextService_RetrierClient) ComposeText(ctx context.Context, reqID int64, text string) (ret0 string, ret1 []snnw.UserMention, ret2 []snnw.URL, err error) {
	for i := 0; i < client.MaxTries; i++ {
		ret0, ret1, ret2, err = client.Client.ComposeText(ctx, reqID, text)
		if err == nil {
			return
		}
	}
	return
}
