// post_storage_service_nt_proc runs the post_storage_service_nt_proc Golang process.
//
// post_storage_service_nt_proc is auto-generated by Blueprint's goproc plugin (goproc/goprocgen/main.go.go)
//
// Usage:
//
//   go run main.go --post_cache_nt.dial_addr=value --post_db_nt.dial_addr=value --post_storage_service_nt.grpc.bind_addr=value 
//
// post_storage_service_nt_proc requires the following arguments are passed:
//
//   --post_cache_nt.dial_addr
//       Auto-generated by Blueprint IR node:
//       post_cache_nt.dial_addr = AddressConfig()
//
//   --post_db_nt.dial_addr
//       Auto-generated by Blueprint IR node:
//       post_db_nt.dial_addr = AddressConfig()
//
//   --post_storage_service_nt.grpc.bind_addr
//       Auto-generated by Blueprint IR node:
//       post_storage_service_nt.grpc.bind_addr = AddressConfig()
//
// post_storage_service_nt_proc will instantiate the following IR nodes:
//   post_storage_service_nt_proc.stdoutmetriccollector
//   post_storage_service_nt_proc.logger
//   post_cache_nt.client
//   post_db_nt.client
//   post_storage_service_nt
//   post_storage_service_nt.grpc_server
package main

import (
	"context"
	"os"

	"log/slog"
)

func main() {
	slog.Info("Running post_storage_service_nt_proc")
	n, err := New_post_storage_service_nt_proc("post_storage_service_nt_proc").Build(context.Background())
	if err != nil {
		slog.Error(err.Error())
		os.Exit(1)
	}
	n.Await()
	slog.Info("post_storage_service_nt_proc exiting")
}