// Package main is auto-generated by gogen/namespacebuilder.go
//
// It provides funcs for instantiating the tracepressure_service_pb_estest_proc namespace.
//
// To instantiate the tracepressure_service_pb_estest_proc namespace, first call [New_tracepressure_service_pb_estest_proc] and then either call
// [Build] or [BuildWithParent].
//
// See [golang.NamespaceBuilder] docs for more information about the behavior of [Build]
package main

import (
	"blueprint/goproc/tracepressure_service_pb_estest_proc/http"
	"blueprint/goproc/tracepressure_service_pb_estest_proc/ot"

	"github.com/blueprint-uservices/blueprint/examples/dsb_sn/workflow/socialnetwork"
	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/golang"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/opentelemetry"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/otelcol"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/slogger"
)

// Initializes the tracepressure_service_pb_estest_proc namespace by defining all of the nodes that run
// within the namespace.
//
// [Build] or [BuildWithParent] must be called on the return value of this func
// to actually build and run the nodes in the namespace.
func New_tracepressure_service_pb_estest_proc(name string) *golang.NamespaceBuilder {
	b := golang.NewNamespaceBuilder(name)
	set_tracepressure_service_pb_estest_proc_Args(b)
	set_tracepressure_service_pb_estest_proc_Instances(b)
	set_tracepressure_service_pb_estest_proc_Definitions(b)
	return b
}

// tracepressure_service_pb_estest_proc requires that its arguments are either:
//   - explicitly set with [golang.NamespaceBuilder.Set]
//   - passed on the command line (if built using [golang.NamespaceBuilder.Build])
//   - are defined in parent (if built using [golang.NamespaceBuilder.BuildWithParent])
//
// The following arguments will be eagerly checked and building the namespace
// will fail if they haven't been provided:
//
//	otelcol_pb_estest.dial_addr
//	tracepressure_service_pb_estest.http.bind_addr
//
// The following arguments are optional and a failure will only occur if the client
// tries to build a node that needs the argument to be set
func set_tracepressure_service_pb_estest_proc_Args(b *golang.NamespaceBuilder) {
	b.Required("otelcol_pb_estest.dial_addr", "Argument generated by Blueprint IR: otelcol_pb_estest.dial_addr = AddressConfig()")
	b.Required("tracepressure_service_pb_estest.http.bind_addr", "Argument generated by Blueprint IR: tracepressure_service_pb_estest.http.bind_addr = AddressConfig()")
}

// When the tracepressure_service_pb_estest_proc namespace is built it will automatically instantiate
// the following nodes:
//
//	tracepressure_service_pb_estest_proc.stdoutmetriccollector
//	tracepressure_service_pb_estest_proc.logger
//	tracepressure_service_pb_estest
//	otelcol_pb_estest.client
//	tracepressure_service_pb_estest.server.ot
//	tracepressure_service_pb_estest.http_server
func set_tracepressure_service_pb_estest_proc_Instances(b *golang.NamespaceBuilder) {
	b.Instantiate("tracepressure_service_pb_estest_proc.stdoutmetriccollector")
	b.Instantiate("tracepressure_service_pb_estest_proc.logger")
	b.Instantiate("tracepressure_service_pb_estest")
	b.Instantiate("otelcol_pb_estest.client")
	b.Instantiate("tracepressure_service_pb_estest.server.ot")
	b.Instantiate("tracepressure_service_pb_estest.http_server")
}

// The tracepressure_service_pb_estest_proc namespace contains definitions for instantiating
// the following nodes:
//
//	otelcol_pb_estest.client
//	tracepressure_service_pb_estest
//	tracepressure_service_pb_estest.http_server
//	tracepressure_service_pb_estest.server.ot
//	tracepressure_service_pb_estest_proc.logger
//	tracepressure_service_pb_estest_proc.stdoutmetriccollector
func set_tracepressure_service_pb_estest_proc_Definitions(b *golang.NamespaceBuilder) {
	b.Define("otelcol_pb_estest.client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var addr string
		if err := n.Get("otelcol_pb_estest.dial_addr", &addr); err != nil {
			return nil, err
		}

		return otelcol.NewOTCollectorTracer(n.Context(), addr, "8080")
	})

	b.Define("tracepressure_service_pb_estest", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		return socialnetwork.NewTracePressureServiceImpl(n.Context())
	})

	b.Define("tracepressure_service_pb_estest.http_server", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var service ot.TracePressureService_OTServerWrapperInterface
		if err := n.Get("tracepressure_service_pb_estest.server.ot", &service); err != nil {
			return nil, err
		}

		var serverAddr string
		if err := n.Get("tracepressure_service_pb_estest.http.bind_addr", &serverAddr); err != nil {
			return nil, err
		}

		return http.New_TracePressureService_HTTPServerHandler(n.Context(), service, serverAddr)
	})

	b.Define("tracepressure_service_pb_estest.server.ot", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var service socialnetwork.TracePressureService
		if err := n.Get("tracepressure_service_pb_estest", &service); err != nil {
			return nil, err
		}

		var otCollectorClient backend.Tracer
		if err := n.Get("otelcol_pb_estest.client", &otCollectorClient); err != nil {
			return nil, err
		}

		return ot.New_TracePressureService_OTServerWrapper(n.Context(), service, otCollectorClient)
	})

	b.Define("tracepressure_service_pb_estest_proc.logger", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		return slogger.NewSLogger(n.Context())
	})

	b.Define("tracepressure_service_pb_estest_proc.stdoutmetriccollector", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		return opentelemetry.NewStdoutMetricCollector(n.Context())
	})

}
