// composepost_service_pb_esrev2ph_proc runs the composepost_service_pb_esrev2ph_proc Golang process.
//
// composepost_service_pb_esrev2ph_proc is auto-generated by Blueprint's goproc plugin (goproc/goprocgen/main.go.go)
//
// Usage:
//
//	go run main.go --post_storage_service_pb_esrev2ph.grpc.dial_addr=value --otelcol_pb_esrev2ph.dial_addr=value --usertimeline_service_pb_esrev2ph.grpc.dial_addr=value --user_service_pb_esrev2ph.grpc.dial_addr=value --uniqueid_service_pb_esrev2ph.grpc.dial_addr=value --media_service_pb_esrev2ph.grpc.dial_addr=value --text_service_pb_esrev2ph.grpc.dial_addr=value --hometimeline_service_pb_esrev2ph.grpc.dial_addr=value --composepost_service_pb_esrev2ph.grpc.bind_addr=value
//
// Optional env: GC_INTERVAL_SEC=N (e.g. 30, 1, 0.5, 0.1) to run GC every N seconds; fractional seconds supported. Omit or <=0 for default GC.
//
// composepost_service_pb_esrev2ph_proc requires the following arguments are passed:
//
//	--post_storage_service_pb_esrev2ph.grpc.dial_addr
//	    Auto-generated by Blueprint IR node:
//	    post_storage_service_pb_esrev2ph.grpc.dial_addr = AddressConfig()
//
//	--otelcol_pb_esrev2ph.dial_addr
//	    Auto-generated by Blueprint IR node:
//	    otelcol_pb_esrev2ph.dial_addr = AddressConfig()
//
//	--usertimeline_service_pb_esrev2ph.grpc.dial_addr
//	    Auto-generated by Blueprint IR node:
//	    usertimeline_service_pb_esrev2ph.grpc.dial_addr = AddressConfig()
//
//	--user_service_pb_esrev2ph.grpc.dial_addr
//	    Auto-generated by Blueprint IR node:
//	    user_service_pb_esrev2ph.grpc.dial_addr = AddressConfig()
//
//	--uniqueid_service_pb_esrev2ph.grpc.dial_addr
//	    Auto-generated by Blueprint IR node:
//	    uniqueid_service_pb_esrev2ph.grpc.dial_addr = AddressConfig()
//
//	--media_service_pb_esrev2ph.grpc.dial_addr
//	    Auto-generated by Blueprint IR node:
//	    media_service_pb_esrev2ph.grpc.dial_addr = AddressConfig()
//
//	--text_service_pb_esrev2ph.grpc.dial_addr
//	    Auto-generated by Blueprint IR node:
//	    text_service_pb_esrev2ph.grpc.dial_addr = AddressConfig()
//
//	--hometimeline_service_pb_esrev2ph.grpc.dial_addr
//	    Auto-generated by Blueprint IR node:
//	    hometimeline_service_pb_esrev2ph.grpc.dial_addr = AddressConfig()
//
//	--composepost_service_pb_esrev2ph.grpc.bind_addr
//	    Auto-generated by Blueprint IR node:
//	    composepost_service_pb_esrev2ph.grpc.bind_addr = AddressConfig()
//
// composepost_service_pb_esrev2ph_proc will instantiate the following IR nodes:
//
//	composepost_service_pb_esrev2ph_proc.stdoutmetriccollector
//	composepost_service_pb_esrev2ph_proc.logger
//	post_storage_service_pb_esrev2ph.grpc_client
//	otelcol_pb_esrev2ph.client
//	post_storage_service_pb_esrev2ph.client.ot
//	post_storage_service_pb_esrev2ph.client.retrier
//	post_storage_service_pb_esrev2ph.client
//	usertimeline_service_pb_esrev2ph.grpc_client
//	usertimeline_service_pb_esrev2ph.client.ot
//	usertimeline_service_pb_esrev2ph.client.retrier
//	usertimeline_service_pb_esrev2ph.client
//	user_service_pb_esrev2ph.grpc_client
//	user_service_pb_esrev2ph.client.ot
//	user_service_pb_esrev2ph.client.retrier
//	user_service_pb_esrev2ph.client
//	uniqueid_service_pb_esrev2ph.grpc_client
//	uniqueid_service_pb_esrev2ph.client.ot
//	uniqueid_service_pb_esrev2ph.client.retrier
//	uniqueid_service_pb_esrev2ph.client
//	media_service_pb_esrev2ph.grpc_client
//	media_service_pb_esrev2ph.client.ot
//	media_service_pb_esrev2ph.client.retrier
//	media_service_pb_esrev2ph.client
//	text_service_pb_esrev2ph.grpc_client
//	text_service_pb_esrev2ph.client.ot
//	text_service_pb_esrev2ph.client.retrier
//	text_service_pb_esrev2ph.client
//	hometimeline_service_pb_esrev2ph.grpc_client
//	hometimeline_service_pb_esrev2ph.client.ot
//	hometimeline_service_pb_esrev2ph.client.retrier
//	hometimeline_service_pb_esrev2ph.client
//	composepost_service_pb_esrev2ph
//	composepost_service_pb_esrev2ph.server.ot
//	composepost_service_pb_esrev2ph.grpc_server
package main

import (
	"context"
	"os"
	"runtime"
	"strconv"
	"time"

	"log/slog"
)

func main() {
	// Optional: run GC on a fixed interval to normalize GC frequency (e.g. across tracing vs no-tracing).
	// Set GC_INTERVAL_SEC to a positive number (e.g. 30, 1, 0.5, 0.1) to trigger runtime.GC() every N seconds; unset or <=0 to leave default GC behavior.
	if sec := os.Getenv("GC_INTERVAL_SEC"); sec != "" {
		if secVal, err := strconv.ParseFloat(sec, 64); err == nil && secVal > 0 && secVal < 1e15 {
			interval := time.Duration(secVal * float64(time.Second))
			if interval > 0 {
				go func() {
					ticker := time.NewTicker(interval)
					defer ticker.Stop()
					for range ticker.C {
						runtime.GC()
					}
				}()
			}
		}
	}
	slog.Info("Running composepost_service_pb_esrev2ph_proc")
	n, err := New_composepost_service_pb_esrev2ph_proc("composepost_service_pb_esrev2ph_proc").Build(context.Background())
	if err != nil {
		slog.Error(err.Error())
		os.Exit(1)
	}
	n.Await()
	slog.Info("composepost_service_pb_esrev2ph_proc exiting")
}
