// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: ComposePostService.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ComposePostService_ComposePost_FullMethodName = "/grpc.ComposePostService/ComposePost"
)

// ComposePostServiceClient is the client API for ComposePostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ComposePostServiceClient interface {
	ComposePost(ctx context.Context, in *ComposePostService_ComposePost_Request, opts ...grpc.CallOption) (*ComposePostService_ComposePost_Response, error)
}

type composePostServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewComposePostServiceClient(cc grpc.ClientConnInterface) ComposePostServiceClient {
	return &composePostServiceClient{cc}
}

func (c *composePostServiceClient) ComposePost(ctx context.Context, in *ComposePostService_ComposePost_Request, opts ...grpc.CallOption) (*ComposePostService_ComposePost_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComposePostService_ComposePost_Response)
	err := c.cc.Invoke(ctx, ComposePostService_ComposePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ComposePostServiceServer is the server API for ComposePostService service.
// All implementations must embed UnimplementedComposePostServiceServer
// for forward compatibility.
type ComposePostServiceServer interface {
	ComposePost(context.Context, *ComposePostService_ComposePost_Request) (*ComposePostService_ComposePost_Response, error)
	mustEmbedUnimplementedComposePostServiceServer()
}

// UnimplementedComposePostServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedComposePostServiceServer struct{}

func (UnimplementedComposePostServiceServer) ComposePost(context.Context, *ComposePostService_ComposePost_Request) (*ComposePostService_ComposePost_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ComposePost not implemented")
}
func (UnimplementedComposePostServiceServer) mustEmbedUnimplementedComposePostServiceServer() {}
func (UnimplementedComposePostServiceServer) testEmbeddedByValue()                            {}

// UnsafeComposePostServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ComposePostServiceServer will
// result in compilation errors.
type UnsafeComposePostServiceServer interface {
	mustEmbedUnimplementedComposePostServiceServer()
}

func RegisterComposePostServiceServer(s grpc.ServiceRegistrar, srv ComposePostServiceServer) {
	// If the following call panics, it indicates UnimplementedComposePostServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ComposePostService_ServiceDesc, srv)
}

func _ComposePostService_ComposePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComposePostService_ComposePost_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComposePostServiceServer).ComposePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComposePostService_ComposePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComposePostServiceServer).ComposePost(ctx, req.(*ComposePostService_ComposePost_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// ComposePostService_ServiceDesc is the grpc.ServiceDesc for ComposePostService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ComposePostService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.ComposePostService",
	HandlerType: (*ComposePostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ComposePost",
			Handler:    _ComposePostService_ComposePost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ComposePostService.proto",
}
