// Blueprint: Auto-generated by OpenTelemetry Plugin
package ot

import (
	"sync/atomic"
	"strconv"
	"encoding/binary"
	"github.com/blueprint-uservices/blueprint/examples/leaf/workflow/leaf"
	"context"
	"go.opentelemetry.io/otel/trace"
	"encoding/base64"
	"go.opentelemetry.io/otel/attribute"
	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"strings"
	trace2 "go.opentelemetry.io/otel/sdk/trace"
)

type LeafService_OTServerWrapperInterface interface {
	HelloInt(ctx context.Context, a int64, traceCtx string) (int64, string, error)
	HelloMate(ctx context.Context, a int, b int32, c string, d map[string]leaf.LeafObject, elems []string, elems2 []leaf.NestedLeafObject, traceCtx string) (string, []string, int32, int, map[string]leaf.LeafObject, string, error)
	HelloNothing(ctx context.Context, traceCtx string) (string, error)
	HelloObject(ctx context.Context, obj *leaf.LeafObject, traceCtx string) (*leaf.LeafObject, string, error)
	
}

type LeafService_OTServerWrapper struct {
	Service leaf.LeafService
	CollClient backend.Tracer
}

func New_LeafService_OTServerWrapper(ctx context.Context, service leaf.LeafService, coll_client backend.Tracer) (*LeafService_OTServerWrapper, error) {
	handler := &LeafService_OTServerWrapper{}
	handler.Service = service
	handler.CollClient = coll_client
	return handler, nil
}


func (handler *LeafService_OTServerWrapper) HelloInt(ctx context.Context, a int64, traceCtx string) (ret0 int64, retCtx string, err error) {
	// Sampling-aware fast path: compact "U:" carrier = head-unsampled upstream ->
	// skip JSON deserialize/baggage/span; restore remote ctx and call the service.
	if len(traceCtx) >= 50 && traceCtx[0:2] == "U:" {
		tid, _ := trace.TraceIDFromHex(traceCtx[2:34])
		sid, _ := trace.SpanIDFromHex(traceCtx[34:50])
		rsc := trace.NewSpanContext(trace.SpanContextConfig{TraceID: tid, SpanID: sid, Remote: true})
		ctx = trace.ContextWithRemoteSpanContext(ctx, rsc)
		ret0, err = handler.Service.HelloInt(ctx, a)
		return
	}
	var baggage map[string]string
	if traceCtx != "" {
		span_ctx_config, upstreamBaggage, _ := backend.GetSpanContext(traceCtx)
		span_ctx := trace.NewSpanContext(span_ctx_config)
		ctx = trace.ContextWithRemoteSpanContext(ctx, span_ctx)
		
		// Set baggage in context for span processor to read
		if upstreamBaggage != nil {
			baggage = upstreamBaggage
			ctx = backend.SetBaggageInContext(ctx, baggage)
		}
	}

	// Fanout ordinal: the caller stamped this span's child ordinal in baggage
	// ("__seq"). Set it on ctx BEFORE the server span starts so the bridge
	// processor's OnStart reads the correct seqNum (else it defaults to 0 and
	// CGPB HA / SB ordinals are never emitted).
	if baggage != nil {
		if sv, ok := baggage["__seq"]; ok {
			if n, e := strconv.Atoi(sv); e == nil {
				ctx = context.WithValue(ctx, "seqNum", n)
			}
		}
	}

	tp, _ := handler.CollClient.GetTracerProvider(ctx)
	tr := tp.Tracer("LeafService")
	ctx, span := tr.Start(ctx, "LeafServiceServer_HelloInt", trace.WithSpanKind(trace.SpanKindServer))
	defer span.End()

	// Extract new baggage from span attributes by casting to ReadWriteSpan
	if baggage == nil {
		baggage = make(map[string]string)
	}
	if rwSpan, ok := span.(trace2.ReadWriteSpan); ok {
		for _, attr := range rwSpan.Attributes() {
			if strings.HasPrefix(string(attr.Key), "__bag.") {
				key := strings.TrimPrefix(string(attr.Key), "__bag.")
				// Convert value to string for baggage based on attribute type
				switch attr.Value.Type() {
				case attribute.INT64:
					baggage[key] = strconv.FormatInt(attr.Value.AsInt64(), 10)
				case attribute.STRING:
					baggage[key] = attr.Value.AsString()
				default:
					baggage[key] = attr.Value.AsString()
				}
			} else if strings.HasPrefix(string(attr.Key), "__bagdel.") {
				key := strings.TrimPrefix(string(attr.Key), "__bagdel.")
				delete(baggage, key)
			}
		}
	}

	// Update context with merged baggage BEFORE calling the service
	if baggage != nil {
		ctx = backend.SetBaggageInContext(ctx, baggage)
	}

	childCount := atomic.Uint64{}
	ctx = context.WithValue(ctx, "childCount", &childCount)
	
	ret0, err = handler.Service.HelloInt(ctx, a)
	if err != nil {
		span.RecordError(err)
	}

	span.SetAttributes(attribute.Bool("hasChildren", int(childCount.Load()) > 0))

	// Dummy reverse-truss back to caller
	retCtx = "00-" + span.SpanContext().TraceID().String() + "-" + span.SpanContext().SpanID().String() + "-ZHVtbXk="
	return
}

func (handler *LeafService_OTServerWrapper) HelloMate(ctx context.Context, a int, b int32, c string, d map[string]leaf.LeafObject, elems []string, elems2 []leaf.NestedLeafObject, traceCtx string) (ret0 string, ret1 []string, ret2 int32, ret3 int, ret4 map[string]leaf.LeafObject, retCtx string, err error) {
	// Sampling-aware fast path: compact "U:" carrier = head-unsampled upstream ->
	// skip JSON deserialize/baggage/span; restore remote ctx and call the service.
	if len(traceCtx) >= 50 && traceCtx[0:2] == "U:" {
		tid, _ := trace.TraceIDFromHex(traceCtx[2:34])
		sid, _ := trace.SpanIDFromHex(traceCtx[34:50])
		rsc := trace.NewSpanContext(trace.SpanContextConfig{TraceID: tid, SpanID: sid, Remote: true})
		ctx = trace.ContextWithRemoteSpanContext(ctx, rsc)
		ret0, ret1, ret2, ret3, ret4, err = handler.Service.HelloMate(ctx, a, b, c, d, elems, elems2)
		return
	}
	var baggage map[string]string
	if traceCtx != "" {
		span_ctx_config, upstreamBaggage, _ := backend.GetSpanContext(traceCtx)
		span_ctx := trace.NewSpanContext(span_ctx_config)
		ctx = trace.ContextWithRemoteSpanContext(ctx, span_ctx)
		
		// Set baggage in context for span processor to read
		if upstreamBaggage != nil {
			baggage = upstreamBaggage
			ctx = backend.SetBaggageInContext(ctx, baggage)
		}
	}

	// Fanout ordinal: the caller stamped this span's child ordinal in baggage
	// ("__seq"). Set it on ctx BEFORE the server span starts so the bridge
	// processor's OnStart reads the correct seqNum (else it defaults to 0 and
	// CGPB HA / SB ordinals are never emitted).
	if baggage != nil {
		if sv, ok := baggage["__seq"]; ok {
			if n, e := strconv.Atoi(sv); e == nil {
				ctx = context.WithValue(ctx, "seqNum", n)
			}
		}
	}

	tp, _ := handler.CollClient.GetTracerProvider(ctx)
	tr := tp.Tracer("LeafService")
	ctx, span := tr.Start(ctx, "LeafServiceServer_HelloMate", trace.WithSpanKind(trace.SpanKindServer))
	defer span.End()

	// Extract new baggage from span attributes by casting to ReadWriteSpan
	if baggage == nil {
		baggage = make(map[string]string)
	}
	if rwSpan, ok := span.(trace2.ReadWriteSpan); ok {
		for _, attr := range rwSpan.Attributes() {
			if strings.HasPrefix(string(attr.Key), "__bag.") {
				key := strings.TrimPrefix(string(attr.Key), "__bag.")
				// Convert value to string for baggage based on attribute type
				switch attr.Value.Type() {
				case attribute.INT64:
					baggage[key] = strconv.FormatInt(attr.Value.AsInt64(), 10)
				case attribute.STRING:
					baggage[key] = attr.Value.AsString()
				default:
					baggage[key] = attr.Value.AsString()
				}
			} else if strings.HasPrefix(string(attr.Key), "__bagdel.") {
				key := strings.TrimPrefix(string(attr.Key), "__bagdel.")
				delete(baggage, key)
			}
		}
	}

	// Update context with merged baggage BEFORE calling the service
	if baggage != nil {
		ctx = backend.SetBaggageInContext(ctx, baggage)
	}

	childCount := atomic.Uint64{}
	ctx = context.WithValue(ctx, "childCount", &childCount)
	
	ret0, ret1, ret2, ret3, ret4, err = handler.Service.HelloMate(ctx, a, b, c, d, elems, elems2)
	if err != nil {
		span.RecordError(err)
	}

	span.SetAttributes(attribute.Bool("hasChildren", int(childCount.Load()) > 0))

	// Dummy reverse-truss back to caller
	retCtx = "00-" + span.SpanContext().TraceID().String() + "-" + span.SpanContext().SpanID().String() + "-ZHVtbXk="
	return
}

func (handler *LeafService_OTServerWrapper) HelloNothing(ctx context.Context, traceCtx string) (retCtx string, err error) {
	// Sampling-aware fast path: compact "U:" carrier = head-unsampled upstream ->
	// skip JSON deserialize/baggage/span; restore remote ctx and call the service.
	if len(traceCtx) >= 50 && traceCtx[0:2] == "U:" {
		tid, _ := trace.TraceIDFromHex(traceCtx[2:34])
		sid, _ := trace.SpanIDFromHex(traceCtx[34:50])
		rsc := trace.NewSpanContext(trace.SpanContextConfig{TraceID: tid, SpanID: sid, Remote: true})
		ctx = trace.ContextWithRemoteSpanContext(ctx, rsc)
		err = handler.Service.HelloNothing(ctx)
		return
	}
	var baggage map[string]string
	if traceCtx != "" {
		span_ctx_config, upstreamBaggage, _ := backend.GetSpanContext(traceCtx)
		span_ctx := trace.NewSpanContext(span_ctx_config)
		ctx = trace.ContextWithRemoteSpanContext(ctx, span_ctx)
		
		// Set baggage in context for span processor to read
		if upstreamBaggage != nil {
			baggage = upstreamBaggage
			ctx = backend.SetBaggageInContext(ctx, baggage)
		}
	}

	// Fanout ordinal: the caller stamped this span's child ordinal in baggage
	// ("__seq"). Set it on ctx BEFORE the server span starts so the bridge
	// processor's OnStart reads the correct seqNum (else it defaults to 0 and
	// CGPB HA / SB ordinals are never emitted).
	if baggage != nil {
		if sv, ok := baggage["__seq"]; ok {
			if n, e := strconv.Atoi(sv); e == nil {
				ctx = context.WithValue(ctx, "seqNum", n)
			}
		}
	}

	tp, _ := handler.CollClient.GetTracerProvider(ctx)
	tr := tp.Tracer("LeafService")
	ctx, span := tr.Start(ctx, "LeafServiceServer_HelloNothing", trace.WithSpanKind(trace.SpanKindServer))
	defer span.End()

	// Extract new baggage from span attributes by casting to ReadWriteSpan
	if baggage == nil {
		baggage = make(map[string]string)
	}
	if rwSpan, ok := span.(trace2.ReadWriteSpan); ok {
		for _, attr := range rwSpan.Attributes() {
			if strings.HasPrefix(string(attr.Key), "__bag.") {
				key := strings.TrimPrefix(string(attr.Key), "__bag.")
				// Convert value to string for baggage based on attribute type
				switch attr.Value.Type() {
				case attribute.INT64:
					baggage[key] = strconv.FormatInt(attr.Value.AsInt64(), 10)
				case attribute.STRING:
					baggage[key] = attr.Value.AsString()
				default:
					baggage[key] = attr.Value.AsString()
				}
			} else if strings.HasPrefix(string(attr.Key), "__bagdel.") {
				key := strings.TrimPrefix(string(attr.Key), "__bagdel.")
				delete(baggage, key)
			}
		}
	}

	// Update context with merged baggage BEFORE calling the service
	if baggage != nil {
		ctx = backend.SetBaggageInContext(ctx, baggage)
	}

	childCount := atomic.Uint64{}
	ctx = context.WithValue(ctx, "childCount", &childCount)
	
	err = handler.Service.HelloNothing(ctx)
	if err != nil {
		span.RecordError(err)
	}

	span.SetAttributes(attribute.Bool("hasChildren", int(childCount.Load()) > 0))

	// Dummy reverse-truss back to caller
	retCtx = "00-" + span.SpanContext().TraceID().String() + "-" + span.SpanContext().SpanID().String() + "-ZHVtbXk="
	return
}

func (handler *LeafService_OTServerWrapper) HelloObject(ctx context.Context, obj *leaf.LeafObject, traceCtx string) (ret0 *leaf.LeafObject, retCtx string, err error) {
	// Sampling-aware fast path: compact "U:" carrier = head-unsampled upstream ->
	// skip JSON deserialize/baggage/span; restore remote ctx and call the service.
	if len(traceCtx) >= 50 && traceCtx[0:2] == "U:" {
		tid, _ := trace.TraceIDFromHex(traceCtx[2:34])
		sid, _ := trace.SpanIDFromHex(traceCtx[34:50])
		rsc := trace.NewSpanContext(trace.SpanContextConfig{TraceID: tid, SpanID: sid, Remote: true})
		ctx = trace.ContextWithRemoteSpanContext(ctx, rsc)
		ret0, err = handler.Service.HelloObject(ctx, obj)
		return
	}
	var baggage map[string]string
	if traceCtx != "" {
		span_ctx_config, upstreamBaggage, _ := backend.GetSpanContext(traceCtx)
		span_ctx := trace.NewSpanContext(span_ctx_config)
		ctx = trace.ContextWithRemoteSpanContext(ctx, span_ctx)
		
		// Set baggage in context for span processor to read
		if upstreamBaggage != nil {
			baggage = upstreamBaggage
			ctx = backend.SetBaggageInContext(ctx, baggage)
		}
	}

	// Fanout ordinal: the caller stamped this span's child ordinal in baggage
	// ("__seq"). Set it on ctx BEFORE the server span starts so the bridge
	// processor's OnStart reads the correct seqNum (else it defaults to 0 and
	// CGPB HA / SB ordinals are never emitted).
	if baggage != nil {
		if sv, ok := baggage["__seq"]; ok {
			if n, e := strconv.Atoi(sv); e == nil {
				ctx = context.WithValue(ctx, "seqNum", n)
			}
		}
	}

	tp, _ := handler.CollClient.GetTracerProvider(ctx)
	tr := tp.Tracer("LeafService")
	ctx, span := tr.Start(ctx, "LeafServiceServer_HelloObject", trace.WithSpanKind(trace.SpanKindServer))
	defer span.End()

	// Extract new baggage from span attributes by casting to ReadWriteSpan
	if baggage == nil {
		baggage = make(map[string]string)
	}
	if rwSpan, ok := span.(trace2.ReadWriteSpan); ok {
		for _, attr := range rwSpan.Attributes() {
			if strings.HasPrefix(string(attr.Key), "__bag.") {
				key := strings.TrimPrefix(string(attr.Key), "__bag.")
				// Convert value to string for baggage based on attribute type
				switch attr.Value.Type() {
				case attribute.INT64:
					baggage[key] = strconv.FormatInt(attr.Value.AsInt64(), 10)
				case attribute.STRING:
					baggage[key] = attr.Value.AsString()
				default:
					baggage[key] = attr.Value.AsString()
				}
			} else if strings.HasPrefix(string(attr.Key), "__bagdel.") {
				key := strings.TrimPrefix(string(attr.Key), "__bagdel.")
				delete(baggage, key)
			}
		}
	}

	// Update context with merged baggage BEFORE calling the service
	if baggage != nil {
		ctx = backend.SetBaggageInContext(ctx, baggage)
	}

	childCount := atomic.Uint64{}
	ctx = context.WithValue(ctx, "childCount", &childCount)
	
	ret0, err = handler.Service.HelloObject(ctx, obj)
	if err != nil {
		span.RecordError(err)
	}

	span.SetAttributes(attribute.Bool("hasChildren", int(childCount.Load()) > 0))

	// Dummy reverse-truss back to caller
	retCtx = "00-" + span.SpanContext().TraceID().String() + "-" + span.SpanContext().SpanID().String() + "-ZHVtbXk="
	return
}

