// wrk2api_service_v5_proc runs the wrk2api_service_v5_proc Golang process.
//
// wrk2api_service_v5_proc is auto-generated by Blueprint's goproc plugin (goproc/goprocgen/main.go.go)
//
// Usage:
//
//   go run main.go --user_service_v5.grpc.dial_addr=value --otelcol_v5.dial_addr=value --composepost_service_v5.grpc.dial_addr=value --usertimeline_service_v5.grpc.dial_addr=value --hometimeline_service_v5.grpc.dial_addr=value --socialgraph_service_v5.grpc.dial_addr=value --wrk2api_service_v5.http.bind_addr=value 
//
// wrk2api_service_v5_proc requires the following arguments are passed:
//
//   --user_service_v5.grpc.dial_addr
//       Auto-generated by Blueprint IR node:
//       user_service_v5.grpc.dial_addr = AddressConfig()
//
//   --otelcol_v5.dial_addr
//       Auto-generated by Blueprint IR node:
//       otelcol_v5.dial_addr = AddressConfig()
//
//   --composepost_service_v5.grpc.dial_addr
//       Auto-generated by Blueprint IR node:
//       composepost_service_v5.grpc.dial_addr = AddressConfig()
//
//   --usertimeline_service_v5.grpc.dial_addr
//       Auto-generated by Blueprint IR node:
//       usertimeline_service_v5.grpc.dial_addr = AddressConfig()
//
//   --hometimeline_service_v5.grpc.dial_addr
//       Auto-generated by Blueprint IR node:
//       hometimeline_service_v5.grpc.dial_addr = AddressConfig()
//
//   --socialgraph_service_v5.grpc.dial_addr
//       Auto-generated by Blueprint IR node:
//       socialgraph_service_v5.grpc.dial_addr = AddressConfig()
//
//   --wrk2api_service_v5.http.bind_addr
//       Auto-generated by Blueprint IR node:
//       wrk2api_service_v5.http.bind_addr = AddressConfig()
//
// wrk2api_service_v5_proc will instantiate the following IR nodes:
//   wrk2api_service_v5_proc.stdoutmetriccollector
//   wrk2api_service_v5_proc.logger
//   user_service_v5.grpc_client
//   otelcol_v5.client
//   user_service_v5.client.ot
//   user_service_v5.client.retrier
//   user_service_v5.client
//   composepost_service_v5.grpc_client
//   composepost_service_v5.client.ot
//   composepost_service_v5.client.retrier
//   composepost_service_v5.client
//   usertimeline_service_v5.grpc_client
//   usertimeline_service_v5.client.ot
//   usertimeline_service_v5.client.retrier
//   usertimeline_service_v5.client
//   hometimeline_service_v5.grpc_client
//   hometimeline_service_v5.client.ot
//   hometimeline_service_v5.client.retrier
//   hometimeline_service_v5.client
//   socialgraph_service_v5.grpc_client
//   socialgraph_service_v5.client.ot
//   socialgraph_service_v5.client.retrier
//   socialgraph_service_v5.client
//   wrk2api_service_v5
//   wrk2api_service_v5.server.ot
//   wrk2api_service_v5.http_server
package main

import (
	"context"
	"os"

	"log/slog"
)

func main() {
	slog.Info("Running wrk2api_service_v5_proc")
	n, err := New_wrk2api_service_v5_proc("wrk2api_service_v5_proc").Build(context.Background())
	if err != nil {
		slog.Error(err.Error())
		os.Exit(1)
	}
	n.Await()
	slog.Info("wrk2api_service_v5_proc exiting")
}