apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_v2/k8s
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: usertimeline-db-v2-ctr
  name: usertimeline-db-v2-ctr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: usertimeline-db-v2-ctr
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_v2/k8s
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: usertimeline-db-v2-ctr
    spec:
      containers:
      - image: 10.10.1.1:30000/mongo:4.4
        name: usertimeline-db-v2-ctr
        ports:
        - containerPort: 27017
          protocol: TCP
        resources:
          requests:
            cpu: 12000m
      hostname: usertimeline-db-v2-ctr
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: node-4
