apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_v2/k8s
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: wrk2api-service-v2-ctr
  name: wrk2api-service-v2-ctr
spec:
  ports:
  - name: '12373'
    port: 12373
    targetPort: 2000
  - name: '2000'
    port: 2000
    targetPort: 2000
  selector:
    io.kompose.service: wrk2api-service-v2-ctr
