// composepost_service_sb_proc runs the composepost_service_sb_proc Golang process.
//
// composepost_service_sb_proc is auto-generated by Blueprint's goproc plugin (goproc/goprocgen/main.go.go)
//
// Usage:
//
//   go run main.go --post_storage_service_sb.grpc.dial_addr=value --otelcol_sb.dial_addr=value --usertimeline_service_sb.grpc.dial_addr=value --user_service_sb.grpc.dial_addr=value --uniqueid_service_sb.grpc.dial_addr=value --media_service_sb.grpc.dial_addr=value --text_service_sb.grpc.dial_addr=value --hometimeline_service_sb.grpc.dial_addr=value --composepost_service_sb.grpc.bind_addr=value 
//
// composepost_service_sb_proc requires the following arguments are passed:
//
//   --post_storage_service_sb.grpc.dial_addr
//       Auto-generated by Blueprint IR node:
//       post_storage_service_sb.grpc.dial_addr = AddressConfig()
//
//   --otelcol_sb.dial_addr
//       Auto-generated by Blueprint IR node:
//       otelcol_sb.dial_addr = AddressConfig()
//
//   --usertimeline_service_sb.grpc.dial_addr
//       Auto-generated by Blueprint IR node:
//       usertimeline_service_sb.grpc.dial_addr = AddressConfig()
//
//   --user_service_sb.grpc.dial_addr
//       Auto-generated by Blueprint IR node:
//       user_service_sb.grpc.dial_addr = AddressConfig()
//
//   --uniqueid_service_sb.grpc.dial_addr
//       Auto-generated by Blueprint IR node:
//       uniqueid_service_sb.grpc.dial_addr = AddressConfig()
//
//   --media_service_sb.grpc.dial_addr
//       Auto-generated by Blueprint IR node:
//       media_service_sb.grpc.dial_addr = AddressConfig()
//
//   --text_service_sb.grpc.dial_addr
//       Auto-generated by Blueprint IR node:
//       text_service_sb.grpc.dial_addr = AddressConfig()
//
//   --hometimeline_service_sb.grpc.dial_addr
//       Auto-generated by Blueprint IR node:
//       hometimeline_service_sb.grpc.dial_addr = AddressConfig()
//
//   --composepost_service_sb.grpc.bind_addr
//       Auto-generated by Blueprint IR node:
//       composepost_service_sb.grpc.bind_addr = AddressConfig()
//
// composepost_service_sb_proc will instantiate the following IR nodes:
//   composepost_service_sb_proc.stdoutmetriccollector
//   composepost_service_sb_proc.logger
//   post_storage_service_sb.clientpool
//   post_storage_service_sb.client.retrier
//   post_storage_service_sb.client
//   usertimeline_service_sb.clientpool
//   usertimeline_service_sb.client.retrier
//   usertimeline_service_sb.client
//   user_service_sb.clientpool
//   user_service_sb.client.retrier
//   user_service_sb.client
//   uniqueid_service_sb.clientpool
//   uniqueid_service_sb.client.retrier
//   uniqueid_service_sb.client
//   media_service_sb.clientpool
//   media_service_sb.client.retrier
//   media_service_sb.client
//   text_service_sb.clientpool
//   text_service_sb.client.retrier
//   text_service_sb.client
//   hometimeline_service_sb.clientpool
//   hometimeline_service_sb.client.retrier
//   hometimeline_service_sb.client
//   composepost_service_sb
//   otelcol_sb.client
//   composepost_service_sb.server.ot
//   composepost_service_sb.grpc_server
package main

import (
	"context"
	"os"

	"log/slog"
)

func main() {
	slog.Info("Running composepost_service_sb_proc")
	n, err := New_composepost_service_sb_proc("composepost_service_sb_proc").Build(context.Background())
	if err != nil {
		slog.Error(err.Error())
		os.Exit(1)
	}
	n.Await()
	slog.Info("composepost_service_sb_proc exiting")
}