// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: ComposePostService.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ComposePostService_ComposePost_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReqID         int64                  `protobuf:"zigzag64,1,opt,name=reqID,proto3" json:"reqID,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	UserID        int64                  `protobuf:"zigzag64,3,opt,name=userID,proto3" json:"userID,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	MediaIDs      []int64                `protobuf:"zigzag64,5,rep,packed,name=mediaIDs,proto3" json:"mediaIDs,omitempty"`
	MediaTypes    []string               `protobuf:"bytes,6,rep,name=mediaTypes,proto3" json:"mediaTypes,omitempty"`
	PostType      int64                  `protobuf:"zigzag64,7,opt,name=postType,proto3" json:"postType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComposePostService_ComposePost_Request) Reset() {
	*x = ComposePostService_ComposePost_Request{}
	mi := &file_ComposePostService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComposePostService_ComposePost_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComposePostService_ComposePost_Request) ProtoMessage() {}

func (x *ComposePostService_ComposePost_Request) ProtoReflect() protoreflect.Message {
	mi := &file_ComposePostService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComposePostService_ComposePost_Request.ProtoReflect.Descriptor instead.
func (*ComposePostService_ComposePost_Request) Descriptor() ([]byte, []int) {
	return file_ComposePostService_proto_rawDescGZIP(), []int{0}
}

func (x *ComposePostService_ComposePost_Request) GetReqID() int64 {
	if x != nil {
		return x.ReqID
	}
	return 0
}

func (x *ComposePostService_ComposePost_Request) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ComposePostService_ComposePost_Request) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *ComposePostService_ComposePost_Request) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ComposePostService_ComposePost_Request) GetMediaIDs() []int64 {
	if x != nil {
		return x.MediaIDs
	}
	return nil
}

func (x *ComposePostService_ComposePost_Request) GetMediaTypes() []string {
	if x != nil {
		return x.MediaTypes
	}
	return nil
}

func (x *ComposePostService_ComposePost_Request) GetPostType() int64 {
	if x != nil {
		return x.PostType
	}
	return 0
}

type ComposePostService_ComposePost_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret0          int64                  `protobuf:"zigzag64,1,opt,name=ret0,proto3" json:"ret0,omitempty"`
	Ret1          []int64                `protobuf:"zigzag64,2,rep,packed,name=ret1,proto3" json:"ret1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComposePostService_ComposePost_Response) Reset() {
	*x = ComposePostService_ComposePost_Response{}
	mi := &file_ComposePostService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComposePostService_ComposePost_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComposePostService_ComposePost_Response) ProtoMessage() {}

func (x *ComposePostService_ComposePost_Response) ProtoReflect() protoreflect.Message {
	mi := &file_ComposePostService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComposePostService_ComposePost_Response.ProtoReflect.Descriptor instead.
func (*ComposePostService_ComposePost_Response) Descriptor() ([]byte, []int) {
	return file_ComposePostService_proto_rawDescGZIP(), []int{1}
}

func (x *ComposePostService_ComposePost_Response) GetRet0() int64 {
	if x != nil {
		return x.Ret0
	}
	return 0
}

func (x *ComposePostService_ComposePost_Response) GetRet1() []int64 {
	if x != nil {
		return x.Ret1
	}
	return nil
}

var File_ComposePostService_proto protoreflect.FileDescriptor

const file_ComposePostService_proto_rawDesc = "" +
	"\n" +
	"\x18ComposePostService.proto\x12\x04grpc\"\xde\x01\n" +
	"&ComposePostService_ComposePost_Request\x12\x14\n" +
	"\x05reqID\x18\x01 \x01(\x12R\x05reqID\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x16\n" +
	"\x06userID\x18\x03 \x01(\x12R\x06userID\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x1a\n" +
	"\bmediaIDs\x18\x05 \x03(\x12R\bmediaIDs\x12\x1e\n" +
	"\n" +
	"mediaTypes\x18\x06 \x03(\tR\n" +
	"mediaTypes\x12\x1a\n" +
	"\bpostType\x18\a \x01(\x12R\bpostType\"Q\n" +
	"'ComposePostService_ComposePost_Response\x12\x12\n" +
	"\x04ret0\x18\x01 \x01(\x12R\x04ret0\x12\x12\n" +
	"\x04ret1\x18\x02 \x03(\x12R\x04ret12\x82\x01\n" +
	"\x12ComposePostService\x12l\n" +
	"\vComposePost\x12,.grpc.ComposePostService_ComposePost_Request\x1a-.grpc.ComposePostService_ComposePost_Response\"\x00B\tZ\a./;grpcb\x06proto3"

var (
	file_ComposePostService_proto_rawDescOnce sync.Once
	file_ComposePostService_proto_rawDescData []byte
)

func file_ComposePostService_proto_rawDescGZIP() []byte {
	file_ComposePostService_proto_rawDescOnce.Do(func() {
		file_ComposePostService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ComposePostService_proto_rawDesc), len(file_ComposePostService_proto_rawDesc)))
	})
	return file_ComposePostService_proto_rawDescData
}

var file_ComposePostService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ComposePostService_proto_goTypes = []any{
	(*ComposePostService_ComposePost_Request)(nil),  // 0: grpc.ComposePostService_ComposePost_Request
	(*ComposePostService_ComposePost_Response)(nil), // 1: grpc.ComposePostService_ComposePost_Response
}
var file_ComposePostService_proto_depIdxs = []int32{
	0, // 0: grpc.ComposePostService.ComposePost:input_type -> grpc.ComposePostService_ComposePost_Request
	1, // 1: grpc.ComposePostService.ComposePost:output_type -> grpc.ComposePostService_ComposePost_Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ComposePostService_proto_init() }
func file_ComposePostService_proto_init() {
	if File_ComposePostService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ComposePostService_proto_rawDesc), len(file_ComposePostService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ComposePostService_proto_goTypes,
		DependencyIndexes: file_ComposePostService_proto_depIdxs,
		MessageInfos:      file_ComposePostService_proto_msgTypes,
	}.Build()
	File_ComposePostService_proto = out.File
	file_ComposePostService_proto_goTypes = nil
	file_ComposePostService_proto_depIdxs = nil
}
