// Package main is auto-generated by gogen/namespacebuilder.go
//
// It provides funcs for instantiating the userid_service_sb_proc namespace.
//
// To instantiate the userid_service_sb_proc namespace, first call [New_userid_service_sb_proc] and then either call 
// [Build] or [BuildWithParent].
// 
// See [golang.NamespaceBuilder] docs for more information about the behavior of [Build]
package main

import (
	"github.com/blueprint-uservices/blueprint/runtime/plugins/mongodb"
	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"github.com/blueprint-uservices/blueprint/examples/dsb_sn/workflow/socialnetwork"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/otelcol"
	"blueprint/goproc/userid_service_sb_proc/ot"
	"blueprint/goproc/userid_service_sb_proc/grpc"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/golang"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/opentelemetry"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/slogger"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/redis"
)

// Initializes the userid_service_sb_proc namespace by defining all of the nodes that run
// within the namespace.
//
// [Build] or [BuildWithParent] must be called on the return value of this func
// to actually build and run the nodes in the namespace.
func New_userid_service_sb_proc(name string) *golang.NamespaceBuilder {
	b := golang.NewNamespaceBuilder(name)
	set_userid_service_sb_proc_Args(b)
	set_userid_service_sb_proc_Instances(b)
	set_userid_service_sb_proc_Definitions(b)
	return b
}

// userid_service_sb_proc requires that its arguments are either:
//  - explicitly set with [golang.NamespaceBuilder.Set]
//  - passed on the command line (if built using [golang.NamespaceBuilder.Build])
//  - are defined in parent (if built using [golang.NamespaceBuilder.BuildWithParent])
//
// The following arguments will be eagerly checked and building the namespace
// will fail if they haven't been provided:
//   otelcol_sb.dial_addr
//   user_cache_sb.dial_addr
//   user_db_sb.dial_addr
//   userid_service_sb.grpc.bind_addr
//
// The following arguments are optional and a failure will only occur if the client
// tries to build a node that needs the argument to be set
func set_userid_service_sb_proc_Args(b *golang.NamespaceBuilder) {
	b.Required("otelcol_sb.dial_addr", "Argument generated by Blueprint IR: otelcol_sb.dial_addr = AddressConfig()")
	b.Required("user_cache_sb.dial_addr", "Argument generated by Blueprint IR: user_cache_sb.dial_addr = AddressConfig()")
	b.Required("user_db_sb.dial_addr", "Argument generated by Blueprint IR: user_db_sb.dial_addr = AddressConfig()")
	b.Required("userid_service_sb.grpc.bind_addr", "Argument generated by Blueprint IR: userid_service_sb.grpc.bind_addr = AddressConfig()")
}

// When the userid_service_sb_proc namespace is built it will automatically instantiate
// the following nodes:
//   userid_service_sb_proc.stdoutmetriccollector
//   userid_service_sb_proc.logger
//   user_cache_sb.client
//   user_db_sb.client
//   userid_service_sb
//   otelcol_sb.client
//   userid_service_sb.server.ot
//   userid_service_sb.grpc_server
func set_userid_service_sb_proc_Instances(b *golang.NamespaceBuilder) {
	b.Instantiate("userid_service_sb_proc.stdoutmetriccollector")
	b.Instantiate("userid_service_sb_proc.logger")
	b.Instantiate("user_cache_sb.client")
	b.Instantiate("user_db_sb.client")
	b.Instantiate("userid_service_sb")
	b.Instantiate("otelcol_sb.client")
	b.Instantiate("userid_service_sb.server.ot")
	b.Instantiate("userid_service_sb.grpc_server")
}

// The userid_service_sb_proc namespace contains definitions for instantiating
// the following nodes:
//   otelcol_sb.client
//   user_cache_sb.client
//   user_db_sb.client
//   userid_service_sb
//   userid_service_sb.grpc_server
//   userid_service_sb.server.ot
//   userid_service_sb_proc.logger
//   userid_service_sb_proc.stdoutmetriccollector
func set_userid_service_sb_proc_Definitions(b *golang.NamespaceBuilder) {
	b.Define("otelcol_sb.client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var addr string
		if err := n.Get("otelcol_sb.dial_addr", &addr); err != nil {
			return nil, err
		}
		
		return otelcol.NewOTCollectorTracer(n.Context(), addr, "8080")
	})
	
	b.Define("user_cache_sb.client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var addr string
		if err := n.Get("user_cache_sb.dial_addr", &addr); err != nil {
			return nil, err
		}
		
		return redis.NewRedisCacheClient(n.Context(), addr)
	})
	
	b.Define("user_db_sb.client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var addr string
		if err := n.Get("user_db_sb.dial_addr", &addr); err != nil {
			return nil, err
		}
		
		return mongodb.NewMongoDB(n.Context(), addr)
	})
	
	b.Define("userid_service_sb", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var userCache backend.Cache
		if err := n.Get("user_cache_sb.client", &userCache); err != nil {
			return nil, err
		}
		
		var userDB backend.NoSQLDatabase
		if err := n.Get("user_db_sb.client", &userDB); err != nil {
			return nil, err
		}
		
		return socialnetwork.NewUserIDServiceImpl(n.Context(), userCache, userDB)
	})
	
	b.Define("userid_service_sb.grpc_server", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var service ot.UserIDService_OTServerWrapperInterface
		if err := n.Get("userid_service_sb.server.ot", &service); err != nil {
			return nil, err
		}
		
		var serverAddr string
		if err := n.Get("userid_service_sb.grpc.bind_addr", &serverAddr); err != nil {
			return nil, err
		}
		
		return grpc.New_UserIDService_GRPCServerHandler(n.Context(), service, serverAddr)
	})
	
	b.Define("userid_service_sb.server.ot", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var service socialnetwork.UserIDService
		if err := n.Get("userid_service_sb", &service); err != nil {
			return nil, err
		}
		
		var otCollectorClient backend.Tracer
		if err := n.Get("otelcol_sb.client", &otCollectorClient); err != nil {
			return nil, err
		}
		
		return ot.New_UserIDService_OTServerWrapper(n.Context(), service, otCollectorClient)
	})
	
	b.Define("userid_service_sb_proc.logger", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		return slogger.NewSLogger(n.Context())
	})
	
	b.Define("userid_service_sb_proc.stdoutmetriccollector", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		return opentelemetry.NewStdoutMetricCollector(n.Context())
	})
	
}
