// text_service_sb3_proc runs the text_service_sb3_proc Golang process.
//
// text_service_sb3_proc is auto-generated by Blueprint's goproc plugin (goproc/goprocgen/main.go.go)
//
// Usage:
//
//   go run main.go --urlshorten_service_sb3.grpc.dial_addr=value --otelcol_sb3.dial_addr=value --usermention_service_sb3.grpc.dial_addr=value --text_service_sb3.grpc.bind_addr=value 
//
// text_service_sb3_proc requires the following arguments are passed:
//
//   --urlshorten_service_sb3.grpc.dial_addr
//       Auto-generated by Blueprint IR node:
//       urlshorten_service_sb3.grpc.dial_addr = AddressConfig()
//
//   --otelcol_sb3.dial_addr
//       Auto-generated by Blueprint IR node:
//       otelcol_sb3.dial_addr = AddressConfig()
//
//   --usermention_service_sb3.grpc.dial_addr
//       Auto-generated by Blueprint IR node:
//       usermention_service_sb3.grpc.dial_addr = AddressConfig()
//
//   --text_service_sb3.grpc.bind_addr
//       Auto-generated by Blueprint IR node:
//       text_service_sb3.grpc.bind_addr = AddressConfig()
//
// text_service_sb3_proc will instantiate the following IR nodes:
//   text_service_sb3_proc.stdoutmetriccollector
//   text_service_sb3_proc.logger
//   urlshorten_service_sb3.grpc_client
//   otelcol_sb3.client
//   urlshorten_service_sb3.client.ot
//   urlshorten_service_sb3.client.retrier
//   urlshorten_service_sb3.client
//   usermention_service_sb3.grpc_client
//   usermention_service_sb3.client.ot
//   usermention_service_sb3.client.retrier
//   usermention_service_sb3.client
//   text_service_sb3
//   text_service_sb3.server.ot
//   text_service_sb3.grpc_server
package main

import (
	"context"
	"os"

	"log/slog"
)

func main() {
	slog.Info("Running text_service_sb3_proc")
	n, err := New_text_service_sb3_proc("text_service_sb3_proc").Build(context.Background())
	if err != nil {
		slog.Error(err.Error())
		os.Exit(1)
	}
	n.Await()
	slog.Info("text_service_sb3_proc exiting")
}