apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_nt_es/k8s
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: hometimeline-service-nt-es-ctr
  name: hometimeline-service-nt-es-ctr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hometimeline-service-nt-es-ctr
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_nt_es/k8s
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: hometimeline-service-nt-es-ctr
    spec:
      containers:
      - env:
        - name: GC_INTERVAL_SEC
          value: '0'
        - name: GOGC
          value: '100'
        - name: HOMETIMELINE_CACHE_NT_ES_DIAL_ADDR
          value: hometimeline-cache-nt-es-ctr:6379
        - name: HOMETIMELINE_SERVICE_NT_ES_GRPC_BIND_ADDR
          value: 0.0.0.0:12345
        - name: POST_STORAGE_SERVICE_NT_ES_GRPC_DIAL_ADDR
          value: post-storage-service-nt-es-ctr:12345
        - name: SOCIALGRAPH_SERVICE_NT_ES_GRPC_DIAL_ADDR
          value: socialgraph-service-nt-es-ctr:12345
        image: 10.10.1.1:30000/hometimeline-service-nt-es-ctr:latest
        name: hometimeline-service-nt-es-ctr
        ports:
        - containerPort: 12345
          protocol: TCP
      hostname: hometimeline-service-nt-es-ctr
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: node-2
