apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_nt/k8s
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: usertimeline-service-nt-ctr
  name: usertimeline-service-nt-ctr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: usertimeline-service-nt-ctr
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_nt/k8s
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: usertimeline-service-nt-ctr
    spec:
      containers:
      - env:
        - name: POST_STORAGE_SERVICE_NT_GRPC_DIAL_ADDR
          value: post-storage-service-nt-ctr:12345
        - name: USERTIMELINE_CACHE_NT_DIAL_ADDR
          value: usertimeline-cache-nt-ctr:6379
        - name: USERTIMELINE_DB_NT_DIAL_ADDR
          value: usertimeline-db-nt-ctr:27017
        - name: USERTIMELINE_SERVICE_NT_GRPC_BIND_ADDR
          value: 0.0.0.0:12345
        image: 10.10.1.1:30000/usertimeline-service-nt-ctr:latest
        name: usertimeline-service-nt-ctr
        ports:
        - containerPort: 12345
          protocol: TCP
        resources:
          requests:
            cpu: 8000m
      hostname: usertimeline-service-nt-ctr
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: node-4
