// Package main is auto-generated by gogen/namespacebuilder.go
//
// It provides funcs for instantiating the user_service_v_proc namespace.
//
// To instantiate the user_service_v_proc namespace, first call [New_user_service_v_proc] and then either call 
// [Build] or [BuildWithParent].
// 
// See [golang.NamespaceBuilder] docs for more information about the behavior of [Build]
package main

import (
	"blueprint/goproc/user_service_v_proc/ot"
	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/slogger"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/redis"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/mongodb"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/otelcol"
	"blueprint/goproc/user_service_v_proc/retries"
	"github.com/blueprint-uservices/blueprint/examples/dsb_sn/workflow/socialnetwork"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/golang"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/opentelemetry"
	"blueprint/goproc/user_service_v_proc/grpc"
)

// Initializes the user_service_v_proc namespace by defining all of the nodes that run
// within the namespace.
//
// [Build] or [BuildWithParent] must be called on the return value of this func
// to actually build and run the nodes in the namespace.
func New_user_service_v_proc(name string) *golang.NamespaceBuilder {
	b := golang.NewNamespaceBuilder(name)
	set_user_service_v_proc_Args(b)
	set_user_service_v_proc_Instances(b)
	set_user_service_v_proc_Definitions(b)
	return b
}

// user_service_v_proc requires that its arguments are either:
//  - explicitly set with [golang.NamespaceBuilder.Set]
//  - passed on the command line (if built using [golang.NamespaceBuilder.Build])
//  - are defined in parent (if built using [golang.NamespaceBuilder.BuildWithParent])
//
// The following arguments will be eagerly checked and building the namespace
// will fail if they haven't been provided:
//   otelcol_v.dial_addr
//   socialgraph_service_v.grpc.dial_addr
//   user_cache_v.dial_addr
//   user_db_v.dial_addr
//   user_service_v.grpc.bind_addr
//
// The following arguments are optional and a failure will only occur if the client
// tries to build a node that needs the argument to be set
func set_user_service_v_proc_Args(b *golang.NamespaceBuilder) {
	b.Required("otelcol_v.dial_addr", "Argument generated by Blueprint IR: otelcol_v.dial_addr = AddressConfig()")
	b.Required("socialgraph_service_v.grpc.dial_addr", "Argument generated by Blueprint IR: socialgraph_service_v.grpc.dial_addr = AddressConfig()")
	b.Required("user_cache_v.dial_addr", "Argument generated by Blueprint IR: user_cache_v.dial_addr = AddressConfig()")
	b.Required("user_db_v.dial_addr", "Argument generated by Blueprint IR: user_db_v.dial_addr = AddressConfig()")
	b.Required("user_service_v.grpc.bind_addr", "Argument generated by Blueprint IR: user_service_v.grpc.bind_addr = AddressConfig()")
}

// When the user_service_v_proc namespace is built it will automatically instantiate
// the following nodes:
//   user_service_v_proc.stdoutmetriccollector
//   user_service_v_proc.logger
//   user_cache_v.client
//   user_db_v.client
//   socialgraph_service_v.grpc_client
//   otelcol_v.client
//   socialgraph_service_v.client.ot
//   socialgraph_service_v.client.retrier
//   socialgraph_service_v.client
//   user_service_v
//   user_service_v.server.ot
//   user_service_v.grpc_server
func set_user_service_v_proc_Instances(b *golang.NamespaceBuilder) {
	b.Instantiate("user_service_v_proc.stdoutmetriccollector")
	b.Instantiate("user_service_v_proc.logger")
	b.Instantiate("user_cache_v.client")
	b.Instantiate("user_db_v.client")
	b.Instantiate("socialgraph_service_v.grpc_client")
	b.Instantiate("otelcol_v.client")
	b.Instantiate("socialgraph_service_v.client.ot")
	b.Instantiate("socialgraph_service_v.client.retrier")
	b.Instantiate("socialgraph_service_v.client")
	b.Instantiate("user_service_v")
	b.Instantiate("user_service_v.server.ot")
	b.Instantiate("user_service_v.grpc_server")
}

// The user_service_v_proc namespace contains definitions for instantiating
// the following nodes:
//   otelcol_v.client
//   socialgraph_service_v.client
//   socialgraph_service_v.client.ot
//   socialgraph_service_v.client.retrier
//   socialgraph_service_v.grpc_client
//   user_cache_v.client
//   user_db_v.client
//   user_service_v
//   user_service_v.grpc_server
//   user_service_v.server.ot
//   user_service_v_proc.logger
//   user_service_v_proc.stdoutmetriccollector
func set_user_service_v_proc_Definitions(b *golang.NamespaceBuilder) {
	b.Define("otelcol_v.client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var addr string
		if err := n.Get("otelcol_v.dial_addr", &addr); err != nil {
			return nil, err
		}
		
		return otelcol.NewOTCollectorTracer(n.Context(), addr, "8080")
	})
	
	b.Define("socialgraph_service_v.client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin workflow/ir_workflowservice.go
		var client socialnetwork.SocialGraphService
		err := n.Get("socialgraph_service_v.client.retrier", &client)
		return client, err
	})
	
	b.Define("socialgraph_service_v.client.ot", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var client ot.SocialGraphService_OTServerWrapperInterface
		if err := n.Get("socialgraph_service_v.grpc_client", &client); err != nil {
			return nil, err
		}
		
		var coll_client backend.Tracer
		if err := n.Get("otelcol_v.client", &coll_client); err != nil {
			return nil, err
		}
		
		return ot.New_SocialGraphService_OTClientWrapper(n.Context(), client, coll_client)
	})
	
	b.Define("socialgraph_service_v.client.retrier", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var client ot.SocialGraphService_OTClientWrapperInterface
		if err := n.Get("socialgraph_service_v.client.ot", &client); err != nil {
			return nil, err
		}
		
		return retries.New_SocialGraphService_RetrierClient(n.Context(), client)
	})
	
	b.Define("socialgraph_service_v.grpc_client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var addr string
		if err := n.Get("socialgraph_service_v.grpc.dial_addr", &addr); err != nil {
			return nil, err
		}
		
		return grpc.New_SocialGraphService_GRPCClient(n.Context(), addr)
	})
	
	b.Define("user_cache_v.client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var addr string
		if err := n.Get("user_cache_v.dial_addr", &addr); err != nil {
			return nil, err
		}
		
		return redis.NewRedisCacheClient(n.Context(), addr)
	})
	
	b.Define("user_db_v.client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var addr string
		if err := n.Get("user_db_v.dial_addr", &addr); err != nil {
			return nil, err
		}
		
		return mongodb.NewMongoDB(n.Context(), addr)
	})
	
	b.Define("user_service_v", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var userCache backend.Cache
		if err := n.Get("user_cache_v.client", &userCache); err != nil {
			return nil, err
		}
		
		var userDB backend.NoSQLDatabase
		if err := n.Get("user_db_v.client", &userDB); err != nil {
			return nil, err
		}
		
		var socialGraphService socialnetwork.SocialGraphService
		if err := n.Get("socialgraph_service_v.client", &socialGraphService); err != nil {
			return nil, err
		}
		
		return socialnetwork.NewUserServiceImpl(n.Context(), userCache, userDB, socialGraphService, "secret")
	})
	
	b.Define("user_service_v.grpc_server", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var service ot.UserService_OTServerWrapperInterface
		if err := n.Get("user_service_v.server.ot", &service); err != nil {
			return nil, err
		}
		
		var serverAddr string
		if err := n.Get("user_service_v.grpc.bind_addr", &serverAddr); err != nil {
			return nil, err
		}
		
		return grpc.New_UserService_GRPCServerHandler(n.Context(), service, serverAddr)
	})
	
	b.Define("user_service_v.server.ot", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var service socialnetwork.UserService
		if err := n.Get("user_service_v", &service); err != nil {
			return nil, err
		}
		
		var otCollectorClient backend.Tracer
		if err := n.Get("otelcol_v.client", &otCollectorClient); err != nil {
			return nil, err
		}
		
		return ot.New_UserService_OTServerWrapper(n.Context(), service, otCollectorClient)
	})
	
	b.Define("user_service_v_proc.logger", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		return slogger.NewSLogger(n.Context())
	})
	
	b.Define("user_service_v_proc.stdoutmetriccollector", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		return opentelemetry.NewStdoutMetricCollector(n.Context())
	})
	
}
