// urlshorten_service_v6_proc runs the urlshorten_service_v6_proc Golang process.
//
// urlshorten_service_v6_proc is auto-generated by Blueprint's goproc plugin (goproc/goprocgen/main.go.go)
//
// Usage:
//
//   go run main.go --urlshorten_db_v6.dial_addr=value --otelcol_v6.dial_addr=value --urlshorten_service_v6.grpc.bind_addr=value 
//
// urlshorten_service_v6_proc requires the following arguments are passed:
//
//   --urlshorten_db_v6.dial_addr
//       Auto-generated by Blueprint IR node:
//       urlshorten_db_v6.dial_addr = AddressConfig()
//
//   --otelcol_v6.dial_addr
//       Auto-generated by Blueprint IR node:
//       otelcol_v6.dial_addr = AddressConfig()
//
//   --urlshorten_service_v6.grpc.bind_addr
//       Auto-generated by Blueprint IR node:
//       urlshorten_service_v6.grpc.bind_addr = AddressConfig()
//
// urlshorten_service_v6_proc will instantiate the following IR nodes:
//   urlshorten_service_v6_proc.stdoutmetriccollector
//   urlshorten_service_v6_proc.logger
//   urlshorten_db_v6.client
//   urlshorten_service_v6
//   otelcol_v6.client
//   urlshorten_service_v6.server.ot
//   urlshorten_service_v6.grpc_server
package main

import (
	"context"
	"os"

	"log/slog"
)

func main() {
	slog.Info("Running urlshorten_service_v6_proc")
	n, err := New_urlshorten_service_v6_proc("urlshorten_service_v6_proc").Build(context.Background())
	if err != nil {
		slog.Error(err.Error())
		os.Exit(1)
	}
	n.Await()
	slog.Info("urlshorten_service_v6_proc exiting")
}