// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: UserMentionService.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserMentionService_ComposeUserMentions_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReqID         int64                  `protobuf:"zigzag64,1,opt,name=reqID,proto3" json:"reqID,omitempty"`
	Usernames     []string               `protobuf:"bytes,2,rep,name=usernames,proto3" json:"usernames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMentionService_ComposeUserMentions_Request) Reset() {
	*x = UserMentionService_ComposeUserMentions_Request{}
	mi := &file_UserMentionService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMentionService_ComposeUserMentions_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMentionService_ComposeUserMentions_Request) ProtoMessage() {}

func (x *UserMentionService_ComposeUserMentions_Request) ProtoReflect() protoreflect.Message {
	mi := &file_UserMentionService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMentionService_ComposeUserMentions_Request.ProtoReflect.Descriptor instead.
func (*UserMentionService_ComposeUserMentions_Request) Descriptor() ([]byte, []int) {
	return file_UserMentionService_proto_rawDescGZIP(), []int{0}
}

func (x *UserMentionService_ComposeUserMentions_Request) GetReqID() int64 {
	if x != nil {
		return x.ReqID
	}
	return 0
}

func (x *UserMentionService_ComposeUserMentions_Request) GetUsernames() []string {
	if x != nil {
		return x.Usernames
	}
	return nil
}

type UserMentionService_ComposeUserMentions_Response struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Ret0          []*UserMentionService_UserMention `protobuf:"bytes,1,rep,name=ret0,proto3" json:"ret0,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMentionService_ComposeUserMentions_Response) Reset() {
	*x = UserMentionService_ComposeUserMentions_Response{}
	mi := &file_UserMentionService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMentionService_ComposeUserMentions_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMentionService_ComposeUserMentions_Response) ProtoMessage() {}

func (x *UserMentionService_ComposeUserMentions_Response) ProtoReflect() protoreflect.Message {
	mi := &file_UserMentionService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMentionService_ComposeUserMentions_Response.ProtoReflect.Descriptor instead.
func (*UserMentionService_ComposeUserMentions_Response) Descriptor() ([]byte, []int) {
	return file_UserMentionService_proto_rawDescGZIP(), []int{1}
}

func (x *UserMentionService_ComposeUserMentions_Response) GetRet0() []*UserMentionService_UserMention {
	if x != nil {
		return x.Ret0
	}
	return nil
}

type UserMentionService_UserMention struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"zigzag64,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMentionService_UserMention) Reset() {
	*x = UserMentionService_UserMention{}
	mi := &file_UserMentionService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMentionService_UserMention) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMentionService_UserMention) ProtoMessage() {}

func (x *UserMentionService_UserMention) ProtoReflect() protoreflect.Message {
	mi := &file_UserMentionService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMentionService_UserMention.ProtoReflect.Descriptor instead.
func (*UserMentionService_UserMention) Descriptor() ([]byte, []int) {
	return file_UserMentionService_proto_rawDescGZIP(), []int{2}
}

func (x *UserMentionService_UserMention) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *UserMentionService_UserMention) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

var File_UserMentionService_proto protoreflect.FileDescriptor

const file_UserMentionService_proto_rawDesc = "" +
	"\n" +
	"\x18UserMentionService.proto\x12\x04grpc\"d\n" +
	".UserMentionService_ComposeUserMentions_Request\x12\x14\n" +
	"\x05reqID\x18\x01 \x01(\x12R\x05reqID\x12\x1c\n" +
	"\tusernames\x18\x02 \x03(\tR\tusernames\"k\n" +
	"/UserMentionService_ComposeUserMentions_Response\x128\n" +
	"\x04ret0\x18\x01 \x03(\v2$.grpc.UserMentionService_UserMentionR\x04ret0\"T\n" +
	"\x1eUserMentionService_UserMention\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\x12R\x06UserID\x12\x1a\n" +
	"\bUsername\x18\x02 \x01(\tR\bUsername2\x9b\x01\n" +
	"\x12UserMentionService\x12\x84\x01\n" +
	"\x13ComposeUserMentions\x124.grpc.UserMentionService_ComposeUserMentions_Request\x1a5.grpc.UserMentionService_ComposeUserMentions_Response\"\x00B\tZ\a./;grpcb\x06proto3"

var (
	file_UserMentionService_proto_rawDescOnce sync.Once
	file_UserMentionService_proto_rawDescData []byte
)

func file_UserMentionService_proto_rawDescGZIP() []byte {
	file_UserMentionService_proto_rawDescOnce.Do(func() {
		file_UserMentionService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_UserMentionService_proto_rawDesc), len(file_UserMentionService_proto_rawDesc)))
	})
	return file_UserMentionService_proto_rawDescData
}

var file_UserMentionService_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_UserMentionService_proto_goTypes = []any{
	(*UserMentionService_ComposeUserMentions_Request)(nil),  // 0: grpc.UserMentionService_ComposeUserMentions_Request
	(*UserMentionService_ComposeUserMentions_Response)(nil), // 1: grpc.UserMentionService_ComposeUserMentions_Response
	(*UserMentionService_UserMention)(nil),                  // 2: grpc.UserMentionService_UserMention
}
var file_UserMentionService_proto_depIdxs = []int32{
	2, // 0: grpc.UserMentionService_ComposeUserMentions_Response.ret0:type_name -> grpc.UserMentionService_UserMention
	0, // 1: grpc.UserMentionService.ComposeUserMentions:input_type -> grpc.UserMentionService_ComposeUserMentions_Request
	1, // 2: grpc.UserMentionService.ComposeUserMentions:output_type -> grpc.UserMentionService_ComposeUserMentions_Response
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_UserMentionService_proto_init() }
func file_UserMentionService_proto_init() {
	if File_UserMentionService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_UserMentionService_proto_rawDesc), len(file_UserMentionService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_UserMentionService_proto_goTypes,
		DependencyIndexes: file_UserMentionService_proto_depIdxs,
		MessageInfos:      file_UserMentionService_proto_msgTypes,
	}.Build()
	File_UserMentionService_proto = out.File
	file_UserMentionService_proto_goTypes = nil
	file_UserMentionService_proto_depIdxs = nil
}
