// Blueprint: Auto-generated by OT plugin
package ot

import (
	"context"
	"github.com/blueprint-uservices/blueprint/examples/dsb_sn/workflow/snnw"
)

type UserService_OTServerWrapperInterface interface {
	ComposeCreatorWithUserId(ctx context.Context, reqID int64, userID int64, username string, traceCtx string) (snnw.Creator, error)
	ComposeCreatorWithUsername(ctx context.Context, reqID int64, username string, traceCtx string) (snnw.Creator, error)
	Login(ctx context.Context, reqID int64, username string, password string, traceCtx string) (string, error)
	RegisterUser(ctx context.Context, reqID int64, firstName string, lastName string, username string, password string, traceCtx string) (error)
	RegisterUserWithId(ctx context.Context, reqID int64, firstName string, lastName string, username string, password string, userID int64, traceCtx string) (error)
	
}
