package snnw

import (
	"context"

	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
)

// The UserService interface
type UserService interface {
	// Logs in a user using the user's `username` and `password`
	// Returns an error if the username is not registered or if the provided password doesn't match the stored password.
	Login(ctx context.Context, reqID int64, username string, password string) (string, error)
	// Registers a new user with a given `userID`.
	// Returns an error if the `userID` is already taken.
	RegisterUserWithId(ctx context.Context, reqID int64, firstName string, lastName string, username string, password string, userID int64) error
	// Registers a new user. A random `userID` is generated by the service.
	RegisterUser(ctx context.Context, reqID int64, firstName string, lastName string, username string, password string) error
	// Creates and returns a creator object to be included in a Post. The Creator object is created using the `userID`.
	ComposeCreatorWithUserId(ctx context.Context, reqID int64, userID int64, username string) (Creator, error)
	// Creates and returns a creator object to be included in a Post. The service looks up the userID of the user with the given `username`.
	// Returns an error if the user with the given `username` is not registered.
	ComposeCreatorWithUsername(ctx context.Context, reqID int64, username string) (Creator, error)
}

// Implementation of [UserService]
type UserServiceImpl struct {
	machine_id         string
	counter            int64
	current_timestamp  int64
	secret             string
	userCache          backend.Cache
	userDB             backend.NoSQLDatabase
	socialGraphService SocialGraphService
}

// The format of a Login object.
type LoginObj struct {
	UserID   int64
	Password string
	Salt     string
}

// Implementation of [UserService]
func NewUserServiceImpl(ctx context.Context, userCache backend.Cache, userDB backend.NoSQLDatabase, socialGraphService SocialGraphService, secret string) (UserService, error) {
	return &UserServiceImpl{counter: 0, current_timestamp: -1, machine_id: GetMachineID(), userCache: userCache, userDB: userDB, socialGraphService: socialGraphService, secret: secret}, nil
}

// Implements UserService interface
func (u *UserServiceImpl) Login(ctx context.Context, reqID int64, username string, password string) (string, error) {
	return "", nil
}

// Implements UserService interface
func (u *UserServiceImpl) ComposeCreatorWithUserId(ctx context.Context, reqID int64, userID int64, username string) (Creator, error) {
	return Creator{UserID: userID, Username: username}, nil
}

// Implements UserService interface
func (u *UserServiceImpl) ComposeCreatorWithUsername(ctx context.Context, reqID int64, username string) (Creator, error) {
	return Creator{Username: username}, nil
}

// Implements UserService interface
func (u *UserServiceImpl) RegisterUserWithId(ctx context.Context, reqID int64, firstName string, lastName string, username string, password string, userID int64) error {
	// Preserve downstream call to SocialGraphService (traced call graph).
	return u.socialGraphService.InsertUser(ctx, reqID, userID)
}

// Implements UserService interface
func (u *UserServiceImpl) RegisterUser(ctx context.Context, reqID int64, firstName string, lastName string, username string, password string) error {
	return u.RegisterUserWithId(ctx, reqID, firstName, lastName, username, password, 0)
}
