// Blueprint: Auto-generated by GRPC Plugin
package grpc

import (
	"google.golang.org/grpc"
	"blueprint/goproc/text_service_v_proc/ot"
	"context"
	"net"
)

type TextService_GRPCServerHandler struct {
	UnimplementedTextService_OTServerWrapperInterfaceServer
	Service ot.TextService_OTServerWrapperInterface
	Address string
}

func New_TextService_GRPCServerHandler(ctx context.Context, service ot.TextService_OTServerWrapperInterface, serverAddress string) (*TextService_GRPCServerHandler, error) {
	handler := &TextService_GRPCServerHandler{}
	handler.Service = service
	handler.Address = serverAddress
	return handler, nil
}

// Blueprint: Run is called automatically in a separate goroutine by runtime/plugins/golang/di.go
func (handler *TextService_GRPCServerHandler) Run(ctx context.Context) error {
	lis, err := net.Listen("tcp", handler.Address)
	if err != nil {
		return err
	}

	s := grpc.NewServer()
	RegisterTextService_OTServerWrapperInterfaceServer(s, handler)

	go func() {
		select {
		case <-ctx.Done():
			s.GracefulStop()
		}
	}()

	return s.Serve(lis)
}


func (handler *TextService_GRPCServerHandler) ComposeText(ctx context.Context, req *TextService_OTServerWrapperInterface_ComposeText_Request) (*TextService_OTServerWrapperInterface_ComposeText_Response, error) {
	reqID, text, traceCtx := req.unmarshall()
	ret0, ret1, ret2, err := handler.Service.ComposeText(ctx, reqID, text, traceCtx)
	if err != nil {
		return nil, err
	}

	rsp := &TextService_OTServerWrapperInterface_ComposeText_Response{}
	rsp.marshall(ret0, ret1, ret2)
	return rsp, nil
}

