// Package main is auto-generated by gogen/namespacebuilder.go
//
// It provides funcs for instantiating the hometimeline_service_pb_proc namespace.
//
// To instantiate the hometimeline_service_pb_proc namespace, first call [New_hometimeline_service_pb_proc] and then either call 
// [Build] or [BuildWithParent].
// 
// See [golang.NamespaceBuilder] docs for more information about the behavior of [Build]
package main

import (
	"github.com/blueprint-uservices/blueprint/examples/dsb_sn/workflow/socialnetwork"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/golang"
	"blueprint/goproc/hometimeline_service_pb_proc/grpc"
	"blueprint/goproc/hometimeline_service_pb_proc/ot"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/opentelemetry"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/slogger"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/redis"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/otelcol"
	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"blueprint/goproc/hometimeline_service_pb_proc/retries"
)

// Initializes the hometimeline_service_pb_proc namespace by defining all of the nodes that run
// within the namespace.
//
// [Build] or [BuildWithParent] must be called on the return value of this func
// to actually build and run the nodes in the namespace.
func New_hometimeline_service_pb_proc(name string) *golang.NamespaceBuilder {
	b := golang.NewNamespaceBuilder(name)
	set_hometimeline_service_pb_proc_Args(b)
	set_hometimeline_service_pb_proc_Instances(b)
	set_hometimeline_service_pb_proc_Definitions(b)
	return b
}

// hometimeline_service_pb_proc requires that its arguments are either:
//  - explicitly set with [golang.NamespaceBuilder.Set]
//  - passed on the command line (if built using [golang.NamespaceBuilder.Build])
//  - are defined in parent (if built using [golang.NamespaceBuilder.BuildWithParent])
//
// The following arguments will be eagerly checked and building the namespace
// will fail if they haven't been provided:
//   hometimeline_cache_pb.dial_addr
//   hometimeline_service_pb.grpc.bind_addr
//   otelcol_pb.dial_addr
//   post_storage_service_pb.grpc.dial_addr
//   socialgraph_service_pb.grpc.dial_addr
//
// The following arguments are optional and a failure will only occur if the client
// tries to build a node that needs the argument to be set
func set_hometimeline_service_pb_proc_Args(b *golang.NamespaceBuilder) {
	b.Required("hometimeline_cache_pb.dial_addr", "Argument generated by Blueprint IR: hometimeline_cache_pb.dial_addr = AddressConfig()")
	b.Required("hometimeline_service_pb.grpc.bind_addr", "Argument generated by Blueprint IR: hometimeline_service_pb.grpc.bind_addr = AddressConfig()")
	b.Required("otelcol_pb.dial_addr", "Argument generated by Blueprint IR: otelcol_pb.dial_addr = AddressConfig()")
	b.Required("post_storage_service_pb.grpc.dial_addr", "Argument generated by Blueprint IR: post_storage_service_pb.grpc.dial_addr = AddressConfig()")
	b.Required("socialgraph_service_pb.grpc.dial_addr", "Argument generated by Blueprint IR: socialgraph_service_pb.grpc.dial_addr = AddressConfig()")
}

// When the hometimeline_service_pb_proc namespace is built it will automatically instantiate
// the following nodes:
//   hometimeline_service_pb_proc.stdoutmetriccollector
//   hometimeline_service_pb_proc.logger
//   hometimeline_cache_pb.client
//   post_storage_service_pb.grpc_client
//   otelcol_pb.client
//   post_storage_service_pb.client.ot
//   post_storage_service_pb.client.retrier
//   post_storage_service_pb.client
//   socialgraph_service_pb.grpc_client
//   socialgraph_service_pb.client.ot
//   socialgraph_service_pb.client.retrier
//   socialgraph_service_pb.client
//   hometimeline_service_pb
//   hometimeline_service_pb.server.ot
//   hometimeline_service_pb.grpc_server
func set_hometimeline_service_pb_proc_Instances(b *golang.NamespaceBuilder) {
	b.Instantiate("hometimeline_service_pb_proc.stdoutmetriccollector")
	b.Instantiate("hometimeline_service_pb_proc.logger")
	b.Instantiate("hometimeline_cache_pb.client")
	b.Instantiate("post_storage_service_pb.grpc_client")
	b.Instantiate("otelcol_pb.client")
	b.Instantiate("post_storage_service_pb.client.ot")
	b.Instantiate("post_storage_service_pb.client.retrier")
	b.Instantiate("post_storage_service_pb.client")
	b.Instantiate("socialgraph_service_pb.grpc_client")
	b.Instantiate("socialgraph_service_pb.client.ot")
	b.Instantiate("socialgraph_service_pb.client.retrier")
	b.Instantiate("socialgraph_service_pb.client")
	b.Instantiate("hometimeline_service_pb")
	b.Instantiate("hometimeline_service_pb.server.ot")
	b.Instantiate("hometimeline_service_pb.grpc_server")
}

// The hometimeline_service_pb_proc namespace contains definitions for instantiating
// the following nodes:
//   hometimeline_cache_pb.client
//   hometimeline_service_pb
//   hometimeline_service_pb.grpc_server
//   hometimeline_service_pb.server.ot
//   hometimeline_service_pb_proc.logger
//   hometimeline_service_pb_proc.stdoutmetriccollector
//   otelcol_pb.client
//   post_storage_service_pb.client
//   post_storage_service_pb.client.ot
//   post_storage_service_pb.client.retrier
//   post_storage_service_pb.grpc_client
//   socialgraph_service_pb.client
//   socialgraph_service_pb.client.ot
//   socialgraph_service_pb.client.retrier
//   socialgraph_service_pb.grpc_client
func set_hometimeline_service_pb_proc_Definitions(b *golang.NamespaceBuilder) {
	b.Define("hometimeline_cache_pb.client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var addr string
		if err := n.Get("hometimeline_cache_pb.dial_addr", &addr); err != nil {
			return nil, err
		}
		
		return redis.NewRedisCacheClient(n.Context(), addr)
	})
	
	b.Define("hometimeline_service_pb", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var homeTimelineCache backend.Cache
		if err := n.Get("hometimeline_cache_pb.client", &homeTimelineCache); err != nil {
			return nil, err
		}
		
		var postStorageService socialnetwork.PostStorageService
		if err := n.Get("post_storage_service_pb.client", &postStorageService); err != nil {
			return nil, err
		}
		
		var socialGraphService socialnetwork.SocialGraphService
		if err := n.Get("socialgraph_service_pb.client", &socialGraphService); err != nil {
			return nil, err
		}
		
		return socialnetwork.NewHomeTimelineServiceImpl(n.Context(), homeTimelineCache, postStorageService, socialGraphService)
	})
	
	b.Define("hometimeline_service_pb.grpc_server", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var service ot.HomeTimelineService_OTServerWrapperInterface
		if err := n.Get("hometimeline_service_pb.server.ot", &service); err != nil {
			return nil, err
		}
		
		var serverAddr string
		if err := n.Get("hometimeline_service_pb.grpc.bind_addr", &serverAddr); err != nil {
			return nil, err
		}
		
		return grpc.New_HomeTimelineService_GRPCServerHandler(n.Context(), service, serverAddr)
	})
	
	b.Define("hometimeline_service_pb.server.ot", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var service socialnetwork.HomeTimelineService
		if err := n.Get("hometimeline_service_pb", &service); err != nil {
			return nil, err
		}
		
		var otCollectorClient backend.Tracer
		if err := n.Get("otelcol_pb.client", &otCollectorClient); err != nil {
			return nil, err
		}
		
		return ot.New_HomeTimelineService_OTServerWrapper(n.Context(), service, otCollectorClient)
	})
	
	b.Define("hometimeline_service_pb_proc.logger", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		return slogger.NewSLogger(n.Context())
	})
	
	b.Define("hometimeline_service_pb_proc.stdoutmetriccollector", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		return opentelemetry.NewStdoutMetricCollector(n.Context())
	})
	
	b.Define("otelcol_pb.client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var addr string
		if err := n.Get("otelcol_pb.dial_addr", &addr); err != nil {
			return nil, err
		}
		
		return otelcol.NewOTCollectorTracer(n.Context(), addr, "8080")
	})
	
	b.Define("post_storage_service_pb.client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin workflow/ir_workflowservice.go
		var client socialnetwork.PostStorageService
		err := n.Get("post_storage_service_pb.client.retrier", &client)
		return client, err
	})
	
	b.Define("post_storage_service_pb.client.ot", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var client ot.PostStorageService_OTServerWrapperInterface
		if err := n.Get("post_storage_service_pb.grpc_client", &client); err != nil {
			return nil, err
		}
		
		var coll_client backend.Tracer
		if err := n.Get("otelcol_pb.client", &coll_client); err != nil {
			return nil, err
		}
		
		return ot.New_PostStorageService_OTClientWrapper(n.Context(), client, coll_client)
	})
	
	b.Define("post_storage_service_pb.client.retrier", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var client ot.PostStorageService_OTClientWrapperInterface
		if err := n.Get("post_storage_service_pb.client.ot", &client); err != nil {
			return nil, err
		}
		
		return retries.New_PostStorageService_RetrierClient(n.Context(), client)
	})
	
	b.Define("post_storage_service_pb.grpc_client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var addr string
		if err := n.Get("post_storage_service_pb.grpc.dial_addr", &addr); err != nil {
			return nil, err
		}
		
		return grpc.New_PostStorageService_GRPCClient(n.Context(), addr)
	})
	
	b.Define("socialgraph_service_pb.client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin workflow/ir_workflowservice.go
		var client socialnetwork.SocialGraphService
		err := n.Get("socialgraph_service_pb.client.retrier", &client)
		return client, err
	})
	
	b.Define("socialgraph_service_pb.client.ot", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var client ot.SocialGraphService_OTServerWrapperInterface
		if err := n.Get("socialgraph_service_pb.grpc_client", &client); err != nil {
			return nil, err
		}
		
		var coll_client backend.Tracer
		if err := n.Get("otelcol_pb.client", &coll_client); err != nil {
			return nil, err
		}
		
		return ot.New_SocialGraphService_OTClientWrapper(n.Context(), client, coll_client)
	})
	
	b.Define("socialgraph_service_pb.client.retrier", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var client ot.SocialGraphService_OTClientWrapperInterface
		if err := n.Get("socialgraph_service_pb.client.ot", &client); err != nil {
			return nil, err
		}
		
		return retries.New_SocialGraphService_RetrierClient(n.Context(), client)
	})
	
	b.Define("socialgraph_service_pb.grpc_client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var addr string
		if err := n.Get("socialgraph_service_pb.grpc.dial_addr", &addr); err != nil {
			return nil, err
		}
		
		return grpc.New_SocialGraphService_GRPCClient(n.Context(), addr)
	})
	
}
