apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_sb2/k8s
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: usertimeline-service-sb2-ctr
  name: usertimeline-service-sb2-ctr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: usertimeline-service-sb2-ctr
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_sb2/k8s
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: usertimeline-service-sb2-ctr
    spec:
      containers:
      - env:
        - name: OTELCOL_SB2_DIAL_ADDR
          value: otelcol-sb2-ctr:4317
        - name: POST_STORAGE_SERVICE_SB2_GRPC_DIAL_ADDR
          value: post-storage-service-sb2-ctr:12345
        - name: USERTIMELINE_CACHE_SB2_DIAL_ADDR
          value: usertimeline-cache-sb2-ctr:6379
        - name: USERTIMELINE_DB_SB2_DIAL_ADDR
          value: usertimeline-db-sb2-ctr:27017
        - name: USERTIMELINE_SERVICE_SB2_GRPC_BIND_ADDR
          value: 0.0.0.0:12345
        image: 10.10.1.1:30000/usertimeline-service-sb2-ctr:latest
        name: usertimeline-service-sb2-ctr
        ports:
        - containerPort: 12345
          protocol: TCP
        resources:
          requests:
            cpu: 15000m
      hostname: usertimeline-service-sb2-ctr
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: node-4
