apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_nt5/k8s
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: post-cache-nt5-ctr
  name: post-cache-nt5-ctr
spec:
  ports:
  - name: '12350'
    port: 12350
    targetPort: 6379
  - name: '6379'
    port: 6379
    targetPort: 6379
  selector:
    io.kompose.service: post-cache-nt5-ctr
