apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_nt5/k8s
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: wrk2api-service-nt5-ctr
  name: wrk2api-service-nt5-ctr
spec:
  ports:
  - name: '12368'
    port: 12368
    targetPort: 2000
  - name: '2000'
    port: 2000
    targetPort: 2000
  selector:
    io.kompose.service: wrk2api-service-nt5-ctr
