// Blueprint: Auto-generated by GRPC Plugin marshallgen.go
package grpc

import (
)

// Client-side function to pack SocialGraphService_OTServerWrapperInterface.Follow args into a GRPC SocialGraphService_OTServerWrapperInterface_Follow_Request struct
func (msg *SocialGraphService_OTServerWrapperInterface_Follow_Request) marshall(reqID int64, userID int64, followeeID int64, traceCtx string) *SocialGraphService_OTServerWrapperInterface_Follow_Request {
	msg.ReqID = int64(reqID)
	msg.UserID = int64(userID)
	msg.FolloweeID = int64(followeeID)
	msg.TraceCtx = string(traceCtx)
	return msg
}

// Server-side function to unpack SocialGraphService_OTServerWrapperInterface.Follow args from a GRPC SocialGraphService_OTServerWrapperInterface_Follow_Request struct
func (msg *SocialGraphService_OTServerWrapperInterface_Follow_Request) unmarshall() (reqID int64, userID int64, followeeID int64, traceCtx string) {
	reqID = int64(msg.ReqID)
	userID = int64(msg.UserID)
	followeeID = int64(msg.FolloweeID)
	traceCtx = string(msg.TraceCtx)
	return
}

// Server-side function to pack SocialGraphService_OTServerWrapperInterface.Follow retvals into a GRPC SocialGraphService_OTServerWrapperInterface_Follow_Response struct
func (msg *SocialGraphService_OTServerWrapperInterface_Follow_Response) marshall() *SocialGraphService_OTServerWrapperInterface_Follow_Response {
	return msg
}

// Client-side function to unpack SocialGraphService_OTServerWrapperInterface.Follow retvals from a GRPC SocialGraphService_OTServerWrapperInterface_Follow_Response struct
func (msg *SocialGraphService_OTServerWrapperInterface_Follow_Response) unmarshall() () {
	return
}

// Client-side function to pack SocialGraphService_OTServerWrapperInterface.FollowWithUsername args into a GRPC SocialGraphService_OTServerWrapperInterface_FollowWithUsername_Request struct
func (msg *SocialGraphService_OTServerWrapperInterface_FollowWithUsername_Request) marshall(reqID int64, userUsername string, followeeUsername string, traceCtx string) *SocialGraphService_OTServerWrapperInterface_FollowWithUsername_Request {
	msg.ReqID = int64(reqID)
	msg.UserUsername = string(userUsername)
	msg.FolloweeUsername = string(followeeUsername)
	msg.TraceCtx = string(traceCtx)
	return msg
}

// Server-side function to unpack SocialGraphService_OTServerWrapperInterface.FollowWithUsername args from a GRPC SocialGraphService_OTServerWrapperInterface_FollowWithUsername_Request struct
func (msg *SocialGraphService_OTServerWrapperInterface_FollowWithUsername_Request) unmarshall() (reqID int64, userUsername string, followeeUsername string, traceCtx string) {
	reqID = int64(msg.ReqID)
	userUsername = string(msg.UserUsername)
	followeeUsername = string(msg.FolloweeUsername)
	traceCtx = string(msg.TraceCtx)
	return
}

// Server-side function to pack SocialGraphService_OTServerWrapperInterface.FollowWithUsername retvals into a GRPC SocialGraphService_OTServerWrapperInterface_FollowWithUsername_Response struct
func (msg *SocialGraphService_OTServerWrapperInterface_FollowWithUsername_Response) marshall() *SocialGraphService_OTServerWrapperInterface_FollowWithUsername_Response {
	return msg
}

// Client-side function to unpack SocialGraphService_OTServerWrapperInterface.FollowWithUsername retvals from a GRPC SocialGraphService_OTServerWrapperInterface_FollowWithUsername_Response struct
func (msg *SocialGraphService_OTServerWrapperInterface_FollowWithUsername_Response) unmarshall() () {
	return
}

// Client-side function to pack SocialGraphService_OTServerWrapperInterface.GetFollowees args into a GRPC SocialGraphService_OTServerWrapperInterface_GetFollowees_Request struct
func (msg *SocialGraphService_OTServerWrapperInterface_GetFollowees_Request) marshall(reqID int64, userID int64, traceCtx string) *SocialGraphService_OTServerWrapperInterface_GetFollowees_Request {
	msg.ReqID = int64(reqID)
	msg.UserID = int64(userID)
	msg.TraceCtx = string(traceCtx)
	return msg
}

// Server-side function to unpack SocialGraphService_OTServerWrapperInterface.GetFollowees args from a GRPC SocialGraphService_OTServerWrapperInterface_GetFollowees_Request struct
func (msg *SocialGraphService_OTServerWrapperInterface_GetFollowees_Request) unmarshall() (reqID int64, userID int64, traceCtx string) {
	reqID = int64(msg.ReqID)
	userID = int64(msg.UserID)
	traceCtx = string(msg.TraceCtx)
	return
}

// Server-side function to pack SocialGraphService_OTServerWrapperInterface.GetFollowees retvals into a GRPC SocialGraphService_OTServerWrapperInterface_GetFollowees_Response struct
func (msg *SocialGraphService_OTServerWrapperInterface_GetFollowees_Response) marshall(ret0 []int64) *SocialGraphService_OTServerWrapperInterface_GetFollowees_Response {
	msg.Ret0 = ret0
	return msg
}

// Client-side function to unpack SocialGraphService_OTServerWrapperInterface.GetFollowees retvals from a GRPC SocialGraphService_OTServerWrapperInterface_GetFollowees_Response struct
func (msg *SocialGraphService_OTServerWrapperInterface_GetFollowees_Response) unmarshall() (ret0 []int64) {
	ret0 = msg.Ret0
	return
}

// Client-side function to pack SocialGraphService_OTServerWrapperInterface.GetFollowers args into a GRPC SocialGraphService_OTServerWrapperInterface_GetFollowers_Request struct
func (msg *SocialGraphService_OTServerWrapperInterface_GetFollowers_Request) marshall(reqID int64, userID int64, traceCtx string) *SocialGraphService_OTServerWrapperInterface_GetFollowers_Request {
	msg.ReqID = int64(reqID)
	msg.UserID = int64(userID)
	msg.TraceCtx = string(traceCtx)
	return msg
}

// Server-side function to unpack SocialGraphService_OTServerWrapperInterface.GetFollowers args from a GRPC SocialGraphService_OTServerWrapperInterface_GetFollowers_Request struct
func (msg *SocialGraphService_OTServerWrapperInterface_GetFollowers_Request) unmarshall() (reqID int64, userID int64, traceCtx string) {
	reqID = int64(msg.ReqID)
	userID = int64(msg.UserID)
	traceCtx = string(msg.TraceCtx)
	return
}

// Server-side function to pack SocialGraphService_OTServerWrapperInterface.GetFollowers retvals into a GRPC SocialGraphService_OTServerWrapperInterface_GetFollowers_Response struct
func (msg *SocialGraphService_OTServerWrapperInterface_GetFollowers_Response) marshall(ret0 []int64) *SocialGraphService_OTServerWrapperInterface_GetFollowers_Response {
	msg.Ret0 = ret0
	return msg
}

// Client-side function to unpack SocialGraphService_OTServerWrapperInterface.GetFollowers retvals from a GRPC SocialGraphService_OTServerWrapperInterface_GetFollowers_Response struct
func (msg *SocialGraphService_OTServerWrapperInterface_GetFollowers_Response) unmarshall() (ret0 []int64) {
	ret0 = msg.Ret0
	return
}

// Client-side function to pack SocialGraphService_OTServerWrapperInterface.InsertUser args into a GRPC SocialGraphService_OTServerWrapperInterface_InsertUser_Request struct
func (msg *SocialGraphService_OTServerWrapperInterface_InsertUser_Request) marshall(reqID int64, userID int64, traceCtx string) *SocialGraphService_OTServerWrapperInterface_InsertUser_Request {
	msg.ReqID = int64(reqID)
	msg.UserID = int64(userID)
	msg.TraceCtx = string(traceCtx)
	return msg
}

// Server-side function to unpack SocialGraphService_OTServerWrapperInterface.InsertUser args from a GRPC SocialGraphService_OTServerWrapperInterface_InsertUser_Request struct
func (msg *SocialGraphService_OTServerWrapperInterface_InsertUser_Request) unmarshall() (reqID int64, userID int64, traceCtx string) {
	reqID = int64(msg.ReqID)
	userID = int64(msg.UserID)
	traceCtx = string(msg.TraceCtx)
	return
}

// Server-side function to pack SocialGraphService_OTServerWrapperInterface.InsertUser retvals into a GRPC SocialGraphService_OTServerWrapperInterface_InsertUser_Response struct
func (msg *SocialGraphService_OTServerWrapperInterface_InsertUser_Response) marshall() *SocialGraphService_OTServerWrapperInterface_InsertUser_Response {
	return msg
}

// Client-side function to unpack SocialGraphService_OTServerWrapperInterface.InsertUser retvals from a GRPC SocialGraphService_OTServerWrapperInterface_InsertUser_Response struct
func (msg *SocialGraphService_OTServerWrapperInterface_InsertUser_Response) unmarshall() () {
	return
}

// Client-side function to pack SocialGraphService_OTServerWrapperInterface.Unfollow args into a GRPC SocialGraphService_OTServerWrapperInterface_Unfollow_Request struct
func (msg *SocialGraphService_OTServerWrapperInterface_Unfollow_Request) marshall(reqID int64, userID int64, followeeID int64, traceCtx string) *SocialGraphService_OTServerWrapperInterface_Unfollow_Request {
	msg.ReqID = int64(reqID)
	msg.UserID = int64(userID)
	msg.FolloweeID = int64(followeeID)
	msg.TraceCtx = string(traceCtx)
	return msg
}

// Server-side function to unpack SocialGraphService_OTServerWrapperInterface.Unfollow args from a GRPC SocialGraphService_OTServerWrapperInterface_Unfollow_Request struct
func (msg *SocialGraphService_OTServerWrapperInterface_Unfollow_Request) unmarshall() (reqID int64, userID int64, followeeID int64, traceCtx string) {
	reqID = int64(msg.ReqID)
	userID = int64(msg.UserID)
	followeeID = int64(msg.FolloweeID)
	traceCtx = string(msg.TraceCtx)
	return
}

// Server-side function to pack SocialGraphService_OTServerWrapperInterface.Unfollow retvals into a GRPC SocialGraphService_OTServerWrapperInterface_Unfollow_Response struct
func (msg *SocialGraphService_OTServerWrapperInterface_Unfollow_Response) marshall() *SocialGraphService_OTServerWrapperInterface_Unfollow_Response {
	return msg
}

// Client-side function to unpack SocialGraphService_OTServerWrapperInterface.Unfollow retvals from a GRPC SocialGraphService_OTServerWrapperInterface_Unfollow_Response struct
func (msg *SocialGraphService_OTServerWrapperInterface_Unfollow_Response) unmarshall() () {
	return
}

// Client-side function to pack SocialGraphService_OTServerWrapperInterface.UnfollowWithUsername args into a GRPC SocialGraphService_OTServerWrapperInterface_UnfollowWithUsername_Request struct
func (msg *SocialGraphService_OTServerWrapperInterface_UnfollowWithUsername_Request) marshall(reqID int64, userUsername string, followeeUsername string, traceCtx string) *SocialGraphService_OTServerWrapperInterface_UnfollowWithUsername_Request {
	msg.ReqID = int64(reqID)
	msg.UserUsername = string(userUsername)
	msg.FolloweeUsername = string(followeeUsername)
	msg.TraceCtx = string(traceCtx)
	return msg
}

// Server-side function to unpack SocialGraphService_OTServerWrapperInterface.UnfollowWithUsername args from a GRPC SocialGraphService_OTServerWrapperInterface_UnfollowWithUsername_Request struct
func (msg *SocialGraphService_OTServerWrapperInterface_UnfollowWithUsername_Request) unmarshall() (reqID int64, userUsername string, followeeUsername string, traceCtx string) {
	reqID = int64(msg.ReqID)
	userUsername = string(msg.UserUsername)
	followeeUsername = string(msg.FolloweeUsername)
	traceCtx = string(msg.TraceCtx)
	return
}

// Server-side function to pack SocialGraphService_OTServerWrapperInterface.UnfollowWithUsername retvals into a GRPC SocialGraphService_OTServerWrapperInterface_UnfollowWithUsername_Response struct
func (msg *SocialGraphService_OTServerWrapperInterface_UnfollowWithUsername_Response) marshall() *SocialGraphService_OTServerWrapperInterface_UnfollowWithUsername_Response {
	return msg
}

// Client-side function to unpack SocialGraphService_OTServerWrapperInterface.UnfollowWithUsername retvals from a GRPC SocialGraphService_OTServerWrapperInterface_UnfollowWithUsername_Response struct
func (msg *SocialGraphService_OTServerWrapperInterface_UnfollowWithUsername_Response) unmarshall() () {
	return
}


