apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_pb_estest/k8s
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: wrk2api-service-pb-estest-ctr
  name: wrk2api-service-pb-estest-ctr
spec:
  selector:
    matchLabels:
      io.kompose.service: wrk2api-service-pb-estest-ctr
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_pb_estest/k8s
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: wrk2api-service-pb-estest-ctr
    spec:
      containers:
      - env:
        - name: BRIDGE_KIND
          value: pb
        - name: COMPOSEPOST_SERVICE_PB_ESTEST_GRPC_DIAL_ADDR
          value: composepost-service-pb-estest-ctr:12345
        - name: GC_INTERVAL_SEC
          value: '0.1'
        - name: GOGC
          value: 'off'
        - name: HOMETIMELINE_SERVICE_PB_ESTEST_GRPC_DIAL_ADDR
          value: hometimeline-service-pb-estest-ctr:12345
        - name: OTELCOL_PB_ESTEST_DIAL_ADDR
          value: otelcol-pb-estest-ctr:4317
        - name: SOCIALGRAPH_SERVICE_PB_ESTEST_GRPC_DIAL_ADDR
          value: socialgraph-service-pb-estest-ctr:12345
        - name: USERTIMELINE_SERVICE_PB_ESTEST_GRPC_DIAL_ADDR
          value: usertimeline-service-pb-estest-ctr:12345
        - name: USER_SERVICE_PB_ESTEST_GRPC_DIAL_ADDR
          value: user-service-pb-estest-ctr:12345
        - name: WRK2API_SERVICE_PB_ESTEST_HTTP_BIND_ADDR
          value: 0.0.0.0:2000
        image: 10.10.1.1:30000/wrk2api-service-pb-estest-ctr:latest
        name: wrk2api-service-pb-estest-ctr
        ports:
        - containerPort: 2000
          protocol: TCP
      hostname: wrk2api-service-pb-estest-ctr
      restartPolicy: Always
