// Blueprint: Auto-generated by GRPC Plugin marshallgen.go
package grpc

import (
)

// Client-side function to pack ComposePostService.ComposePost args into a GRPC ComposePostService_ComposePost_Request struct
func (msg *ComposePostService_ComposePost_Request) marshall(reqID int64, username string, userID int64, text string, mediaIDs []int64, mediaTypes []string, postType int64) *ComposePostService_ComposePost_Request {
	msg.ReqID = int64(reqID)
	msg.Username = string(username)
	msg.UserID = int64(userID)
	msg.Text = string(text)
	msg.MediaIDs = mediaIDs
	msg.MediaTypes = mediaTypes
	msg.PostType = int64(postType)
	return msg
}

// Server-side function to unpack ComposePostService.ComposePost args from a GRPC ComposePostService_ComposePost_Request struct
func (msg *ComposePostService_ComposePost_Request) unmarshall() (reqID int64, username string, userID int64, text string, mediaIDs []int64, mediaTypes []string, postType int64) {
	reqID = int64(msg.ReqID)
	username = string(msg.Username)
	userID = int64(msg.UserID)
	text = string(msg.Text)
	mediaIDs = msg.MediaIDs
	mediaTypes = msg.MediaTypes
	postType = int64(msg.PostType)
	return
}

// Server-side function to pack ComposePostService.ComposePost retvals into a GRPC ComposePostService_ComposePost_Response struct
func (msg *ComposePostService_ComposePost_Response) marshall(ret0 int64, ret1 []int64) *ComposePostService_ComposePost_Response {
	msg.Ret0 = int64(ret0)
	msg.Ret1 = ret1
	return msg
}

// Client-side function to unpack ComposePostService.ComposePost retvals from a GRPC ComposePostService_ComposePost_Response struct
func (msg *ComposePostService_ComposePost_Response) unmarshall() (ret0 int64, ret1 []int64) {
	ret0 = int64(msg.Ret0)
	ret1 = msg.Ret1
	return
}


