// Blueprint: Auto-generated by OpenTelemetry Plugin
package ot

import (
	"strconv"
	"context"
	"go.opentelemetry.io/otel/trace"
	"go.opentelemetry.io/otel/attribute"
	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"strings"
	trace2 "go.opentelemetry.io/otel/sdk/trace"
)

type SocialGraphService_OTClientWrapperInterface interface {
	Follow(ctx context.Context, reqID int64, userID int64, followeeID int64) (error)
	FollowWithUsername(ctx context.Context, reqID int64, userUsername string, followeeUsername string) (error)
	GetFollowees(ctx context.Context, reqID int64, userID int64) ([]int64, error)
	GetFollowers(ctx context.Context, reqID int64, userID int64) ([]int64, error)
	InsertUser(ctx context.Context, reqID int64, userID int64) (error)
	Unfollow(ctx context.Context, reqID int64, userID int64, followeeID int64) (error)
	UnfollowWithUsername(ctx context.Context, reqID int64, userUsername string, followeeUsername string) (error)
	
}

type SocialGraphService_OTClientWrapper struct {
	Client SocialGraphService_OTServerWrapperInterface
	CollClient backend.Tracer
}

func New_SocialGraphService_OTClientWrapper(ctx context.Context, client SocialGraphService_OTServerWrapperInterface, coll_client backend.Tracer) (*SocialGraphService_OTClientWrapper, error) {
	handler := &SocialGraphService_OTClientWrapper{}
	handler.Client = client
	handler.CollClient = coll_client
	return handler, nil
}


func (handler *SocialGraphService_OTClientWrapper) Follow(ctx context.Context, reqID int64, userID int64, followeeID int64) (err error) {
	// Get baggage from context and create a copy to avoid mutating shared state
	upstreamBaggage := backend.GetBaggageFromContext(ctx)
	baggage := make(map[string]string)
	if upstreamBaggage != nil {
		for k, v := range upstreamBaggage {
			baggage[k] = v
		}
	}
	
	tp, _ := handler.CollClient.GetTracerProvider(ctx)
	tr := tp.Tracer("SocialGraphService_OTServerWrapperInterface")
	
	ctx, span := tr.Start(ctx, "SocialGraphServiceClient_Follow", trace.WithSpanKind(trace.SpanKindClient))

	defer span.End()
	
	// Extract baggage from span attributes by casting to ReadWriteSpan
	if rwSpan, ok := span.(trace2.ReadWriteSpan); ok {
		for _, attr := range rwSpan.Attributes() {
			if strings.HasPrefix(string(attr.Key), "__bag.") {
				key := strings.TrimPrefix(string(attr.Key), "__bag.")
				// Convert value to string for baggage based on attribute type
				switch attr.Value.Type() {
				case attribute.INT64:
					baggage[key] = strconv.FormatInt(attr.Value.AsInt64(), 10)
				case attribute.STRING:
					baggage[key] = attr.Value.AsString()
				default:
					baggage[key] = attr.Value.AsString()
				}
			} else if strings.HasPrefix(string(attr.Key), "__bagdel.") {
				key := strings.TrimPrefix(string(attr.Key), "__bagdel.")
				delete(baggage, key)
			}
		}
	}
	
	// Combine trace context with baggage
	trace_ctx, _ := span.SpanContext().MarshalJSON()
	trace_ctx_with_baggage, _ := backend.AddBaggageToTraceContext(string(trace_ctx), baggage)
	
	err = handler.Client.Follow(ctx, reqID, userID, followeeID, trace_ctx_with_baggage)
	if err != nil {
		span.RecordError(err)
	}
	
	return
}

func (handler *SocialGraphService_OTClientWrapper) FollowWithUsername(ctx context.Context, reqID int64, userUsername string, followeeUsername string) (err error) {
	// Get baggage from context and create a copy to avoid mutating shared state
	upstreamBaggage := backend.GetBaggageFromContext(ctx)
	baggage := make(map[string]string)
	if upstreamBaggage != nil {
		for k, v := range upstreamBaggage {
			baggage[k] = v
		}
	}
	
	tp, _ := handler.CollClient.GetTracerProvider(ctx)
	tr := tp.Tracer("SocialGraphService_OTServerWrapperInterface")
	
	ctx, span := tr.Start(ctx, "SocialGraphServiceClient_FollowWithUsername", trace.WithSpanKind(trace.SpanKindClient))

	defer span.End()
	
	// Extract baggage from span attributes by casting to ReadWriteSpan
	if rwSpan, ok := span.(trace2.ReadWriteSpan); ok {
		for _, attr := range rwSpan.Attributes() {
			if strings.HasPrefix(string(attr.Key), "__bag.") {
				key := strings.TrimPrefix(string(attr.Key), "__bag.")
				// Convert value to string for baggage based on attribute type
				switch attr.Value.Type() {
				case attribute.INT64:
					baggage[key] = strconv.FormatInt(attr.Value.AsInt64(), 10)
				case attribute.STRING:
					baggage[key] = attr.Value.AsString()
				default:
					baggage[key] = attr.Value.AsString()
				}
			} else if strings.HasPrefix(string(attr.Key), "__bagdel.") {
				key := strings.TrimPrefix(string(attr.Key), "__bagdel.")
				delete(baggage, key)
			}
		}
	}
	
	// Combine trace context with baggage
	trace_ctx, _ := span.SpanContext().MarshalJSON()
	trace_ctx_with_baggage, _ := backend.AddBaggageToTraceContext(string(trace_ctx), baggage)
	
	err = handler.Client.FollowWithUsername(ctx, reqID, userUsername, followeeUsername, trace_ctx_with_baggage)
	if err != nil {
		span.RecordError(err)
	}
	
	return
}

func (handler *SocialGraphService_OTClientWrapper) GetFollowees(ctx context.Context, reqID int64, userID int64) (ret0 []int64, err error) {
	// Get baggage from context and create a copy to avoid mutating shared state
	upstreamBaggage := backend.GetBaggageFromContext(ctx)
	baggage := make(map[string]string)
	if upstreamBaggage != nil {
		for k, v := range upstreamBaggage {
			baggage[k] = v
		}
	}
	
	tp, _ := handler.CollClient.GetTracerProvider(ctx)
	tr := tp.Tracer("SocialGraphService_OTServerWrapperInterface")
	
	ctx, span := tr.Start(ctx, "SocialGraphServiceClient_GetFollowees", trace.WithSpanKind(trace.SpanKindClient))

	defer span.End()
	
	// Extract baggage from span attributes by casting to ReadWriteSpan
	if rwSpan, ok := span.(trace2.ReadWriteSpan); ok {
		for _, attr := range rwSpan.Attributes() {
			if strings.HasPrefix(string(attr.Key), "__bag.") {
				key := strings.TrimPrefix(string(attr.Key), "__bag.")
				// Convert value to string for baggage based on attribute type
				switch attr.Value.Type() {
				case attribute.INT64:
					baggage[key] = strconv.FormatInt(attr.Value.AsInt64(), 10)
				case attribute.STRING:
					baggage[key] = attr.Value.AsString()
				default:
					baggage[key] = attr.Value.AsString()
				}
			} else if strings.HasPrefix(string(attr.Key), "__bagdel.") {
				key := strings.TrimPrefix(string(attr.Key), "__bagdel.")
				delete(baggage, key)
			}
		}
	}
	
	// Combine trace context with baggage
	trace_ctx, _ := span.SpanContext().MarshalJSON()
	trace_ctx_with_baggage, _ := backend.AddBaggageToTraceContext(string(trace_ctx), baggage)
	
	ret0, err = handler.Client.GetFollowees(ctx, reqID, userID, trace_ctx_with_baggage)
	if err != nil {
		span.RecordError(err)
	}
	
	return
}

func (handler *SocialGraphService_OTClientWrapper) GetFollowers(ctx context.Context, reqID int64, userID int64) (ret0 []int64, err error) {
	// Get baggage from context and create a copy to avoid mutating shared state
	upstreamBaggage := backend.GetBaggageFromContext(ctx)
	baggage := make(map[string]string)
	if upstreamBaggage != nil {
		for k, v := range upstreamBaggage {
			baggage[k] = v
		}
	}
	
	tp, _ := handler.CollClient.GetTracerProvider(ctx)
	tr := tp.Tracer("SocialGraphService_OTServerWrapperInterface")
	
	ctx, span := tr.Start(ctx, "SocialGraphServiceClient_GetFollowers", trace.WithSpanKind(trace.SpanKindClient))

	defer span.End()
	
	// Extract baggage from span attributes by casting to ReadWriteSpan
	if rwSpan, ok := span.(trace2.ReadWriteSpan); ok {
		for _, attr := range rwSpan.Attributes() {
			if strings.HasPrefix(string(attr.Key), "__bag.") {
				key := strings.TrimPrefix(string(attr.Key), "__bag.")
				// Convert value to string for baggage based on attribute type
				switch attr.Value.Type() {
				case attribute.INT64:
					baggage[key] = strconv.FormatInt(attr.Value.AsInt64(), 10)
				case attribute.STRING:
					baggage[key] = attr.Value.AsString()
				default:
					baggage[key] = attr.Value.AsString()
				}
			} else if strings.HasPrefix(string(attr.Key), "__bagdel.") {
				key := strings.TrimPrefix(string(attr.Key), "__bagdel.")
				delete(baggage, key)
			}
		}
	}
	
	// Combine trace context with baggage
	trace_ctx, _ := span.SpanContext().MarshalJSON()
	trace_ctx_with_baggage, _ := backend.AddBaggageToTraceContext(string(trace_ctx), baggage)
	
	ret0, err = handler.Client.GetFollowers(ctx, reqID, userID, trace_ctx_with_baggage)
	if err != nil {
		span.RecordError(err)
	}
	
	return
}

func (handler *SocialGraphService_OTClientWrapper) InsertUser(ctx context.Context, reqID int64, userID int64) (err error) {
	// Get baggage from context and create a copy to avoid mutating shared state
	upstreamBaggage := backend.GetBaggageFromContext(ctx)
	baggage := make(map[string]string)
	if upstreamBaggage != nil {
		for k, v := range upstreamBaggage {
			baggage[k] = v
		}
	}
	
	tp, _ := handler.CollClient.GetTracerProvider(ctx)
	tr := tp.Tracer("SocialGraphService_OTServerWrapperInterface")
	
	ctx, span := tr.Start(ctx, "SocialGraphServiceClient_InsertUser", trace.WithSpanKind(trace.SpanKindClient))

	defer span.End()
	
	// Extract baggage from span attributes by casting to ReadWriteSpan
	if rwSpan, ok := span.(trace2.ReadWriteSpan); ok {
		for _, attr := range rwSpan.Attributes() {
			if strings.HasPrefix(string(attr.Key), "__bag.") {
				key := strings.TrimPrefix(string(attr.Key), "__bag.")
				// Convert value to string for baggage based on attribute type
				switch attr.Value.Type() {
				case attribute.INT64:
					baggage[key] = strconv.FormatInt(attr.Value.AsInt64(), 10)
				case attribute.STRING:
					baggage[key] = attr.Value.AsString()
				default:
					baggage[key] = attr.Value.AsString()
				}
			} else if strings.HasPrefix(string(attr.Key), "__bagdel.") {
				key := strings.TrimPrefix(string(attr.Key), "__bagdel.")
				delete(baggage, key)
			}
		}
	}
	
	// Combine trace context with baggage
	trace_ctx, _ := span.SpanContext().MarshalJSON()
	trace_ctx_with_baggage, _ := backend.AddBaggageToTraceContext(string(trace_ctx), baggage)
	
	err = handler.Client.InsertUser(ctx, reqID, userID, trace_ctx_with_baggage)
	if err != nil {
		span.RecordError(err)
	}
	
	return
}

func (handler *SocialGraphService_OTClientWrapper) Unfollow(ctx context.Context, reqID int64, userID int64, followeeID int64) (err error) {
	// Get baggage from context and create a copy to avoid mutating shared state
	upstreamBaggage := backend.GetBaggageFromContext(ctx)
	baggage := make(map[string]string)
	if upstreamBaggage != nil {
		for k, v := range upstreamBaggage {
			baggage[k] = v
		}
	}
	
	tp, _ := handler.CollClient.GetTracerProvider(ctx)
	tr := tp.Tracer("SocialGraphService_OTServerWrapperInterface")
	
	ctx, span := tr.Start(ctx, "SocialGraphServiceClient_Unfollow", trace.WithSpanKind(trace.SpanKindClient))

	defer span.End()
	
	// Extract baggage from span attributes by casting to ReadWriteSpan
	if rwSpan, ok := span.(trace2.ReadWriteSpan); ok {
		for _, attr := range rwSpan.Attributes() {
			if strings.HasPrefix(string(attr.Key), "__bag.") {
				key := strings.TrimPrefix(string(attr.Key), "__bag.")
				// Convert value to string for baggage based on attribute type
				switch attr.Value.Type() {
				case attribute.INT64:
					baggage[key] = strconv.FormatInt(attr.Value.AsInt64(), 10)
				case attribute.STRING:
					baggage[key] = attr.Value.AsString()
				default:
					baggage[key] = attr.Value.AsString()
				}
			} else if strings.HasPrefix(string(attr.Key), "__bagdel.") {
				key := strings.TrimPrefix(string(attr.Key), "__bagdel.")
				delete(baggage, key)
			}
		}
	}
	
	// Combine trace context with baggage
	trace_ctx, _ := span.SpanContext().MarshalJSON()
	trace_ctx_with_baggage, _ := backend.AddBaggageToTraceContext(string(trace_ctx), baggage)
	
	err = handler.Client.Unfollow(ctx, reqID, userID, followeeID, trace_ctx_with_baggage)
	if err != nil {
		span.RecordError(err)
	}
	
	return
}

func (handler *SocialGraphService_OTClientWrapper) UnfollowWithUsername(ctx context.Context, reqID int64, userUsername string, followeeUsername string) (err error) {
	// Get baggage from context and create a copy to avoid mutating shared state
	upstreamBaggage := backend.GetBaggageFromContext(ctx)
	baggage := make(map[string]string)
	if upstreamBaggage != nil {
		for k, v := range upstreamBaggage {
			baggage[k] = v
		}
	}
	
	tp, _ := handler.CollClient.GetTracerProvider(ctx)
	tr := tp.Tracer("SocialGraphService_OTServerWrapperInterface")
	
	ctx, span := tr.Start(ctx, "SocialGraphServiceClient_UnfollowWithUsername", trace.WithSpanKind(trace.SpanKindClient))

	defer span.End()
	
	// Extract baggage from span attributes by casting to ReadWriteSpan
	if rwSpan, ok := span.(trace2.ReadWriteSpan); ok {
		for _, attr := range rwSpan.Attributes() {
			if strings.HasPrefix(string(attr.Key), "__bag.") {
				key := strings.TrimPrefix(string(attr.Key), "__bag.")
				// Convert value to string for baggage based on attribute type
				switch attr.Value.Type() {
				case attribute.INT64:
					baggage[key] = strconv.FormatInt(attr.Value.AsInt64(), 10)
				case attribute.STRING:
					baggage[key] = attr.Value.AsString()
				default:
					baggage[key] = attr.Value.AsString()
				}
			} else if strings.HasPrefix(string(attr.Key), "__bagdel.") {
				key := strings.TrimPrefix(string(attr.Key), "__bagdel.")
				delete(baggage, key)
			}
		}
	}
	
	// Combine trace context with baggage
	trace_ctx, _ := span.SpanContext().MarshalJSON()
	trace_ctx_with_baggage, _ := backend.AddBaggageToTraceContext(string(trace_ctx), baggage)
	
	err = handler.Client.UnfollowWithUsername(ctx, reqID, userUsername, followeeUsername, trace_ctx_with_baggage)
	if err != nil {
		span.RecordError(err)
	}
	
	return
}

