// socialgraph_service_v4_proc runs the socialgraph_service_v4_proc Golang process.
//
// socialgraph_service_v4_proc is auto-generated by Blueprint's goproc plugin (goproc/goprocgen/main.go.go)
//
// Usage:
//
//   go run main.go --social_cache_v4.dial_addr=value --social_db_v4.dial_addr=value --userid_service_v4.grpc.dial_addr=value --otelcol_v4.dial_addr=value --socialgraph_service_v4.grpc.bind_addr=value 
//
// socialgraph_service_v4_proc requires the following arguments are passed:
//
//   --social_cache_v4.dial_addr
//       Auto-generated by Blueprint IR node:
//       social_cache_v4.dial_addr = AddressConfig()
//
//   --social_db_v4.dial_addr
//       Auto-generated by Blueprint IR node:
//       social_db_v4.dial_addr = AddressConfig()
//
//   --userid_service_v4.grpc.dial_addr
//       Auto-generated by Blueprint IR node:
//       userid_service_v4.grpc.dial_addr = AddressConfig()
//
//   --otelcol_v4.dial_addr
//       Auto-generated by Blueprint IR node:
//       otelcol_v4.dial_addr = AddressConfig()
//
//   --socialgraph_service_v4.grpc.bind_addr
//       Auto-generated by Blueprint IR node:
//       socialgraph_service_v4.grpc.bind_addr = AddressConfig()
//
// socialgraph_service_v4_proc will instantiate the following IR nodes:
//   socialgraph_service_v4_proc.stdoutmetriccollector
//   socialgraph_service_v4_proc.logger
//   social_cache_v4.client
//   social_db_v4.client
//   userid_service_v4.clientpool
//   userid_service_v4.client.retrier
//   userid_service_v4.client
//   socialgraph_service_v4
//   otelcol_v4.client
//   socialgraph_service_v4.server.ot
//   socialgraph_service_v4.grpc_server
package main

import (
	"context"
	"os"

	"log/slog"
)

func main() {
	slog.Info("Running socialgraph_service_v4_proc")
	n, err := New_socialgraph_service_v4_proc("socialgraph_service_v4_proc").Build(context.Background())
	if err != nil {
		slog.Error(err.Error())
		os.Exit(1)
	}
	n.Await()
	slog.Info("socialgraph_service_v4_proc exiting")
}