// usermention_service_nt5_proc runs the usermention_service_nt5_proc Golang process.
//
// usermention_service_nt5_proc is auto-generated by Blueprint's goproc plugin (goproc/goprocgen/main.go.go)
//
// Usage:
//
//   go run main.go --user_cache_nt5.dial_addr=value --user_db_nt5.dial_addr=value --usermention_service_nt5.grpc.bind_addr=value 
//
// Optional env: GC_INTERVAL_SEC=N (e.g. 30, 1, 0.5, 0.1) to run GC every N seconds; fractional seconds supported. Omit or <=0 for default GC.
//
// usermention_service_nt5_proc requires the following arguments are passed:
//
//   --user_cache_nt5.dial_addr
//       Auto-generated by Blueprint IR node:
//       user_cache_nt5.dial_addr = AddressConfig()
//
//   --user_db_nt5.dial_addr
//       Auto-generated by Blueprint IR node:
//       user_db_nt5.dial_addr = AddressConfig()
//
//   --usermention_service_nt5.grpc.bind_addr
//       Auto-generated by Blueprint IR node:
//       usermention_service_nt5.grpc.bind_addr = AddressConfig()
//
// usermention_service_nt5_proc will instantiate the following IR nodes:
//   usermention_service_nt5_proc.stdoutmetriccollector
//   usermention_service_nt5_proc.logger
//   user_cache_nt5.client
//   user_db_nt5.client
//   usermention_service_nt5
//   usermention_service_nt5.grpc_server
package main

import (
	"context"
	"os"
	"runtime"
	"strconv"
	"time"

	"log/slog"
)

func main() {
	// Optional: run GC on a fixed interval to normalize GC frequency (e.g. across tracing vs no-tracing).
	// Set GC_INTERVAL_SEC to a positive number (e.g. 30, 1, 0.5, 0.1) to trigger runtime.GC() every N seconds; unset or <=0 to leave default GC behavior.
	if sec := os.Getenv("GC_INTERVAL_SEC"); sec != "" {
		if secVal, err := strconv.ParseFloat(sec, 64); err == nil && secVal > 0 && secVal < 1e15 {
			interval := time.Duration(secVal * float64(time.Second))
			if interval > 0 {
				go func() {
					ticker := time.NewTicker(interval)
					defer ticker.Stop()
					for range ticker.C {
						runtime.GC()
					}
				}()
			}
		}
	}
	slog.Info("Running usermention_service_nt5_proc")
	n, err := New_usermention_service_nt5_proc("usermention_service_nt5_proc").Build(context.Background())
	if err != nil {
		slog.Error(err.Error())
		os.Exit(1)
	}
	n.Await()
	slog.Info("usermention_service_nt5_proc exiting")
}