// Blueprint: Auto-generated by Retries Plugin
package retries

import (
	"github.com/blueprint-uservices/blueprint/examples/dsb_sn/workflow/socialnetwork"
	"context"
)

type UniqueIdService_RetrierClient struct {
	Client socialnetwork.UniqueIdService
	MaxTries int
}

func New_UniqueIdService_RetrierClient (ctx context.Context, client socialnetwork.UniqueIdService) (*UniqueIdService_RetrierClient, error) {
	handler := &UniqueIdService_RetrierClient{}
	handler.Client = client
	handler.MaxTries = 3
	return handler, nil
}


func (client *UniqueIdService_RetrierClient) ComposeUniqueId(ctx context.Context, reqID int64, postType int64) (ret0 int64, err error) {
	for i := 0; i < client.MaxTries; i++ {
		ret0, err = client.Client.ComposeUniqueId(ctx, reqID, postType)
		if err == nil {
			return
		}
	}
	return
}

