apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_vrev1/k8s
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: tracepressure-service-vrev1-ctr
  name: tracepressure-service-vrev1-ctr
spec:
  selector:
    matchLabels:
      io.kompose.service: tracepressure-service-vrev1-ctr
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_vrev1/k8s
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: tracepressure-service-vrev1-ctr
    spec:
      containers:
      - env:
        - name: BRIDGE_KIND
          value: v
        - name: GC_INTERVAL_SEC
          value: '0.1'
        - name: GOGC
          value: 'off'
        - name: OTELCOL_VREV1_DIAL_ADDR
          value: otelcol-vrev1-ctr:4317
        - name: SPAN_PADDING_BYTES
          value: '1024'
        - name: TRACEPRESSURE_SERVICE_VREV1_HTTP_BIND_ADDR
          value: 0.0.0.0:2000
        image: 10.10.1.1:30000/tracepressure-service-vrev1-ctr:latest
        name: tracepressure-service-vrev1-ctr
        ports:
        - containerPort: 2000
          protocol: TCP
      hostname: tracepressure-service-vrev1-ctr
      restartPolicy: Always
