// media_service_sb4_proc runs the media_service_sb4_proc Golang process.
//
// media_service_sb4_proc is auto-generated by Blueprint's goproc plugin (goproc/goprocgen/main.go.go)
//
// Usage:
//
//   go run main.go --otelcol_sb4.dial_addr=value --media_service_sb4.grpc.bind_addr=value 
//
// Optional env: GC_INTERVAL_SEC=N (e.g. 30, 1, 0.5, 0.1) to run GC every N seconds; fractional seconds supported. Omit or <=0 for default GC.
//
// media_service_sb4_proc requires the following arguments are passed:
//
//   --otelcol_sb4.dial_addr
//       Auto-generated by Blueprint IR node:
//       otelcol_sb4.dial_addr = AddressConfig()
//
//   --media_service_sb4.grpc.bind_addr
//       Auto-generated by Blueprint IR node:
//       media_service_sb4.grpc.bind_addr = AddressConfig()
//
// media_service_sb4_proc will instantiate the following IR nodes:
//   media_service_sb4_proc.stdoutmetriccollector
//   media_service_sb4_proc.logger
//   media_service_sb4
//   otelcol_sb4.client
//   media_service_sb4.server.ot
//   media_service_sb4.grpc_server
package main

import (
	"context"
	"os"
	"runtime"
	"strconv"
	"time"

	"log/slog"
)

func main() {
	// Optional: run GC on a fixed interval to normalize GC frequency (e.g. across tracing vs no-tracing).
	// Set GC_INTERVAL_SEC to a positive number (e.g. 30, 1, 0.5, 0.1) to trigger runtime.GC() every N seconds; unset or <=0 to leave default GC behavior.
	if sec := os.Getenv("GC_INTERVAL_SEC"); sec != "" {
		if secVal, err := strconv.ParseFloat(sec, 64); err == nil && secVal > 0 && secVal < 1e15 {
			interval := time.Duration(secVal * float64(time.Second))
			if interval > 0 {
				go func() {
					ticker := time.NewTicker(interval)
					defer ticker.Stop()
					for range ticker.C {
						runtime.GC()
					}
				}()
			}
		}
	}
	slog.Info("Running media_service_sb4_proc")
	n, err := New_media_service_sb4_proc("media_service_sb4_proc").Build(context.Background())
	if err != nil {
		slog.Error(err.Error())
		os.Exit(1)
	}
	n.Await()
	slog.Info("media_service_sb4_proc exiting")
}