// Blueprint: Auto-generated by GRPC Plugin marshallgen.go
package grpc

import (
)

// Client-side function to pack UniqueIdService.ComposeUniqueId args into a GRPC UniqueIdService_ComposeUniqueId_Request struct
func (msg *UniqueIdService_ComposeUniqueId_Request) marshall(reqID int64, postType int64) *UniqueIdService_ComposeUniqueId_Request {
	msg.ReqID = int64(reqID)
	msg.PostType = int64(postType)
	return msg
}

// Server-side function to unpack UniqueIdService.ComposeUniqueId args from a GRPC UniqueIdService_ComposeUniqueId_Request struct
func (msg *UniqueIdService_ComposeUniqueId_Request) unmarshall() (reqID int64, postType int64) {
	reqID = int64(msg.ReqID)
	postType = int64(msg.PostType)
	return
}

// Server-side function to pack UniqueIdService.ComposeUniqueId retvals into a GRPC UniqueIdService_ComposeUniqueId_Response struct
func (msg *UniqueIdService_ComposeUniqueId_Response) marshall(ret0 int64) *UniqueIdService_ComposeUniqueId_Response {
	msg.Ret0 = int64(ret0)
	return msg
}

// Client-side function to unpack UniqueIdService.ComposeUniqueId retvals from a GRPC UniqueIdService_ComposeUniqueId_Response struct
func (msg *UniqueIdService_ComposeUniqueId_Response) unmarshall() (ret0 int64) {
	ret0 = int64(msg.Ret0)
	return
}


