// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: PostStorageService.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PostStorageService_ReadPost_FullMethodName  = "/grpc.PostStorageService/ReadPost"
	PostStorageService_ReadPosts_FullMethodName = "/grpc.PostStorageService/ReadPosts"
	PostStorageService_StorePost_FullMethodName = "/grpc.PostStorageService/StorePost"
)

// PostStorageServiceClient is the client API for PostStorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PostStorageServiceClient interface {
	ReadPost(ctx context.Context, in *PostStorageService_ReadPost_Request, opts ...grpc.CallOption) (*PostStorageService_ReadPost_Response, error)
	ReadPosts(ctx context.Context, in *PostStorageService_ReadPosts_Request, opts ...grpc.CallOption) (*PostStorageService_ReadPosts_Response, error)
	StorePost(ctx context.Context, in *PostStorageService_StorePost_Request, opts ...grpc.CallOption) (*PostStorageService_StorePost_Response, error)
}

type postStorageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPostStorageServiceClient(cc grpc.ClientConnInterface) PostStorageServiceClient {
	return &postStorageServiceClient{cc}
}

func (c *postStorageServiceClient) ReadPost(ctx context.Context, in *PostStorageService_ReadPost_Request, opts ...grpc.CallOption) (*PostStorageService_ReadPost_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostStorageService_ReadPost_Response)
	err := c.cc.Invoke(ctx, PostStorageService_ReadPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postStorageServiceClient) ReadPosts(ctx context.Context, in *PostStorageService_ReadPosts_Request, opts ...grpc.CallOption) (*PostStorageService_ReadPosts_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostStorageService_ReadPosts_Response)
	err := c.cc.Invoke(ctx, PostStorageService_ReadPosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postStorageServiceClient) StorePost(ctx context.Context, in *PostStorageService_StorePost_Request, opts ...grpc.CallOption) (*PostStorageService_StorePost_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostStorageService_StorePost_Response)
	err := c.cc.Invoke(ctx, PostStorageService_StorePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostStorageServiceServer is the server API for PostStorageService service.
// All implementations must embed UnimplementedPostStorageServiceServer
// for forward compatibility.
type PostStorageServiceServer interface {
	ReadPost(context.Context, *PostStorageService_ReadPost_Request) (*PostStorageService_ReadPost_Response, error)
	ReadPosts(context.Context, *PostStorageService_ReadPosts_Request) (*PostStorageService_ReadPosts_Response, error)
	StorePost(context.Context, *PostStorageService_StorePost_Request) (*PostStorageService_StorePost_Response, error)
	mustEmbedUnimplementedPostStorageServiceServer()
}

// UnimplementedPostStorageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPostStorageServiceServer struct{}

func (UnimplementedPostStorageServiceServer) ReadPost(context.Context, *PostStorageService_ReadPost_Request) (*PostStorageService_ReadPost_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadPost not implemented")
}
func (UnimplementedPostStorageServiceServer) ReadPosts(context.Context, *PostStorageService_ReadPosts_Request) (*PostStorageService_ReadPosts_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadPosts not implemented")
}
func (UnimplementedPostStorageServiceServer) StorePost(context.Context, *PostStorageService_StorePost_Request) (*PostStorageService_StorePost_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method StorePost not implemented")
}
func (UnimplementedPostStorageServiceServer) mustEmbedUnimplementedPostStorageServiceServer() {}
func (UnimplementedPostStorageServiceServer) testEmbeddedByValue()                            {}

// UnsafePostStorageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PostStorageServiceServer will
// result in compilation errors.
type UnsafePostStorageServiceServer interface {
	mustEmbedUnimplementedPostStorageServiceServer()
}

func RegisterPostStorageServiceServer(s grpc.ServiceRegistrar, srv PostStorageServiceServer) {
	// If the following call panics, it indicates UnimplementedPostStorageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PostStorageService_ServiceDesc, srv)
}

func _PostStorageService_ReadPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostStorageService_ReadPost_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostStorageServiceServer).ReadPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostStorageService_ReadPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostStorageServiceServer).ReadPost(ctx, req.(*PostStorageService_ReadPost_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostStorageService_ReadPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostStorageService_ReadPosts_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostStorageServiceServer).ReadPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostStorageService_ReadPosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostStorageServiceServer).ReadPosts(ctx, req.(*PostStorageService_ReadPosts_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostStorageService_StorePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostStorageService_StorePost_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostStorageServiceServer).StorePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostStorageService_StorePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostStorageServiceServer).StorePost(ctx, req.(*PostStorageService_StorePost_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// PostStorageService_ServiceDesc is the grpc.ServiceDesc for PostStorageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PostStorageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.PostStorageService",
	HandlerType: (*PostStorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadPost",
			Handler:    _PostStorageService_ReadPost_Handler,
		},
		{
			MethodName: "ReadPosts",
			Handler:    _PostStorageService_ReadPosts_Handler,
		},
		{
			MethodName: "StorePost",
			Handler:    _PostStorageService_StorePost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "PostStorageService.proto",
}
