// Package pool is auto-generated by gogen/namespacebuilder.go
//
// It provides funcs for instantiating the UserIDService_PoolClient namespace.
//
// To instantiate the UserIDService_PoolClient namespace, first call [New_UserIDService_PoolClient] and then either call 
// [Build] or [BuildWithParent].
// 
// See [golang.NamespaceBuilder] docs for more information about the behavior of [Build]
package pool

import (
	"github.com/blueprint-uservices/blueprint/runtime/plugins/golang"
	"blueprint/goproc/socialgraph_service_sb_proc/grpc"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/otelcol"
	"blueprint/goproc/socialgraph_service_sb_proc/ot"
	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
)

// Initializes the UserIDService_PoolClient namespace by defining all of the nodes that run
// within the namespace.
//
// [Build] or [BuildWithParent] must be called on the return value of this func
// to actually build and run the nodes in the namespace.
func New_UserIDService_PoolClient(name string) *golang.NamespaceBuilder {
	b := golang.NewNamespaceBuilder(name)
	set_UserIDService_PoolClient_Args(b)
	set_UserIDService_PoolClient_Instances(b)
	set_UserIDService_PoolClient_Definitions(b)
	return b
}

// UserIDService_PoolClient requires that its arguments are either:
//  - explicitly set with [golang.NamespaceBuilder.Set]
//  - passed on the command line (if built using [golang.NamespaceBuilder.Build])
//  - are defined in parent (if built using [golang.NamespaceBuilder.BuildWithParent])
//
// The following arguments will be eagerly checked and building the namespace
// will fail if they haven't been provided:
//
// The following arguments are optional and a failure will only occur if the client
// tries to build a node that needs the argument to be set
func set_UserIDService_PoolClient_Args(b *golang.NamespaceBuilder) {
}

// When the UserIDService_PoolClient namespace is built it will automatically instantiate
// the following nodes:
func set_UserIDService_PoolClient_Instances(b *golang.NamespaceBuilder) {
}

// The UserIDService_PoolClient namespace contains definitions for instantiating
// the following nodes:
//   otelcol_sb.client
//   userid_service_sb.client.ot
//   userid_service_sb.grpc_client
func set_UserIDService_PoolClient_Definitions(b *golang.NamespaceBuilder) {
	b.Define("otelcol_sb.client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var addr string
		if err := n.Get("otelcol_sb.dial_addr", &addr); err != nil {
			return nil, err
		}
		
		return otelcol.NewOTCollectorTracer(n.Context(), addr, "8080")
	})
	
	b.Define("userid_service_sb.client.ot", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var client ot.UserIDService_OTServerWrapperInterface
		if err := n.Get("userid_service_sb.grpc_client", &client); err != nil {
			return nil, err
		}
		
		var coll_client backend.Tracer
		if err := n.Get("otelcol_sb.client", &coll_client); err != nil {
			return nil, err
		}
		
		return ot.New_UserIDService_OTClientWrapper(n.Context(), client, coll_client)
	})
	
	b.Define("userid_service_sb.grpc_client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var addr string
		if err := n.Get("userid_service_sb.grpc.dial_addr", &addr); err != nil {
			return nil, err
		}
		
		return grpc.New_UserIDService_GRPCClient(n.Context(), addr)
	})
	
}
