apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/sockshop/k8s
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: catalogue-ctr
  name: catalogue-ctr
spec:
  ports:
  - name: '12348'
    port: 12348
    targetPort: 12345
  - name: '12345'
    port: 12345
    targetPort: 12345
  selector:
    io.kompose.service: catalogue-ctr
status:
  loadBalancer: {}
