apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/sockshop/k8s
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend-ctr
  name: frontend-ctr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend-ctr
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/sockshop/k8s
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/docker-default: 'true'
        io.kompose.service: frontend-ctr
    spec:
      containers:
      - env:
        - name: CART_SERVICE_GRPC_DIAL_ADDR
          value: cart-ctr:12345
        - name: CATALOGUE_SERVICE_GRPC_DIAL_ADDR
          value: catalogue-ctr:12345
        - name: FRONTEND_HTTP_BIND_ADDR
          value: 0.0.0.0:2000
        - name: ORDER_SERVICE_GRPC_DIAL_ADDR
          value: order-ctr:12345
        - name: OTELCOL_DIAL_ADDR
          value: otelcol-ctr:4317
        - name: USER_SERVICE_GRPC_DIAL_ADDR
          value: user-ctr:12345
        image: 10.10.1.1:30000/frontend-ctr:latest
        name: frontend-ctr
        ports:
        - containerPort: 2000
          hostIP: 0.0.0.0
          hostPort: 12349
          protocol: TCP
        resources: {}
      hostname: frontend-ctr
      restartPolicy: Always
status: {}
