apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/sockshop/k8s
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: otelcol-ctr
  name: otelcol-ctr
spec:
  internalTrafficPolicy: Local
  ports:
  - name: '12355'
    port: 12355
    targetPort: 4317
  - name: '12356'
    port: 12356
    targetPort: 8080
  - name: '4317'
    port: 4317
    targetPort: 4317
  - name: '8080'
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: otelcol-ctr
status:
  loadBalancer: {}
