apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/sockshop/k8s
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: user-db-ctr
  name: user-db-ctr
spec:
  ports:
  - name: '12360'
    port: 12360
    targetPort: 27017
  - name: '27017'
    port: 27017
    targetPort: 27017
  selector:
    io.kompose.service: user-db-ctr
status:
  loadBalancer: {}
