exporters:
  otlp:
    endpoint: ${JAEGER_NT_ES_OTLP_DIAL_ADDR}
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_elapsed_time: 0
      max_interval: 30s
    sending_queue:
      block_on_overflow: false
      enabled: true
      queue_size: 1000
    tls:
      insecure: true
processors:
  batch: {}
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
service:
  pipelines:
    traces:
      exporters:
      - otlp
      processors:
      - batch
      receivers:
      - otlp
  telemetry:
    logs:
      level: DEBUG
