// Package main is auto-generated by gogen/namespacebuilder.go
//
// It provides funcs for instantiating the uniqueid_service_sb_proc namespace.
//
// To instantiate the uniqueid_service_sb_proc namespace, first call [New_uniqueid_service_sb_proc] and then either call 
// [Build] or [BuildWithParent].
// 
// See [golang.NamespaceBuilder] docs for more information about the behavior of [Build]
package main

import (
	"github.com/blueprint-uservices/blueprint/runtime/plugins/opentelemetry"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/slogger"
	"github.com/blueprint-uservices/blueprint/examples/dsb_sn/workflow/socialnetwork"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/otelcol"
	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"blueprint/goproc/uniqueid_service_sb_proc/ot"
	"blueprint/goproc/uniqueid_service_sb_proc/grpc"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/golang"
)

// Initializes the uniqueid_service_sb_proc namespace by defining all of the nodes that run
// within the namespace.
//
// [Build] or [BuildWithParent] must be called on the return value of this func
// to actually build and run the nodes in the namespace.
func New_uniqueid_service_sb_proc(name string) *golang.NamespaceBuilder {
	b := golang.NewNamespaceBuilder(name)
	set_uniqueid_service_sb_proc_Args(b)
	set_uniqueid_service_sb_proc_Instances(b)
	set_uniqueid_service_sb_proc_Definitions(b)
	return b
}

// uniqueid_service_sb_proc requires that its arguments are either:
//  - explicitly set with [golang.NamespaceBuilder.Set]
//  - passed on the command line (if built using [golang.NamespaceBuilder.Build])
//  - are defined in parent (if built using [golang.NamespaceBuilder.BuildWithParent])
//
// The following arguments will be eagerly checked and building the namespace
// will fail if they haven't been provided:
//   otelcol_sb.dial_addr
//   uniqueid_service_sb.grpc.bind_addr
//
// The following arguments are optional and a failure will only occur if the client
// tries to build a node that needs the argument to be set
func set_uniqueid_service_sb_proc_Args(b *golang.NamespaceBuilder) {
	b.Required("otelcol_sb.dial_addr", "Argument generated by Blueprint IR: otelcol_sb.dial_addr = AddressConfig()")
	b.Required("uniqueid_service_sb.grpc.bind_addr", "Argument generated by Blueprint IR: uniqueid_service_sb.grpc.bind_addr = AddressConfig()")
}

// When the uniqueid_service_sb_proc namespace is built it will automatically instantiate
// the following nodes:
//   uniqueid_service_sb_proc.stdoutmetriccollector
//   uniqueid_service_sb_proc.logger
//   uniqueid_service_sb
//   otelcol_sb.client
//   uniqueid_service_sb.server.ot
//   uniqueid_service_sb.grpc_server
func set_uniqueid_service_sb_proc_Instances(b *golang.NamespaceBuilder) {
	b.Instantiate("uniqueid_service_sb_proc.stdoutmetriccollector")
	b.Instantiate("uniqueid_service_sb_proc.logger")
	b.Instantiate("uniqueid_service_sb")
	b.Instantiate("otelcol_sb.client")
	b.Instantiate("uniqueid_service_sb.server.ot")
	b.Instantiate("uniqueid_service_sb.grpc_server")
}

// The uniqueid_service_sb_proc namespace contains definitions for instantiating
// the following nodes:
//   otelcol_sb.client
//   uniqueid_service_sb
//   uniqueid_service_sb.grpc_server
//   uniqueid_service_sb.server.ot
//   uniqueid_service_sb_proc.logger
//   uniqueid_service_sb_proc.stdoutmetriccollector
func set_uniqueid_service_sb_proc_Definitions(b *golang.NamespaceBuilder) {
	b.Define("otelcol_sb.client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var addr string
		if err := n.Get("otelcol_sb.dial_addr", &addr); err != nil {
			return nil, err
		}
		
		return otelcol.NewOTCollectorTracer(n.Context(), addr, "8080")
	})
	
	b.Define("uniqueid_service_sb", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		return socialnetwork.NewUniqueIdServiceImpl(n.Context())
	})
	
	b.Define("uniqueid_service_sb.grpc_server", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var service ot.UniqueIdService_OTServerWrapperInterface
		if err := n.Get("uniqueid_service_sb.server.ot", &service); err != nil {
			return nil, err
		}
		
		var serverAddr string
		if err := n.Get("uniqueid_service_sb.grpc.bind_addr", &serverAddr); err != nil {
			return nil, err
		}
		
		return grpc.New_UniqueIdService_GRPCServerHandler(n.Context(), service, serverAddr)
	})
	
	b.Define("uniqueid_service_sb.server.ot", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var service socialnetwork.UniqueIdService
		if err := n.Get("uniqueid_service_sb", &service); err != nil {
			return nil, err
		}
		
		var otCollectorClient backend.Tracer
		if err := n.Get("otelcol_sb.client", &otCollectorClient); err != nil {
			return nil, err
		}
		
		return ot.New_UniqueIdService_OTServerWrapper(n.Context(), service, otCollectorClient)
	})
	
	b.Define("uniqueid_service_sb_proc.logger", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		return slogger.NewSLogger(n.Context())
	})
	
	b.Define("uniqueid_service_sb_proc.stdoutmetriccollector", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		return opentelemetry.NewStdoutMetricCollector(n.Context())
	})
	
}
