// text_service_v7_proc runs the text_service_v7_proc Golang process.
//
// text_service_v7_proc is auto-generated by Blueprint's goproc plugin (goproc/goprocgen/main.go.go)
//
// Usage:
//
//   go run main.go --urlshorten_service_v7.grpc.dial_addr=value --otelcol_v7.dial_addr=value --usermention_service_v7.grpc.dial_addr=value --text_service_v7.grpc.bind_addr=value 
//
// text_service_v7_proc requires the following arguments are passed:
//
//   --urlshorten_service_v7.grpc.dial_addr
//       Auto-generated by Blueprint IR node:
//       urlshorten_service_v7.grpc.dial_addr = AddressConfig()
//
//   --otelcol_v7.dial_addr
//       Auto-generated by Blueprint IR node:
//       otelcol_v7.dial_addr = AddressConfig()
//
//   --usermention_service_v7.grpc.dial_addr
//       Auto-generated by Blueprint IR node:
//       usermention_service_v7.grpc.dial_addr = AddressConfig()
//
//   --text_service_v7.grpc.bind_addr
//       Auto-generated by Blueprint IR node:
//       text_service_v7.grpc.bind_addr = AddressConfig()
//
// text_service_v7_proc will instantiate the following IR nodes:
//   text_service_v7_proc.stdoutmetriccollector
//   text_service_v7_proc.logger
//   urlshorten_service_v7.grpc_client
//   otelcol_v7.client
//   urlshorten_service_v7.client.ot
//   urlshorten_service_v7.client.retrier
//   urlshorten_service_v7.client
//   usermention_service_v7.grpc_client
//   usermention_service_v7.client.ot
//   usermention_service_v7.client.retrier
//   usermention_service_v7.client
//   text_service_v7
//   text_service_v7.server.ot
//   text_service_v7.grpc_server
package main

import (
	"context"
	"os"

	"log/slog"
)

func main() {
	slog.Info("Running text_service_v7_proc")
	n, err := New_text_service_v7_proc("text_service_v7_proc").Build(context.Background())
	if err != nil {
		slog.Error(err.Error())
		os.Exit(1)
	}
	n.Await()
	slog.Info("text_service_v7_proc exiting")
}