// Blueprint: Auto-generated by GRPC Plugin
package grpc

import (
	"context"
	"net"
	"google.golang.org/grpc"
	"blueprint/goproc/userid_service_v6_proc/ot"
)

type UserIDService_GRPCServerHandler struct {
	UnimplementedUserIDService_OTServerWrapperInterfaceServer
	Service ot.UserIDService_OTServerWrapperInterface
	Address string
}

func New_UserIDService_GRPCServerHandler(ctx context.Context, service ot.UserIDService_OTServerWrapperInterface, serverAddress string) (*UserIDService_GRPCServerHandler, error) {
	handler := &UserIDService_GRPCServerHandler{}
	handler.Service = service
	handler.Address = serverAddress
	return handler, nil
}

// Blueprint: Run is called automatically in a separate goroutine by runtime/plugins/golang/di.go
func (handler *UserIDService_GRPCServerHandler) Run(ctx context.Context) error {
	lis, err := net.Listen("tcp", handler.Address)
	if err != nil {
		return err
	}

	s := grpc.NewServer()
	RegisterUserIDService_OTServerWrapperInterfaceServer(s, handler)

	go func() {
		select {
		case <-ctx.Done():
			s.GracefulStop()
		}
	}()

	return s.Serve(lis)
}


func (handler *UserIDService_GRPCServerHandler) GetUserId(ctx context.Context, req *UserIDService_OTServerWrapperInterface_GetUserId_Request) (*UserIDService_OTServerWrapperInterface_GetUserId_Response, error) {
	reqID, username, traceCtx := req.unmarshall()
	ret0, err := handler.Service.GetUserId(ctx, reqID, username, traceCtx)
	if err != nil {
		return nil, err
	}

	rsp := &UserIDService_OTServerWrapperInterface_GetUserId_Response{}
	rsp.marshall(ret0)
	return rsp, nil
}

