// Blueprint: Auto-generated by HTTP Plugin
package http

import (
	"encoding/json"
	"net/http"
	"github.com/gorilla/mux"
	"blueprint/goproc/nonleaf_proc/ot"
	"context"
)

type NonLeafService_HTTPServerHandler struct {
	Service ot.NonLeafService_OTServerWrapperInterface
	Address string
}

func New_NonLeafService_HTTPServerHandler(ctx context.Context, service ot.NonLeafService_OTServerWrapperInterface, serverAddress string) (*NonLeafService_HTTPServerHandler, error) {
	handler := &NonLeafService_HTTPServerHandler{}
	handler.Service = service
	handler.Address = serverAddress
	return handler, nil
}

// Blueprint: Run is called automatically in a separate goroutine by runtime/plugins/golang/di.go
func (handler *NonLeafService_HTTPServerHandler) Run(ctx context.Context) error {
	router := mux.NewRouter()
	// Add paths for the mux router
	
	router.Path("/Hello").HandlerFunc(handler.Hello)
	
	srv := &http.Server {
		Addr: handler.Address,
		Handler: router,
	}

	go func() {
		select {
		case <-ctx.Done():
			srv.Shutdown(ctx)
		}
	}()

	return srv.ListenAndServe()
}


func (handler *NonLeafService_HTTPServerHandler) Hello(w http.ResponseWriter, r *http.Request) {
	var err error
	defer r.Body.Close()
	
	request_a := r.URL.Query().Get("a")
	var a int64
	if request_a != "" {
		err = json.Unmarshal([]byte(request_a), &a)
		if err != nil {
			http.Error(w, err.Error(), 500)
			return
		}
	}
	
	traceCtx := r.URL.Query().Get("traceCtx")
	
	ctx := context.Background()
	ret0, ret1, err := handler.Service.Hello(ctx, a, traceCtx)
	if err != nil {
		http.Error(w, err.Error(), 500)
		return
	}
	response := struct {
		
		Ret0 int64
		
		Ret1 string
		
	}{}
	
	response.Ret0 = ret0
	
	response.Ret1 = ret1
	
	json.NewEncoder(w).Encode(response)
}

