apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_v/k8s
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: otelcol-v-ctr
  name: otelcol-v-ctr
spec:
  selector:
    matchLabels:
      io.kompose.service: otelcol-v-ctr
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_v/k8s
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: otelcol-v-ctr
    spec:
      containers:
      - env:
        - name: JAEGER_V_OTLP_DIAL_ADDR
          value: jaeger-v-ctr:4317
        image: 10.10.1.1:30000/otelcol-v-ctr:latest
        name: otelcol-v-ctr
        ports:
        - containerPort: 4317
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
      hostname: otelcol-v-ctr
      restartPolicy: Always
