apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_v/k8s
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: usertimeline-cache-v-ctr
  name: usertimeline-cache-v-ctr
spec:
  ports:
  - name: '12370'
    port: 12370
    targetPort: 6379
  - name: '6379'
    port: 6379
    targetPort: 6379
  selector:
    io.kompose.service: usertimeline-cache-v-ctr
