apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_v/k8s
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: usertimeline-service-v-ctr
  name: usertimeline-service-v-ctr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: usertimeline-service-v-ctr
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_v/k8s
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: usertimeline-service-v-ctr
    spec:
      containers:
      - env:
        - name: OTELCOL_V_DIAL_ADDR
          value: otelcol-v-ctr:4317
        - name: POST_STORAGE_SERVICE_V_GRPC_DIAL_ADDR
          value: post-storage-service-v-ctr:12345
        - name: USERTIMELINE_CACHE_V_DIAL_ADDR
          value: usertimeline-cache-v-ctr:6379
        - name: USERTIMELINE_DB_V_DIAL_ADDR
          value: usertimeline-db-v-ctr:27017
        - name: USERTIMELINE_SERVICE_V_GRPC_BIND_ADDR
          value: 0.0.0.0:12345
        image: 10.10.1.1:30000/usertimeline-service-v-ctr:latest
        name: usertimeline-service-v-ctr
        ports:
        - containerPort: 12345
          protocol: TCP
        resources:
          requests:
            cpu: 8000m
      hostname: usertimeline-service-v-ctr
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: node-4
