// composepost_service_v8_proc runs the composepost_service_v8_proc Golang process.
//
// composepost_service_v8_proc is auto-generated by Blueprint's goproc plugin (goproc/goprocgen/main.go.go)
//
// Usage:
//
//   go run main.go --post_storage_service_v8.grpc.dial_addr=value --otelcol_v8.dial_addr=value --usertimeline_service_v8.grpc.dial_addr=value --user_service_v8.grpc.dial_addr=value --uniqueid_service_v8.grpc.dial_addr=value --media_service_v8.grpc.dial_addr=value --text_service_v8.grpc.dial_addr=value --hometimeline_service_v8.grpc.dial_addr=value --composepost_service_v8.grpc.bind_addr=value 
//
// Optional env: GC_INTERVAL_SEC=N (e.g. 30, 1, 0.5, 0.1) to run GC every N seconds; fractional seconds supported. Omit or <=0 for default GC.
//
// composepost_service_v8_proc requires the following arguments are passed:
//
//   --post_storage_service_v8.grpc.dial_addr
//       Auto-generated by Blueprint IR node:
//       post_storage_service_v8.grpc.dial_addr = AddressConfig()
//
//   --otelcol_v8.dial_addr
//       Auto-generated by Blueprint IR node:
//       otelcol_v8.dial_addr = AddressConfig()
//
//   --usertimeline_service_v8.grpc.dial_addr
//       Auto-generated by Blueprint IR node:
//       usertimeline_service_v8.grpc.dial_addr = AddressConfig()
//
//   --user_service_v8.grpc.dial_addr
//       Auto-generated by Blueprint IR node:
//       user_service_v8.grpc.dial_addr = AddressConfig()
//
//   --uniqueid_service_v8.grpc.dial_addr
//       Auto-generated by Blueprint IR node:
//       uniqueid_service_v8.grpc.dial_addr = AddressConfig()
//
//   --media_service_v8.grpc.dial_addr
//       Auto-generated by Blueprint IR node:
//       media_service_v8.grpc.dial_addr = AddressConfig()
//
//   --text_service_v8.grpc.dial_addr
//       Auto-generated by Blueprint IR node:
//       text_service_v8.grpc.dial_addr = AddressConfig()
//
//   --hometimeline_service_v8.grpc.dial_addr
//       Auto-generated by Blueprint IR node:
//       hometimeline_service_v8.grpc.dial_addr = AddressConfig()
//
//   --composepost_service_v8.grpc.bind_addr
//       Auto-generated by Blueprint IR node:
//       composepost_service_v8.grpc.bind_addr = AddressConfig()
//
// composepost_service_v8_proc will instantiate the following IR nodes:
//   composepost_service_v8_proc.stdoutmetriccollector
//   composepost_service_v8_proc.logger
//   post_storage_service_v8.grpc_client
//   otelcol_v8.client
//   post_storage_service_v8.client.ot
//   post_storage_service_v8.client.retrier
//   post_storage_service_v8.client
//   usertimeline_service_v8.grpc_client
//   usertimeline_service_v8.client.ot
//   usertimeline_service_v8.client.retrier
//   usertimeline_service_v8.client
//   user_service_v8.grpc_client
//   user_service_v8.client.ot
//   user_service_v8.client.retrier
//   user_service_v8.client
//   uniqueid_service_v8.grpc_client
//   uniqueid_service_v8.client.ot
//   uniqueid_service_v8.client.retrier
//   uniqueid_service_v8.client
//   media_service_v8.grpc_client
//   media_service_v8.client.ot
//   media_service_v8.client.retrier
//   media_service_v8.client
//   text_service_v8.grpc_client
//   text_service_v8.client.ot
//   text_service_v8.client.retrier
//   text_service_v8.client
//   hometimeline_service_v8.grpc_client
//   hometimeline_service_v8.client.ot
//   hometimeline_service_v8.client.retrier
//   hometimeline_service_v8.client
//   composepost_service_v8
//   composepost_service_v8.server.ot
//   composepost_service_v8.grpc_server
package main

import (
	"context"
	"os"
	"runtime"
	"strconv"
	"time"

	"log/slog"
)

func main() {
	// Optional: run GC on a fixed interval to normalize GC frequency (e.g. across tracing vs no-tracing).
	// Set GC_INTERVAL_SEC to a positive number (e.g. 30, 1, 0.5, 0.1) to trigger runtime.GC() every N seconds; unset or <=0 to leave default GC behavior.
	if sec := os.Getenv("GC_INTERVAL_SEC"); sec != "" {
		if secVal, err := strconv.ParseFloat(sec, 64); err == nil && secVal > 0 && secVal < 1e15 {
			interval := time.Duration(secVal * float64(time.Second))
			if interval > 0 {
				go func() {
					ticker := time.NewTicker(interval)
					defer ticker.Stop()
					for range ticker.C {
						runtime.GC()
					}
				}()
			}
		}
	}
	slog.Info("Running composepost_service_v8_proc")
	n, err := New_composepost_service_v8_proc("composepost_service_v8_proc").Build(context.Background())
	if err != nil {
		slog.Error(err.Error())
		os.Exit(1)
	}
	n.Await()
	slog.Info("composepost_service_v8_proc exiting")
}