apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_v_nwctl/k8s
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: post-storage-service-v-es-nw-ctr
  name: post-storage-service-v-es-nw-ctr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: post-storage-service-v-es-nw-ctr
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_v_nwctl/k8s
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: post-storage-service-v-es-nw-ctr
    spec:
      containers:
      - env:
        - name: BRIDGE_KIND
          value: v
        - name: GC_INTERVAL_SEC
          value: '0'
        - name: GOGC
          value: '100'
        - name: OTELCOL_V_ES_NW_DIAL_ADDR
          value: otelcol-v-es-nw-ctr:4317
        - name: POST_CACHE_V_ES_NW_DIAL_ADDR
          value: post-cache-v-es-nw-ctr:6379
        - name: POST_DB_V_ES_NW_DIAL_ADDR
          value: post-db-v-es-nw-ctr:27017
        - name: POST_STORAGE_SERVICE_V_ES_NW_GRPC_BIND_ADDR
          value: 0.0.0.0:12345
        - name: OTLP_RETRY
          value: 'off'
        - name: OTEL_SAMPLE_RATIO
          value: '0.1'
        - name: GOMAXPROCS
          value: '8'
        image: 10.10.1.1:30000/post-storage-service-v-es-nw-ctr:latest
        name: post-storage-service-v-es-nw-ctr
        ports:
        - containerPort: 12345
          protocol: TCP
        resources:
          requests:
            cpu: 8000m
          limits:
            cpu: 8000m
      hostname: post-storage-service-v-es-nw-ctr
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: node-5
