// Blueprint: Auto-generated by HTTP Plugin
package http

import (
	"context"
	"encoding/json"
	"net/http"
	"github.com/gorilla/mux"
	"github.com/blueprint-uservices/blueprint/examples/dsb_sn/workflow/snnw"
)

type TracePressureService_HTTPServerHandler struct {
	Service snnw.TracePressureService
	Address string
}

func New_TracePressureService_HTTPServerHandler(ctx context.Context, service snnw.TracePressureService, serverAddress string) (*TracePressureService_HTTPServerHandler, error) {
	handler := &TracePressureService_HTTPServerHandler{}
	handler.Service = service
	handler.Address = serverAddress
	return handler, nil
}

// Blueprint: Run is called automatically in a separate goroutine by runtime/plugins/golang/di.go
func (handler *TracePressureService_HTTPServerHandler) Run(ctx context.Context) error {
	router := mux.NewRouter()
	// Add paths for the mux router
	
	router.Path("/Spam").HandlerFunc(handler.Spam)
	
	srv := &http.Server {
		Addr: handler.Address,
		Handler: router,
	}

	go func() {
		select {
		case <-ctx.Done():
			srv.Shutdown(ctx)
		}
	}()

	return srv.ListenAndServe()
}


func (handler *TracePressureService_HTTPServerHandler) Spam(w http.ResponseWriter, r *http.Request) {
	var err error
	defer r.Body.Close()
	
	request_n := r.URL.Query().Get("n")
	var n int64
	if request_n != "" {
		err = json.Unmarshal([]byte(request_n), &n)
		if err != nil {
			http.Error(w, err.Error(), 500)
			return
		}
	}
	
	ctx := context.Background()
	ret0, err := handler.Service.Spam(ctx, n)
	if err != nil {
		http.Error(w, err.Error(), 500)
		return
	}
	response := struct {
		
		Ret0 int64
		
	}{}
	
	response.Ret0 = ret0
	
	json.NewEncoder(w).Encode(response)
}

