// Blueprint: Auto-generated by OpenTelemetry Plugin
package ot

import (
	"context"
	"go.opentelemetry.io/otel/trace"
	"sync/atomic"
	"strconv"
	"github.com/blueprint-uservices/blueprint/examples/dsb_sn/workflow/socialnetwork"
	"go.opentelemetry.io/otel/attribute"
	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"strings"
	"sync"
	trace2 "go.opentelemetry.io/otel/sdk/trace"
)

type UrlShortenService_OTClientWrapperInterface interface {
	ComposeUrls(ctx context.Context, reqID int64, urls []string) ([]socialnetwork.URL, error)
	GetExtendedUrls(ctx context.Context, reqID int64, shortenedUrls []string) ([]string, error)
	
}

type UrlShortenService_OTClientWrapper struct {
	Client UrlShortenService_OTServerWrapperInterface
	CollClient backend.Tracer
}

func New_UrlShortenService_OTClientWrapper(ctx context.Context, client UrlShortenService_OTServerWrapperInterface, coll_client backend.Tracer) (*UrlShortenService_OTClientWrapper, error) {
	handler := &UrlShortenService_OTClientWrapper{}
	handler.Client = client
	handler.CollClient = coll_client
	return handler, nil
}


func (handler *UrlShortenService_OTClientWrapper) ComposeUrls(ctx context.Context, reqID int64, urls []string) (ret0 []socialnetwork.URL, err error) {
	// Get baggage from context and create a copy to avoid mutating shared state
	upstreamBaggage := backend.GetBaggageFromContext(ctx)
	baggage := make(map[string]string)
	if upstreamBaggage != nil {
		for k, v := range upstreamBaggage {
			baggage[k] = v
		}
	}

	// Server always sets these values, so we can skip ok checks to reduce overhead
	// Cache pointers after first lookup to avoid repeated context.Value() calls
	eventCountPtr := ctx.Value("eventCount").(*atomic.Uint64)
	endEventsPtr := ctx.Value("endEvents").(*string)
	childrenMutexPtr := ctx.Value("childrenMutex").(*sync.Mutex)
	seqNum := int(eventCountPtr.Add(1))

	ctx = context.WithValue(ctx, "seqNum", seqNum)
	childrenMutexPtr.Lock()
	curEndEvents := *endEventsPtr
	*endEventsPtr = ""
	childrenMutexPtr.Unlock()

	ctx = context.WithValue(ctx, "curEndEvents", curEndEvents)
	
	tp, _ := handler.CollClient.GetTracerProvider(ctx)
	tr := tp.Tracer("UrlShortenService_OTServerWrapperInterface")

	// childrenMutexPtr.Lock()
	
	ctx, span := tr.Start(ctx, "UrlShortenServiceClient_ComposeUrls", trace.WithSpanKind(trace.SpanKindClient))

	// childrenMutexPtr.Unlock()

	defer span.End()
	
	// Extract baggage from span attributes by casting to ReadWriteSpan
	if rwSpan, ok := span.(trace2.ReadWriteSpan); ok {
		for _, attr := range rwSpan.Attributes() {
			if strings.HasPrefix(string(attr.Key), "__bag.") {
				key := strings.TrimPrefix(string(attr.Key), "__bag.")
				// Convert value to string for baggage based on attribute type
				switch attr.Value.Type() {
				case attribute.INT64:
					baggage[key] = strconv.FormatInt(attr.Value.AsInt64(), 10)
				case attribute.STRING:
					baggage[key] = attr.Value.AsString()
				default:
					baggage[key] = attr.Value.AsString()
				}
			} else if strings.HasPrefix(string(attr.Key), "__bagdel.") {
				key := strings.TrimPrefix(string(attr.Key), "__bagdel.")
				delete(baggage, key)
			}
		}
	}
	
	// Combine trace context with baggage
	trace_ctx, _ := span.SpanContext().MarshalJSON()
	trace_ctx_with_baggage, _ := backend.AddBaggageToTraceContext(string(trace_ctx), baggage)
	
	ret0, err = handler.Client.ComposeUrls(ctx, reqID, urls, trace_ctx_with_baggage)
	if err != nil {
		span.RecordError(err)
	}

	endSeqNum := int(eventCountPtr.Add(1))
	toAppend := "," + strconv.Itoa(seqNum) + ":" + strconv.Itoa(endSeqNum)
	childrenMutexPtr.Lock()
	*endEventsPtr = *endEventsPtr + toAppend
	childrenMutexPtr.Unlock()
	
	return
}

func (handler *UrlShortenService_OTClientWrapper) GetExtendedUrls(ctx context.Context, reqID int64, shortenedUrls []string) (ret0 []string, err error) {
	// Get baggage from context and create a copy to avoid mutating shared state
	upstreamBaggage := backend.GetBaggageFromContext(ctx)
	baggage := make(map[string]string)
	if upstreamBaggage != nil {
		for k, v := range upstreamBaggage {
			baggage[k] = v
		}
	}

	// Server always sets these values, so we can skip ok checks to reduce overhead
	// Cache pointers after first lookup to avoid repeated context.Value() calls
	eventCountPtr := ctx.Value("eventCount").(*atomic.Uint64)
	endEventsPtr := ctx.Value("endEvents").(*string)
	childrenMutexPtr := ctx.Value("childrenMutex").(*sync.Mutex)
	seqNum := int(eventCountPtr.Add(1))

	ctx = context.WithValue(ctx, "seqNum", seqNum)
	childrenMutexPtr.Lock()
	curEndEvents := *endEventsPtr
	*endEventsPtr = ""
	childrenMutexPtr.Unlock()

	ctx = context.WithValue(ctx, "curEndEvents", curEndEvents)
	
	tp, _ := handler.CollClient.GetTracerProvider(ctx)
	tr := tp.Tracer("UrlShortenService_OTServerWrapperInterface")

	// childrenMutexPtr.Lock()
	
	ctx, span := tr.Start(ctx, "UrlShortenServiceClient_GetExtendedUrls", trace.WithSpanKind(trace.SpanKindClient))

	// childrenMutexPtr.Unlock()

	defer span.End()
	
	// Extract baggage from span attributes by casting to ReadWriteSpan
	if rwSpan, ok := span.(trace2.ReadWriteSpan); ok {
		for _, attr := range rwSpan.Attributes() {
			if strings.HasPrefix(string(attr.Key), "__bag.") {
				key := strings.TrimPrefix(string(attr.Key), "__bag.")
				// Convert value to string for baggage based on attribute type
				switch attr.Value.Type() {
				case attribute.INT64:
					baggage[key] = strconv.FormatInt(attr.Value.AsInt64(), 10)
				case attribute.STRING:
					baggage[key] = attr.Value.AsString()
				default:
					baggage[key] = attr.Value.AsString()
				}
			} else if strings.HasPrefix(string(attr.Key), "__bagdel.") {
				key := strings.TrimPrefix(string(attr.Key), "__bagdel.")
				delete(baggage, key)
			}
		}
	}
	
	// Combine trace context with baggage
	trace_ctx, _ := span.SpanContext().MarshalJSON()
	trace_ctx_with_baggage, _ := backend.AddBaggageToTraceContext(string(trace_ctx), baggage)
	
	ret0, err = handler.Client.GetExtendedUrls(ctx, reqID, shortenedUrls, trace_ctx_with_baggage)
	if err != nil {
		span.RecordError(err)
	}

	endSeqNum := int(eventCountPtr.Add(1))
	toAppend := "," + strconv.Itoa(seqNum) + ":" + strconv.Itoa(endSeqNum)
	childrenMutexPtr.Lock()
	*endEventsPtr = *endEventsPtr + toAppend
	childrenMutexPtr.Unlock()
	
	return
}

