// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: UserIDService.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserIDService_OTServerWrapperInterface_GetUserId_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReqID         int64                  `protobuf:"zigzag64,1,opt,name=reqID,proto3" json:"reqID,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	TraceCtx      string                 `protobuf:"bytes,3,opt,name=traceCtx,proto3" json:"traceCtx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIDService_OTServerWrapperInterface_GetUserId_Request) Reset() {
	*x = UserIDService_OTServerWrapperInterface_GetUserId_Request{}
	mi := &file_UserIDService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIDService_OTServerWrapperInterface_GetUserId_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIDService_OTServerWrapperInterface_GetUserId_Request) ProtoMessage() {}

func (x *UserIDService_OTServerWrapperInterface_GetUserId_Request) ProtoReflect() protoreflect.Message {
	mi := &file_UserIDService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIDService_OTServerWrapperInterface_GetUserId_Request.ProtoReflect.Descriptor instead.
func (*UserIDService_OTServerWrapperInterface_GetUserId_Request) Descriptor() ([]byte, []int) {
	return file_UserIDService_proto_rawDescGZIP(), []int{0}
}

func (x *UserIDService_OTServerWrapperInterface_GetUserId_Request) GetReqID() int64 {
	if x != nil {
		return x.ReqID
	}
	return 0
}

func (x *UserIDService_OTServerWrapperInterface_GetUserId_Request) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserIDService_OTServerWrapperInterface_GetUserId_Request) GetTraceCtx() string {
	if x != nil {
		return x.TraceCtx
	}
	return ""
}

type UserIDService_OTServerWrapperInterface_GetUserId_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret0          int64                  `protobuf:"zigzag64,1,opt,name=ret0,proto3" json:"ret0,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIDService_OTServerWrapperInterface_GetUserId_Response) Reset() {
	*x = UserIDService_OTServerWrapperInterface_GetUserId_Response{}
	mi := &file_UserIDService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIDService_OTServerWrapperInterface_GetUserId_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIDService_OTServerWrapperInterface_GetUserId_Response) ProtoMessage() {}

func (x *UserIDService_OTServerWrapperInterface_GetUserId_Response) ProtoReflect() protoreflect.Message {
	mi := &file_UserIDService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIDService_OTServerWrapperInterface_GetUserId_Response.ProtoReflect.Descriptor instead.
func (*UserIDService_OTServerWrapperInterface_GetUserId_Response) Descriptor() ([]byte, []int) {
	return file_UserIDService_proto_rawDescGZIP(), []int{1}
}

func (x *UserIDService_OTServerWrapperInterface_GetUserId_Response) GetRet0() int64 {
	if x != nil {
		return x.Ret0
	}
	return 0
}

var File_UserIDService_proto protoreflect.FileDescriptor

const file_UserIDService_proto_rawDesc = "" +
	"\n" +
	"\x13UserIDService.proto\x12\x04grpc\"\x88\x01\n" +
	"8UserIDService_OTServerWrapperInterface_GetUserId_Request\x12\x14\n" +
	"\x05reqID\x18\x01 \x01(\x12R\x05reqID\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\btraceCtx\x18\x03 \x01(\tR\btraceCtx\"O\n" +
	"9UserIDService_OTServerWrapperInterface_GetUserId_Response\x12\x12\n" +
	"\x04ret0\x18\x01 \x01(\x12R\x04ret02\xb9\x01\n" +
	"&UserIDService_OTServerWrapperInterface\x12\x8e\x01\n" +
	"\tGetUserId\x12>.grpc.UserIDService_OTServerWrapperInterface_GetUserId_Request\x1a?.grpc.UserIDService_OTServerWrapperInterface_GetUserId_Response\"\x00B\tZ\a./;grpcb\x06proto3"

var (
	file_UserIDService_proto_rawDescOnce sync.Once
	file_UserIDService_proto_rawDescData []byte
)

func file_UserIDService_proto_rawDescGZIP() []byte {
	file_UserIDService_proto_rawDescOnce.Do(func() {
		file_UserIDService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_UserIDService_proto_rawDesc), len(file_UserIDService_proto_rawDesc)))
	})
	return file_UserIDService_proto_rawDescData
}

var file_UserIDService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_UserIDService_proto_goTypes = []any{
	(*UserIDService_OTServerWrapperInterface_GetUserId_Request)(nil),  // 0: grpc.UserIDService_OTServerWrapperInterface_GetUserId_Request
	(*UserIDService_OTServerWrapperInterface_GetUserId_Response)(nil), // 1: grpc.UserIDService_OTServerWrapperInterface_GetUserId_Response
}
var file_UserIDService_proto_depIdxs = []int32{
	0, // 0: grpc.UserIDService_OTServerWrapperInterface.GetUserId:input_type -> grpc.UserIDService_OTServerWrapperInterface_GetUserId_Request
	1, // 1: grpc.UserIDService_OTServerWrapperInterface.GetUserId:output_type -> grpc.UserIDService_OTServerWrapperInterface_GetUserId_Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_UserIDService_proto_init() }
func file_UserIDService_proto_init() {
	if File_UserIDService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_UserIDService_proto_rawDesc), len(file_UserIDService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_UserIDService_proto_goTypes,
		DependencyIndexes: file_UserIDService_proto_depIdxs,
		MessageInfos:      file_UserIDService_proto_msgTypes,
	}.Build()
	File_UserIDService_proto = out.File
	file_UserIDService_proto_goTypes = nil
	file_UserIDService_proto_depIdxs = nil
}
