// This file is auto-generated by the Blueprint clientpool plugin
package pool

import (
	"fmt"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/clientpool"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/golang"
	"github.com/blueprint-uservices/blueprint/examples/dsb_sn/workflow/socialnetwork"
	"context"
)

type PostStorageService_ClientPool struct {
	clients *clientpool.ClientPool[socialnetwork.PostStorageService]
}

func New_PostStorageService_Pool(parent *golang.Namespace) *PostStorageService_ClientPool {
	i := 0
	createClient := func() (socialnetwork.PostStorageService, error) {
		clientName := fmt.Sprintf("post_storage_service_nt2.clientpool.%v", i)
		n, err := New_PostStorageService_PoolClient(clientName).BuildWithParent(parent)
		if err != nil {
			return nil, err
		}
		i++
		var client socialnetwork.PostStorageService
		err = n.Get("post_storage_service_nt2.grpc_client", &client)
		return client, err
	}
	clients := clientpool.NewClientPool(10, createClient)
	return &PostStorageService_ClientPool{clients: clients}
}


func (pool *PostStorageService_ClientPool) ReadPost(ctx context.Context, reqID int64, postID int64) (ret0 socialnetwork.Post, err error) {
	client, err := pool.clients.Pop(ctx)
	if err != nil {
		return
	}
	defer pool.clients.Push(client)
	return client.ReadPost(ctx, reqID, postID)
}

func (pool *PostStorageService_ClientPool) ReadPosts(ctx context.Context, reqID int64, postIDs []int64) (ret0 []socialnetwork.Post, err error) {
	client, err := pool.clients.Pop(ctx)
	if err != nil {
		return
	}
	defer pool.clients.Push(client)
	return client.ReadPosts(ctx, reqID, postIDs)
}

func (pool *PostStorageService_ClientPool) StorePost(ctx context.Context, reqID int64, post socialnetwork.Post) (err error) {
	client, err := pool.clients.Pop(ctx)
	if err != nil {
		return
	}
	defer pool.clients.Push(client)
	return client.StorePost(ctx, reqID, post)
}



