// Package main is auto-generated by gogen/namespacebuilder.go
//
// It provides funcs for instantiating the user_service_pb_es_proc namespace.
//
// To instantiate the user_service_pb_es_proc namespace, first call [New_user_service_pb_es_proc] and then either call
// [Build] or [BuildWithParent].
//
// See [golang.NamespaceBuilder] docs for more information about the behavior of [Build]
package main

import (
	"blueprint/goproc/user_service_pb_es_proc/grpc"
	"blueprint/goproc/user_service_pb_es_proc/ot"
	"blueprint/goproc/user_service_pb_es_proc/retries"

	"github.com/blueprint-uservices/blueprint/examples/dsb_sn/workflow/socialnetwork"
	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/golang"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/mongodb"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/opentelemetry"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/otelcol"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/redis"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/slogger"
)

// Initializes the user_service_pb_es_proc namespace by defining all of the nodes that run
// within the namespace.
//
// [Build] or [BuildWithParent] must be called on the return value of this func
// to actually build and run the nodes in the namespace.
func New_user_service_pb_es_proc(name string) *golang.NamespaceBuilder {
	b := golang.NewNamespaceBuilder(name)
	set_user_service_pb_es_proc_Args(b)
	set_user_service_pb_es_proc_Instances(b)
	set_user_service_pb_es_proc_Definitions(b)
	return b
}

// user_service_pb_es_proc requires that its arguments are either:
//   - explicitly set with [golang.NamespaceBuilder.Set]
//   - passed on the command line (if built using [golang.NamespaceBuilder.Build])
//   - are defined in parent (if built using [golang.NamespaceBuilder.BuildWithParent])
//
// The following arguments will be eagerly checked and building the namespace
// will fail if they haven't been provided:
//
//	otelcol_pb_es.dial_addr
//	socialgraph_service_pb_es.grpc.dial_addr
//	user_cache_pb_es.dial_addr
//	user_db_pb_es.dial_addr
//	user_service_pb_es.grpc.bind_addr
//
// The following arguments are optional and a failure will only occur if the client
// tries to build a node that needs the argument to be set
func set_user_service_pb_es_proc_Args(b *golang.NamespaceBuilder) {
	b.Required("otelcol_pb_es.dial_addr", "Argument generated by Blueprint IR: otelcol_pb_es.dial_addr = AddressConfig()")
	b.Required("socialgraph_service_pb_es.grpc.dial_addr", "Argument generated by Blueprint IR: socialgraph_service_pb_es.grpc.dial_addr = AddressConfig()")
	b.Required("user_cache_pb_es.dial_addr", "Argument generated by Blueprint IR: user_cache_pb_es.dial_addr = AddressConfig()")
	b.Required("user_db_pb_es.dial_addr", "Argument generated by Blueprint IR: user_db_pb_es.dial_addr = AddressConfig()")
	b.Required("user_service_pb_es.grpc.bind_addr", "Argument generated by Blueprint IR: user_service_pb_es.grpc.bind_addr = AddressConfig()")
}

// When the user_service_pb_es_proc namespace is built it will automatically instantiate
// the following nodes:
//
//	user_service_pb_es_proc.stdoutmetriccollector
//	user_service_pb_es_proc.logger
//	user_cache_pb_es.client
//	user_db_pb_es.client
//	socialgraph_service_pb_es.grpc_client
//	otelcol_pb_es.client
//	socialgraph_service_pb_es.client.ot
//	socialgraph_service_pb_es.client.retrier
//	socialgraph_service_pb_es.client
//	user_service_pb_es
//	user_service_pb_es.server.ot
//	user_service_pb_es.grpc_server
func set_user_service_pb_es_proc_Instances(b *golang.NamespaceBuilder) {
	b.Instantiate("user_service_pb_es_proc.stdoutmetriccollector")
	b.Instantiate("user_service_pb_es_proc.logger")
	b.Instantiate("user_cache_pb_es.client")
	b.Instantiate("user_db_pb_es.client")
	b.Instantiate("socialgraph_service_pb_es.grpc_client")
	b.Instantiate("otelcol_pb_es.client")
	b.Instantiate("socialgraph_service_pb_es.client.ot")
	b.Instantiate("socialgraph_service_pb_es.client.retrier")
	b.Instantiate("socialgraph_service_pb_es.client")
	b.Instantiate("user_service_pb_es")
	b.Instantiate("user_service_pb_es.server.ot")
	b.Instantiate("user_service_pb_es.grpc_server")
}

// The user_service_pb_es_proc namespace contains definitions for instantiating
// the following nodes:
//
//	otelcol_pb_es.client
//	socialgraph_service_pb_es.client
//	socialgraph_service_pb_es.client.ot
//	socialgraph_service_pb_es.client.retrier
//	socialgraph_service_pb_es.grpc_client
//	user_cache_pb_es.client
//	user_db_pb_es.client
//	user_service_pb_es
//	user_service_pb_es.grpc_server
//	user_service_pb_es.server.ot
//	user_service_pb_es_proc.logger
//	user_service_pb_es_proc.stdoutmetriccollector
func set_user_service_pb_es_proc_Definitions(b *golang.NamespaceBuilder) {
	b.Define("otelcol_pb_es.client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var addr string
		if err := n.Get("otelcol_pb_es.dial_addr", &addr); err != nil {
			return nil, err
		}

		return otelcol.NewOTCollectorTracer(n.Context(), addr, "8080")
	})

	b.Define("socialgraph_service_pb_es.client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin workflow/ir_workflowservice.go
		var client socialnetwork.SocialGraphService
		err := n.Get("socialgraph_service_pb_es.client.retrier", &client)
		return client, err
	})

	b.Define("socialgraph_service_pb_es.client.ot", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var client ot.SocialGraphService_OTServerWrapperInterface
		if err := n.Get("socialgraph_service_pb_es.grpc_client", &client); err != nil {
			return nil, err
		}

		var coll_client backend.Tracer
		if err := n.Get("otelcol_pb_es.client", &coll_client); err != nil {
			return nil, err
		}

		return ot.New_SocialGraphService_OTClientWrapper(n.Context(), client, coll_client)
	})

	b.Define("socialgraph_service_pb_es.client.retrier", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var client ot.SocialGraphService_OTClientWrapperInterface
		if err := n.Get("socialgraph_service_pb_es.client.ot", &client); err != nil {
			return nil, err
		}

		return retries.New_SocialGraphService_RetrierClient(n.Context(), client)
	})

	b.Define("socialgraph_service_pb_es.grpc_client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var addr string
		if err := n.Get("socialgraph_service_pb_es.grpc.dial_addr", &addr); err != nil {
			return nil, err
		}

		return grpc.New_SocialGraphService_GRPCClient(n.Context(), addr)
	})

	b.Define("user_cache_pb_es.client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var addr string
		if err := n.Get("user_cache_pb_es.dial_addr", &addr); err != nil {
			return nil, err
		}

		return redis.NewRedisCacheClient(n.Context(), addr)
	})

	b.Define("user_db_pb_es.client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var addr string
		if err := n.Get("user_db_pb_es.dial_addr", &addr); err != nil {
			return nil, err
		}

		return mongodb.NewMongoDB(n.Context(), addr)
	})

	b.Define("user_service_pb_es", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var userCache backend.Cache
		if err := n.Get("user_cache_pb_es.client", &userCache); err != nil {
			return nil, err
		}

		var userDB backend.NoSQLDatabase
		if err := n.Get("user_db_pb_es.client", &userDB); err != nil {
			return nil, err
		}

		var socialGraphService socialnetwork.SocialGraphService
		if err := n.Get("socialgraph_service_pb_es.client", &socialGraphService); err != nil {
			return nil, err
		}

		return socialnetwork.NewUserServiceImpl(n.Context(), userCache, userDB, socialGraphService, "secret")
	})

	b.Define("user_service_pb_es.grpc_server", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var service ot.UserService_OTServerWrapperInterface
		if err := n.Get("user_service_pb_es.server.ot", &service); err != nil {
			return nil, err
		}

		var serverAddr string
		if err := n.Get("user_service_pb_es.grpc.bind_addr", &serverAddr); err != nil {
			return nil, err
		}

		return grpc.New_UserService_GRPCServerHandler(n.Context(), service, serverAddr)
	})

	b.Define("user_service_pb_es.server.ot", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var service socialnetwork.UserService
		if err := n.Get("user_service_pb_es", &service); err != nil {
			return nil, err
		}

		var otCollectorClient backend.Tracer
		if err := n.Get("otelcol_pb_es.client", &otCollectorClient); err != nil {
			return nil, err
		}

		return ot.New_UserService_OTServerWrapper(n.Context(), service, otCollectorClient)
	})

	b.Define("user_service_pb_es_proc.logger", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		return slogger.NewSLogger(n.Context())
	})

	b.Define("user_service_pb_es_proc.stdoutmetriccollector", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		return opentelemetry.NewStdoutMetricCollector(n.Context())
	})

}
