// Package main is auto-generated by gogen/namespacebuilder.go
//
// It provides funcs for instantiating the composepost_service_v4_proc namespace.
//
// To instantiate the composepost_service_v4_proc namespace, first call [New_composepost_service_v4_proc] and then either call 
// [Build] or [BuildWithParent].
// 
// See [golang.NamespaceBuilder] docs for more information about the behavior of [Build]
package main

import (
	"blueprint/goproc/composepost_service_v4_proc/ot"
	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/golang"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/slogger"
	"blueprint/goproc/composepost_service_v4_proc/retries"
	"github.com/blueprint-uservices/blueprint/examples/dsb_sn/workflow/socialnetwork"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/otelcol"
	"blueprint/goproc/composepost_service_v4_proc/grpc"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/opentelemetry"
	"blueprint/goproc/composepost_service_v4_proc/pool"
)

// Initializes the composepost_service_v4_proc namespace by defining all of the nodes that run
// within the namespace.
//
// [Build] or [BuildWithParent] must be called on the return value of this func
// to actually build and run the nodes in the namespace.
func New_composepost_service_v4_proc(name string) *golang.NamespaceBuilder {
	b := golang.NewNamespaceBuilder(name)
	set_composepost_service_v4_proc_Args(b)
	set_composepost_service_v4_proc_Instances(b)
	set_composepost_service_v4_proc_Definitions(b)
	return b
}

// composepost_service_v4_proc requires that its arguments are either:
//  - explicitly set with [golang.NamespaceBuilder.Set]
//  - passed on the command line (if built using [golang.NamespaceBuilder.Build])
//  - are defined in parent (if built using [golang.NamespaceBuilder.BuildWithParent])
//
// The following arguments will be eagerly checked and building the namespace
// will fail if they haven't been provided:
//   composepost_service_v4.grpc.bind_addr
//   hometimeline_service_v4.grpc.dial_addr
//   media_service_v4.grpc.dial_addr
//   otelcol_v4.dial_addr
//   post_storage_service_v4.grpc.dial_addr
//   text_service_v4.grpc.dial_addr
//   uniqueid_service_v4.grpc.dial_addr
//   user_service_v4.grpc.dial_addr
//   usertimeline_service_v4.grpc.dial_addr
//
// The following arguments are optional and a failure will only occur if the client
// tries to build a node that needs the argument to be set
func set_composepost_service_v4_proc_Args(b *golang.NamespaceBuilder) {
	b.Required("composepost_service_v4.grpc.bind_addr", "Argument generated by Blueprint IR: composepost_service_v4.grpc.bind_addr = AddressConfig()")
	b.Required("hometimeline_service_v4.grpc.dial_addr", "Argument generated by Blueprint IR: hometimeline_service_v4.grpc.dial_addr = AddressConfig()")
	b.Required("media_service_v4.grpc.dial_addr", "Argument generated by Blueprint IR: media_service_v4.grpc.dial_addr = AddressConfig()")
	b.Required("otelcol_v4.dial_addr", "Argument generated by Blueprint IR: otelcol_v4.dial_addr = AddressConfig()")
	b.Required("post_storage_service_v4.grpc.dial_addr", "Argument generated by Blueprint IR: post_storage_service_v4.grpc.dial_addr = AddressConfig()")
	b.Required("text_service_v4.grpc.dial_addr", "Argument generated by Blueprint IR: text_service_v4.grpc.dial_addr = AddressConfig()")
	b.Required("uniqueid_service_v4.grpc.dial_addr", "Argument generated by Blueprint IR: uniqueid_service_v4.grpc.dial_addr = AddressConfig()")
	b.Required("user_service_v4.grpc.dial_addr", "Argument generated by Blueprint IR: user_service_v4.grpc.dial_addr = AddressConfig()")
	b.Required("usertimeline_service_v4.grpc.dial_addr", "Argument generated by Blueprint IR: usertimeline_service_v4.grpc.dial_addr = AddressConfig()")
}

// When the composepost_service_v4_proc namespace is built it will automatically instantiate
// the following nodes:
//   composepost_service_v4_proc.stdoutmetriccollector
//   composepost_service_v4_proc.logger
//   post_storage_service_v4.clientpool
//   post_storage_service_v4.client.retrier
//   post_storage_service_v4.client
//   usertimeline_service_v4.clientpool
//   usertimeline_service_v4.client.retrier
//   usertimeline_service_v4.client
//   user_service_v4.clientpool
//   user_service_v4.client.retrier
//   user_service_v4.client
//   uniqueid_service_v4.clientpool
//   uniqueid_service_v4.client.retrier
//   uniqueid_service_v4.client
//   media_service_v4.clientpool
//   media_service_v4.client.retrier
//   media_service_v4.client
//   text_service_v4.clientpool
//   text_service_v4.client.retrier
//   text_service_v4.client
//   hometimeline_service_v4.clientpool
//   hometimeline_service_v4.client.retrier
//   hometimeline_service_v4.client
//   composepost_service_v4
//   otelcol_v4.client
//   composepost_service_v4.server.ot
//   composepost_service_v4.grpc_server
func set_composepost_service_v4_proc_Instances(b *golang.NamespaceBuilder) {
	b.Instantiate("composepost_service_v4_proc.stdoutmetriccollector")
	b.Instantiate("composepost_service_v4_proc.logger")
	b.Instantiate("post_storage_service_v4.clientpool")
	b.Instantiate("post_storage_service_v4.client.retrier")
	b.Instantiate("post_storage_service_v4.client")
	b.Instantiate("usertimeline_service_v4.clientpool")
	b.Instantiate("usertimeline_service_v4.client.retrier")
	b.Instantiate("usertimeline_service_v4.client")
	b.Instantiate("user_service_v4.clientpool")
	b.Instantiate("user_service_v4.client.retrier")
	b.Instantiate("user_service_v4.client")
	b.Instantiate("uniqueid_service_v4.clientpool")
	b.Instantiate("uniqueid_service_v4.client.retrier")
	b.Instantiate("uniqueid_service_v4.client")
	b.Instantiate("media_service_v4.clientpool")
	b.Instantiate("media_service_v4.client.retrier")
	b.Instantiate("media_service_v4.client")
	b.Instantiate("text_service_v4.clientpool")
	b.Instantiate("text_service_v4.client.retrier")
	b.Instantiate("text_service_v4.client")
	b.Instantiate("hometimeline_service_v4.clientpool")
	b.Instantiate("hometimeline_service_v4.client.retrier")
	b.Instantiate("hometimeline_service_v4.client")
	b.Instantiate("composepost_service_v4")
	b.Instantiate("otelcol_v4.client")
	b.Instantiate("composepost_service_v4.server.ot")
	b.Instantiate("composepost_service_v4.grpc_server")
}

// The composepost_service_v4_proc namespace contains definitions for instantiating
// the following nodes:
//   composepost_service_v4
//   composepost_service_v4.grpc_server
//   composepost_service_v4.server.ot
//   composepost_service_v4_proc.logger
//   composepost_service_v4_proc.stdoutmetriccollector
//   hometimeline_service_v4.client
//   hometimeline_service_v4.client.retrier
//   hometimeline_service_v4.clientpool
//   media_service_v4.client
//   media_service_v4.client.retrier
//   media_service_v4.clientpool
//   otelcol_v4.client
//   post_storage_service_v4.client
//   post_storage_service_v4.client.retrier
//   post_storage_service_v4.clientpool
//   text_service_v4.client
//   text_service_v4.client.retrier
//   text_service_v4.clientpool
//   uniqueid_service_v4.client
//   uniqueid_service_v4.client.retrier
//   uniqueid_service_v4.clientpool
//   user_service_v4.client
//   user_service_v4.client.retrier
//   user_service_v4.clientpool
//   usertimeline_service_v4.client
//   usertimeline_service_v4.client.retrier
//   usertimeline_service_v4.clientpool
func set_composepost_service_v4_proc_Definitions(b *golang.NamespaceBuilder) {
	b.Define("composepost_service_v4", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var postStorageService socialnetwork.PostStorageService
		if err := n.Get("post_storage_service_v4.client", &postStorageService); err != nil {
			return nil, err
		}
		
		var userTimelineService socialnetwork.UserTimelineService
		if err := n.Get("usertimeline_service_v4.client", &userTimelineService); err != nil {
			return nil, err
		}
		
		var userService socialnetwork.UserService
		if err := n.Get("user_service_v4.client", &userService); err != nil {
			return nil, err
		}
		
		var uniqueIDService socialnetwork.UniqueIdService
		if err := n.Get("uniqueid_service_v4.client", &uniqueIDService); err != nil {
			return nil, err
		}
		
		var mediaService socialnetwork.MediaService
		if err := n.Get("media_service_v4.client", &mediaService); err != nil {
			return nil, err
		}
		
		var textService socialnetwork.TextService
		if err := n.Get("text_service_v4.client", &textService); err != nil {
			return nil, err
		}
		
		var homeTimelineService socialnetwork.HomeTimelineService
		if err := n.Get("hometimeline_service_v4.client", &homeTimelineService); err != nil {
			return nil, err
		}
		
		return socialnetwork.NewComposePostServiceImpl(n.Context(), postStorageService, userTimelineService, userService, uniqueIDService, mediaService, textService, homeTimelineService)
	})
	
	b.Define("composepost_service_v4.grpc_server", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var service ot.ComposePostService_OTServerWrapperInterface
		if err := n.Get("composepost_service_v4.server.ot", &service); err != nil {
			return nil, err
		}
		
		var serverAddr string
		if err := n.Get("composepost_service_v4.grpc.bind_addr", &serverAddr); err != nil {
			return nil, err
		}
		
		return grpc.New_ComposePostService_GRPCServerHandler(n.Context(), service, serverAddr)
	})
	
	b.Define("composepost_service_v4.server.ot", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var service socialnetwork.ComposePostService
		if err := n.Get("composepost_service_v4", &service); err != nil {
			return nil, err
		}
		
		var otCollectorClient backend.Tracer
		if err := n.Get("otelcol_v4.client", &otCollectorClient); err != nil {
			return nil, err
		}
		
		return ot.New_ComposePostService_OTServerWrapper(n.Context(), service, otCollectorClient)
	})
	
	b.Define("composepost_service_v4_proc.logger", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		return slogger.NewSLogger(n.Context())
	})
	
	b.Define("composepost_service_v4_proc.stdoutmetriccollector", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		return opentelemetry.NewStdoutMetricCollector(n.Context())
	})
	
	b.Define("hometimeline_service_v4.client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin workflow/ir_workflowservice.go
		var client socialnetwork.HomeTimelineService
		err := n.Get("hometimeline_service_v4.client.retrier", &client)
		return client, err
	})
	
	b.Define("hometimeline_service_v4.client.retrier", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var client ot.HomeTimelineService_OTClientWrapperInterface
		if err := n.Get("hometimeline_service_v4.clientpool", &client); err != nil {
			return nil, err
		}
		
		return retries.New_HomeTimelineService_RetrierClient(n.Context(), client)
	})
	
	b.Define("hometimeline_service_v4.clientpool", func(n *golang.Namespace) (any, error) {
		return pool.New_HomeTimelineService_Pool(n), nil
	})
	
	b.Define("media_service_v4.client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin workflow/ir_workflowservice.go
		var client socialnetwork.MediaService
		err := n.Get("media_service_v4.client.retrier", &client)
		return client, err
	})
	
	b.Define("media_service_v4.client.retrier", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var client ot.MediaService_OTClientWrapperInterface
		if err := n.Get("media_service_v4.clientpool", &client); err != nil {
			return nil, err
		}
		
		return retries.New_MediaService_RetrierClient(n.Context(), client)
	})
	
	b.Define("media_service_v4.clientpool", func(n *golang.Namespace) (any, error) {
		return pool.New_MediaService_Pool(n), nil
	})
	
	b.Define("otelcol_v4.client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var addr string
		if err := n.Get("otelcol_v4.dial_addr", &addr); err != nil {
			return nil, err
		}
		
		return otelcol.NewOTCollectorTracer(n.Context(), addr, "8080")
	})
	
	b.Define("post_storage_service_v4.client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin workflow/ir_workflowservice.go
		var client socialnetwork.PostStorageService
		err := n.Get("post_storage_service_v4.client.retrier", &client)
		return client, err
	})
	
	b.Define("post_storage_service_v4.client.retrier", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var client ot.PostStorageService_OTClientWrapperInterface
		if err := n.Get("post_storage_service_v4.clientpool", &client); err != nil {
			return nil, err
		}
		
		return retries.New_PostStorageService_RetrierClient(n.Context(), client)
	})
	
	b.Define("post_storage_service_v4.clientpool", func(n *golang.Namespace) (any, error) {
		return pool.New_PostStorageService_Pool(n), nil
	})
	
	b.Define("text_service_v4.client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin workflow/ir_workflowservice.go
		var client socialnetwork.TextService
		err := n.Get("text_service_v4.client.retrier", &client)
		return client, err
	})
	
	b.Define("text_service_v4.client.retrier", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var client ot.TextService_OTClientWrapperInterface
		if err := n.Get("text_service_v4.clientpool", &client); err != nil {
			return nil, err
		}
		
		return retries.New_TextService_RetrierClient(n.Context(), client)
	})
	
	b.Define("text_service_v4.clientpool", func(n *golang.Namespace) (any, error) {
		return pool.New_TextService_Pool(n), nil
	})
	
	b.Define("uniqueid_service_v4.client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin workflow/ir_workflowservice.go
		var client socialnetwork.UniqueIdService
		err := n.Get("uniqueid_service_v4.client.retrier", &client)
		return client, err
	})
	
	b.Define("uniqueid_service_v4.client.retrier", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var client ot.UniqueIdService_OTClientWrapperInterface
		if err := n.Get("uniqueid_service_v4.clientpool", &client); err != nil {
			return nil, err
		}
		
		return retries.New_UniqueIdService_RetrierClient(n.Context(), client)
	})
	
	b.Define("uniqueid_service_v4.clientpool", func(n *golang.Namespace) (any, error) {
		return pool.New_UniqueIdService_Pool(n), nil
	})
	
	b.Define("user_service_v4.client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin workflow/ir_workflowservice.go
		var client socialnetwork.UserService
		err := n.Get("user_service_v4.client.retrier", &client)
		return client, err
	})
	
	b.Define("user_service_v4.client.retrier", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var client ot.UserService_OTClientWrapperInterface
		if err := n.Get("user_service_v4.clientpool", &client); err != nil {
			return nil, err
		}
		
		return retries.New_UserService_RetrierClient(n.Context(), client)
	})
	
	b.Define("user_service_v4.clientpool", func(n *golang.Namespace) (any, error) {
		return pool.New_UserService_Pool(n), nil
	})
	
	b.Define("usertimeline_service_v4.client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin workflow/ir_workflowservice.go
		var client socialnetwork.UserTimelineService
		err := n.Get("usertimeline_service_v4.client.retrier", &client)
		return client, err
	})
	
	b.Define("usertimeline_service_v4.client.retrier", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var client ot.UserTimelineService_OTClientWrapperInterface
		if err := n.Get("usertimeline_service_v4.clientpool", &client); err != nil {
			return nil, err
		}
		
		return retries.New_UserTimelineService_RetrierClient(n.Context(), client)
	})
	
	b.Define("usertimeline_service_v4.clientpool", func(n *golang.Namespace) (any, error) {
		return pool.New_UserTimelineService_Pool(n), nil
	})
	
}
