// uniqueid_service_nt4_proc runs the uniqueid_service_nt4_proc Golang process.
//
// uniqueid_service_nt4_proc is auto-generated by Blueprint's goproc plugin (goproc/goprocgen/main.go.go)
//
// Usage:
//
//   go run main.go --uniqueid_service_nt4.grpc.bind_addr=value 
//
// uniqueid_service_nt4_proc requires the following arguments are passed:
//
//   --uniqueid_service_nt4.grpc.bind_addr
//       Auto-generated by Blueprint IR node:
//       uniqueid_service_nt4.grpc.bind_addr = AddressConfig()
//
// uniqueid_service_nt4_proc will instantiate the following IR nodes:
//   uniqueid_service_nt4_proc.stdoutmetriccollector
//   uniqueid_service_nt4_proc.logger
//   uniqueid_service_nt4
//   uniqueid_service_nt4.grpc_server
package main

import (
	"context"
	"os"

	"log/slog"
)

func main() {
	slog.Info("Running uniqueid_service_nt4_proc")
	n, err := New_uniqueid_service_nt4_proc("uniqueid_service_nt4_proc").Build(context.Background())
	if err != nil {
		slog.Error(err.Error())
		os.Exit(1)
	}
	n.Await()
	slog.Info("uniqueid_service_nt4_proc exiting")
}