package burstload

import (
	"fmt"
	"path/filepath"

	"github.com/blueprint-uservices/blueprint/plugins/golang"
	"github.com/blueprint-uservices/blueprint/plugins/golang/gocode"
	"github.com/blueprint-uservices/blueprint/plugins/golang/gogen"
	"golang.org/x/exp/slog"
)

// code generation function called from the ir.go file for burst load generator.
func generateBurstLoadGenerator(builder golang.ModuleBuilder, wrapped *gocode.ServiceInterface, outputPackage string, burstSize int64, burstDuration string, burstInterval string) error {
	pkg, err := builder.CreatePackage(outputPackage)
	if err != nil {
		return err
	}

	client := clientArgs{
		Package:       pkg,
		Service:       wrapped,
		Name:          wrapped.BaseName + "_BurstLoadGenerator",
		BurstSize:     burstSize,
		BurstDuration: burstDuration,
		BurstInterval: burstInterval,
		Imports:       gogen.NewImports(pkg.Name),
	}

	client.Imports.AddPackages("context", "sync", "time", "os", "strconv", "strings", "log", "math/rand", "sync/atomic")

	return generateClientCommon(&client, burstLoadGeneratorTemplate)
}


func generateClientCommon(client *clientArgs, clientTemplate string) error {
	clientName := client.Name
	slog.Info(fmt.Sprintf("Generating %v/%v", client.Package.PackageName, clientName))
	outputFile := filepath.Join(client.Package.Path, clientName+".go")
	return gogen.ExecuteTemplateToFile("BurstLoad", clientTemplate, client, outputFile)
}

type clientArgs struct {
	Package       golang.PackageInfo
	Service       *gocode.ServiceInterface
	Name          string
	BurstSize     int64  // X requests/sec
	BurstDuration string // Y seconds (burst generation period)
	BurstInterval string // Z seconds (wait between burst periods)
	Imports       *gogen.Imports
}

var burstLoadGeneratorTemplate = `// Blueprint: Auto-generated by BurstLoad Plugin
package {{.Package.ShortName}}

{{.Imports}}

// Burst Load Generator - runs inside service, independent of business logic
type {{.Name}} struct {
	Client        {{.Imports.NameOf .Service.UserType}}
	BurstSize     int           // X requests/sec
	BurstDuration time.Duration // Y seconds (burst generation period)
	BurstInterval time.Duration // Z seconds (wait between burst periods)
	
	// Method selection and data recording
	BurstMethods  []string      // Which methods to call for burst generation
	RecordedCalls []RecordedCall // Real data captured from actual calls
	CallCounter   int64         // Counts total calls to trigger sampling
	
	// Control
	ctx    context.Context
	cancel context.CancelFunc
	wg     sync.WaitGroup
	mu     sync.RWMutex // Protects RecordedCalls
}

// RecordedCall stores real parameters from actual service calls
type RecordedCall struct {
	MethodName string
	Args       []interface{}
	Timestamp  time.Time
}

// Global call counter for sampling (atomic for thread safety)
var globalCallCounter int64

func New_{{.Name}} (ctx context.Context, client {{.Imports.NameOf .Service.UserType}}) (*{{.Name}}, error) {
	generator := &{{.Name}}{}
	generator.Client = client
	
	// Compile-time defaults
	generator.BurstSize = int({{.BurstSize}})
	
	burstDuration, _ := time.ParseDuration("{{.BurstDuration}}")
	generator.BurstDuration = burstDuration
	
	burstInterval, _ := time.ParseDuration("{{.BurstInterval}}")
	generator.BurstInterval = burstInterval
	
	// Initialize data structures
	generator.RecordedCalls = make([]RecordedCall, 0, 100) // Buffer for recorded calls
	generator.BurstMethods = []string{ {{range $i, $f := .Service.Methods}}{{if eq $i 0}}"{{$f.Name}}"{{end}}{{end}} } // Default to first method
	generator.CallCounter = 0
	
	// Runtime overrides from environment variables
	generator.loadFromEnvironment()
	
	// Setup context for lifecycle management
	generator.ctx, generator.cancel = context.WithCancel(ctx)
	
	return generator, nil
}

// Start begins burst generation inside the service
func (g *{{.Name}}) Start() {
	g.wg.Add(1)
	go g.runBurstGeneration()
	log.Printf("Started burst load generator for {{.Service.Name}}: %d req/sec, duration=%v, interval=%v", 
		g.BurstSize, g.BurstDuration, g.BurstInterval)
}

// Stop gracefully shuts down the burst load generator
func (g *{{.Name}}) Stop() {
	log.Printf("Stopping burst load generator for {{.Service.Name}}")
	g.cancel()
	g.wg.Wait()
	log.Printf("Burst load generator for {{.Service.Name}} stopped")
}

// runBurstGeneration executes the burst pattern: generate -> wait -> repeat
func (g *{{.Name}}) runBurstGeneration() {
	defer g.wg.Done()
	
	burstCount := 0
	for {
		select {
		case <-g.ctx.Done():
			// Generator shutdown requested
			return
		default:
			burstCount++
			log.Printf("Starting burst period %d for {{.Service.Name}}", burstCount)
			
			// Execute one burst period
			g.executeBurstPeriod()
			
			// Wait interval between burst periods
			if g.BurstInterval > 0 {
				log.Printf("Burst interval for {{.Service.Name}}: %v", g.BurstInterval)
				select {
				case <-g.ctx.Done():
					return
				case <-time.After(g.BurstInterval):
					// Continue to next burst period
				}
			}
		}
	}
}

// executeBurstPeriod generates requests at the specified rate for the burst duration
func (g *{{.Name}}) executeBurstPeriod() {
	// Calculate interval between individual requests
	interval := time.Second / time.Duration(g.BurstSize)
	ticker := time.NewTicker(interval)
	defer ticker.Stop()
	
	// Burst duration context - this timeout is EXPECTED behavior
	burstCtx, cancel := context.WithTimeout(g.ctx, g.BurstDuration)
	defer cancel()
	
	requestCount := 0
	for {
		select {
		case <-burstCtx.Done():
			// Burst duration completed - this is EXPECTED and CORRECT
			log.Printf("Burst period completed for {{.Service.Name}}: %d requests sent", requestCount)
			return
		case <-ticker.C:
			// Make a real RPC call in background
			requestCount++
			go g.makeRealRPCCall(requestCount)
		}
	}
}

// makeRealRPCCall makes actual RPC calls using recorded real data
func (g *{{.Name}}) makeRealRPCCall(requestNum int) {
	// Create fresh context for each request
	ctx := context.Background()
	
	// Select method to call (from configured burst methods)
	methodToCall := g.BurstMethods[rand.Intn(len(g.BurstMethods))]
	
	// Get recorded call data for this method
	g.mu.RLock()
	var recordedCall *RecordedCall
	for i := len(g.RecordedCalls) - 1; i >= 0; i-- {
		if g.RecordedCalls[i].MethodName == methodToCall {
			recordedCall = &g.RecordedCalls[i]
			break
		}
	}
	g.mu.RUnlock()
	
	if recordedCall == nil {
		// No recorded data yet, skip this burst call
		log.Printf("Burst request #%d skipped: no recorded data for %s.%s", 
			requestNum, "{{.Service.Name}}", methodToCall)
		return
	}
	
	// Call the method with recorded real parameters
	switch methodToCall {
	{{range $f := .Service.Methods}}
	case "{{$f.Name}}":
		{{if $f.Arguments}}
		// Extract parameters from recorded call
		if len(recordedCall.Args) >= {{len $f.Arguments}} {
			{{range $i, $arg := $f.Arguments}}
			{{$arg.Name}}, _ := recordedCall.Args[{{$i}}].({{$arg.Type.Name}})
			{{end}}
			
			{{RetVars $f "err"}} := g.Client.{{$f.Name}}(ctx{{range $f.Arguments}}, {{.Name}}{{end}})
			
			if err != nil {
				log.Printf("Burst request #%d to {{$.Service.Name}}.{{$f.Name}} failed: %v", requestNum, err)
			} else {
				log.Printf("Burst request #%d to {{$.Service.Name}}.{{$f.Name}} succeeded", requestNum)
			}
		}
		{{else}}
		// Method has no parameters
		{{RetVars $f "err"}} := g.Client.{{$f.Name}}(ctx)
		
		if err != nil {
			log.Printf("Burst request #%d to {{$.Service.Name}}.{{$f.Name}} failed: %v", requestNum, err)
		} else {
			log.Printf("Burst request #%d to {{$.Service.Name}}.{{$f.Name}} succeeded", requestNum)
		}
		{{end}}
	{{end}}
	}
}

// loadFromEnvironment loads configuration from environment variables
func (g *{{.Name}}) loadFromEnvironment() {
	// Remove "_SERVICE" suffix and use just the service name
	serviceName := strings.ToUpper("{{.Service.Name}}")
	serviceName = strings.TrimSuffix(serviceName, "_SERVICE")
	
	// Burst size (requests per second)
	if envVal := os.Getenv(serviceName + "_BURST_SIZE"); envVal != "" {
		if val, err := strconv.Atoi(envVal); err == nil {
			g.BurstSize = val
		}
	}
	
	// Burst duration (how long to generate bursts)
	if envVal := os.Getenv(serviceName + "_BURST_DURATION"); envVal != "" {
		if val, err := time.ParseDuration(envVal); err == nil {
			g.BurstDuration = val
		}
	}
	
	// Burst interval (wait time between burst periods)
	if envVal := os.Getenv(serviceName + "_BURST_INTERVAL"); envVal != "" {
		if val, err := time.ParseDuration(envVal); err == nil {
			g.BurstInterval = val
		}
	}
	
	// Burst methods (which methods to call)
	if envVal := os.Getenv(serviceName + "_BURST_METHODS"); envVal != "" {
		methods := strings.Split(envVal, ",")
		validMethods := make([]string, 0)
		availableMethods := []string{ {{range $f := .Service.Methods}}"{{$f.Name}}", {{end}} }
		
		// Only include valid methods that exist in the service
		for _, method := range methods {
			method = strings.TrimSpace(method)
			for _, available := range availableMethods {
				if method == available {
					validMethods = append(validMethods, method)
					break
				}
			}
		}
		
		if len(validMethods) > 0 {
			g.BurstMethods = validMethods
		}
	}
}

// Wrapper methods that record real calls and forward to actual service
{{$service := .Service.Name -}}
{{$receiver := .Name -}}
{{ range $_, $f := .Service.Methods }}
func (client *{{$receiver}}) {{$f.Name -}} ({{ArgVarsAndTypes $f "ctx context.Context"}}) ({{RetVarsAndTypes $f "err error"}}) {
	// Increment global call counter and check if we should sample
	callNum := atomic.AddInt64(&globalCallCounter, 1)
	if callNum % 200 == 0 {
		// Sample this call - record the parameters
		client.recordCall("{{$f.Name}}", []interface{}{ {{range $i, $arg := $f.Arguments}}{{if gt $i 0}}, {{end}}{{$arg.Name}}{{end}} })
	}
	
	// Forward to the real service
	{{RetVars $f "err"}} = client.Client.{{$f.Name}}({{ArgVars $f "ctx"}})
	return
}
{{end}}

// recordCall stores real call parameters for later use in burst generation
func (client *{{$receiver}}) recordCall(methodName string, args []interface{}) {
	client.mu.Lock()
	defer client.mu.Unlock()
	
	// Add to recorded calls (keep only last 50 calls to prevent memory issues)
	call := RecordedCall{
		MethodName: methodName,
		Args:       args,
		Timestamp:  time.Now(),
	}
	
	client.RecordedCalls = append(client.RecordedCalls, call)
	if len(client.RecordedCalls) > 50 {
		client.RecordedCalls = client.RecordedCalls[1:] // Remove oldest
	}
	
	log.Printf("Recorded call #%d: %s.%s with %d parameters", 
		atomic.LoadInt64(&globalCallCounter), "{{.Service.Name}}", methodName, len(args))
}
`


