// usermention_service_sb_proc runs the usermention_service_sb_proc Golang process.
//
// usermention_service_sb_proc is auto-generated by Blueprint's goproc plugin (goproc/goprocgen/main.go.go)
//
// Usage:
//
//   go run main.go --user_cache_sb.dial_addr=value --user_db_sb.dial_addr=value --otelcol_sb.dial_addr=value --usermention_service_sb.grpc.bind_addr=value 
//
// usermention_service_sb_proc requires the following arguments are passed:
//
//   --user_cache_sb.dial_addr
//       Auto-generated by Blueprint IR node:
//       user_cache_sb.dial_addr = AddressConfig()
//
//   --user_db_sb.dial_addr
//       Auto-generated by Blueprint IR node:
//       user_db_sb.dial_addr = AddressConfig()
//
//   --otelcol_sb.dial_addr
//       Auto-generated by Blueprint IR node:
//       otelcol_sb.dial_addr = AddressConfig()
//
//   --usermention_service_sb.grpc.bind_addr
//       Auto-generated by Blueprint IR node:
//       usermention_service_sb.grpc.bind_addr = AddressConfig()
//
// usermention_service_sb_proc will instantiate the following IR nodes:
//   usermention_service_sb_proc.stdoutmetriccollector
//   usermention_service_sb_proc.logger
//   user_cache_sb.client
//   user_db_sb.client
//   usermention_service_sb
//   otelcol_sb.client
//   usermention_service_sb.server.ot
//   usermention_service_sb.grpc_server
package main

import (
	"context"
	"os"

	"log/slog"
)

func main() {
	slog.Info("Running usermention_service_sb_proc")
	n, err := New_usermention_service_sb_proc("usermention_service_sb_proc").Build(context.Background())
	if err != nil {
		slog.Error(err.Error())
		os.Exit(1)
	}
	n.Await()
	slog.Info("usermention_service_sb_proc exiting")
}