// Blueprint: Auto-generated by OpenTelemetry Plugin
package ot

import (
	"context"
	"strconv"
	"strings"
	"sync/atomic"

	"github.com/blueprint-uservices/blueprint/examples/dsb_sn/workflow/snnw"
	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.opentelemetry.io/otel/attribute"
	trace2 "go.opentelemetry.io/otel/sdk/trace"
	"go.opentelemetry.io/otel/trace"
)

type SocialGraphService_OTServerWrapperInterface interface {
	Follow(ctx context.Context, reqID int64, userID int64, followeeID int64, traceCtx string) error
	FollowWithUsername(ctx context.Context, reqID int64, userUsername string, followeeUsername string, traceCtx string) error
	GetFollowees(ctx context.Context, reqID int64, userID int64, traceCtx string) ([]int64, error)
	GetFollowers(ctx context.Context, reqID int64, userID int64, traceCtx string) ([]int64, error)
	InsertUser(ctx context.Context, reqID int64, userID int64, traceCtx string) error
	Unfollow(ctx context.Context, reqID int64, userID int64, followeeID int64, traceCtx string) error
	UnfollowWithUsername(ctx context.Context, reqID int64, userUsername string, followeeUsername string, traceCtx string) error
}

type SocialGraphService_OTServerWrapper struct {
	Service    snnw.SocialGraphService
	CollClient backend.Tracer
}

func New_SocialGraphService_OTServerWrapper(ctx context.Context, service snnw.SocialGraphService, coll_client backend.Tracer) (*SocialGraphService_OTServerWrapper, error) {
	handler := &SocialGraphService_OTServerWrapper{}
	handler.Service = service
	handler.CollClient = coll_client
	return handler, nil
}

func (handler *SocialGraphService_OTServerWrapper) Follow(ctx context.Context, reqID int64, userID int64, followeeID int64, traceCtx string) (err error) {
	// Sampling-aware fast path: compact "U:" carrier = head-unsampled upstream ->
	// skip JSON deserialize/baggage/span; restore remote ctx and call the service.
	if len(traceCtx) >= 50 && traceCtx[0:2] == "U:" {
		tid, _ := trace.TraceIDFromHex(traceCtx[2:34])
		sid, _ := trace.SpanIDFromHex(traceCtx[34:50])
		rsc := trace.NewSpanContext(trace.SpanContextConfig{TraceID: tid, SpanID: sid, Remote: true})
		ctx = trace.ContextWithRemoteSpanContext(ctx, rsc)
		err = handler.Service.Follow(ctx, reqID, userID, followeeID)
		return
	}
	var baggage map[string]string
	if traceCtx != "" {
		span_ctx_config, upstreamBaggage, _ := backend.GetSpanContext(traceCtx)
		span_ctx := trace.NewSpanContext(span_ctx_config)
		ctx = trace.ContextWithRemoteSpanContext(ctx, span_ctx)

		// Set baggage in context for span processor to read
		if upstreamBaggage != nil {
			baggage = upstreamBaggage
			ctx = backend.SetBaggageInContext(ctx, baggage)
		}
	}

	// Fanout ordinal: the caller stamped this span's child ordinal in baggage
	// ("__seq"). Set it on ctx BEFORE the server span starts so the bridge
	// processor's OnStart reads the correct seqNum (else it defaults to 0 and
	// CGPB HA / SB ordinals are never emitted).
	if baggage != nil {
		if sv, ok := baggage["__seq"]; ok {
			if n, e := strconv.Atoi(sv); e == nil {
				ctx = context.WithValue(ctx, "seqNum", n)
			}
		}
	}

	tp, _ := handler.CollClient.GetTracerProvider(ctx)
	tr := tp.Tracer("SocialGraphService")
	ctx, span := tr.Start(ctx, "SocialGraphServiceServer_Follow", trace.WithSpanKind(trace.SpanKindServer))
	defer span.End()

	// Extract new baggage from span attributes by casting to ReadWriteSpan
	if baggage == nil {
		baggage = make(map[string]string)
	}
	if rwSpan, ok := span.(trace2.ReadWriteSpan); ok {
		for _, attr := range rwSpan.Attributes() {
			if strings.HasPrefix(string(attr.Key), "__bag.") {
				key := strings.TrimPrefix(string(attr.Key), "__bag.")
				// Convert value to string for baggage based on attribute type
				switch attr.Value.Type() {
				case attribute.INT64:
					baggage[key] = strconv.FormatInt(attr.Value.AsInt64(), 10)
				case attribute.STRING:
					baggage[key] = attr.Value.AsString()
				default:
					baggage[key] = attr.Value.AsString()
				}
			} else if strings.HasPrefix(string(attr.Key), "__bagdel.") {
				key := strings.TrimPrefix(string(attr.Key), "__bagdel.")
				delete(baggage, key)
			}
		}
	}

	// Update context with merged baggage BEFORE calling the service
	if baggage != nil {
		ctx = backend.SetBaggageInContext(ctx, baggage)
	}

	childCount := atomic.Uint64{}
	ctx = context.WithValue(ctx, "childCount", &childCount)

	err = handler.Service.Follow(ctx, reqID, userID, followeeID)
	if err != nil {
		span.RecordError(err)
	}

	span.SetAttributes(attribute.Bool("hasChildren", int(childCount.Load()) > 0))

	return
}

func (handler *SocialGraphService_OTServerWrapper) FollowWithUsername(ctx context.Context, reqID int64, userUsername string, followeeUsername string, traceCtx string) (err error) {
	// Sampling-aware fast path: compact "U:" carrier = head-unsampled upstream ->
	// skip JSON deserialize/baggage/span; restore remote ctx and call the service.
	if len(traceCtx) >= 50 && traceCtx[0:2] == "U:" {
		tid, _ := trace.TraceIDFromHex(traceCtx[2:34])
		sid, _ := trace.SpanIDFromHex(traceCtx[34:50])
		rsc := trace.NewSpanContext(trace.SpanContextConfig{TraceID: tid, SpanID: sid, Remote: true})
		ctx = trace.ContextWithRemoteSpanContext(ctx, rsc)
		err = handler.Service.FollowWithUsername(ctx, reqID, userUsername, followeeUsername)
		return
	}
	var baggage map[string]string
	if traceCtx != "" {
		span_ctx_config, upstreamBaggage, _ := backend.GetSpanContext(traceCtx)
		span_ctx := trace.NewSpanContext(span_ctx_config)
		ctx = trace.ContextWithRemoteSpanContext(ctx, span_ctx)

		// Set baggage in context for span processor to read
		if upstreamBaggage != nil {
			baggage = upstreamBaggage
			ctx = backend.SetBaggageInContext(ctx, baggage)
		}
	}

	// Fanout ordinal: the caller stamped this span's child ordinal in baggage
	// ("__seq"). Set it on ctx BEFORE the server span starts so the bridge
	// processor's OnStart reads the correct seqNum (else it defaults to 0 and
	// CGPB HA / SB ordinals are never emitted).
	if baggage != nil {
		if sv, ok := baggage["__seq"]; ok {
			if n, e := strconv.Atoi(sv); e == nil {
				ctx = context.WithValue(ctx, "seqNum", n)
			}
		}
	}

	tp, _ := handler.CollClient.GetTracerProvider(ctx)
	tr := tp.Tracer("SocialGraphService")
	ctx, span := tr.Start(ctx, "SocialGraphServiceServer_FollowWithUsername", trace.WithSpanKind(trace.SpanKindServer))
	defer span.End()

	// Extract new baggage from span attributes by casting to ReadWriteSpan
	if baggage == nil {
		baggage = make(map[string]string)
	}
	if rwSpan, ok := span.(trace2.ReadWriteSpan); ok {
		for _, attr := range rwSpan.Attributes() {
			if strings.HasPrefix(string(attr.Key), "__bag.") {
				key := strings.TrimPrefix(string(attr.Key), "__bag.")
				// Convert value to string for baggage based on attribute type
				switch attr.Value.Type() {
				case attribute.INT64:
					baggage[key] = strconv.FormatInt(attr.Value.AsInt64(), 10)
				case attribute.STRING:
					baggage[key] = attr.Value.AsString()
				default:
					baggage[key] = attr.Value.AsString()
				}
			} else if strings.HasPrefix(string(attr.Key), "__bagdel.") {
				key := strings.TrimPrefix(string(attr.Key), "__bagdel.")
				delete(baggage, key)
			}
		}
	}

	// Update context with merged baggage BEFORE calling the service
	if baggage != nil {
		ctx = backend.SetBaggageInContext(ctx, baggage)
	}

	childCount := atomic.Uint64{}
	ctx = context.WithValue(ctx, "childCount", &childCount)

	err = handler.Service.FollowWithUsername(ctx, reqID, userUsername, followeeUsername)
	if err != nil {
		span.RecordError(err)
	}

	span.SetAttributes(attribute.Bool("hasChildren", int(childCount.Load()) > 0))

	return
}

func (handler *SocialGraphService_OTServerWrapper) GetFollowees(ctx context.Context, reqID int64, userID int64, traceCtx string) (ret0 []int64, err error) {
	// Sampling-aware fast path: compact "U:" carrier = head-unsampled upstream ->
	// skip JSON deserialize/baggage/span; restore remote ctx and call the service.
	if len(traceCtx) >= 50 && traceCtx[0:2] == "U:" {
		tid, _ := trace.TraceIDFromHex(traceCtx[2:34])
		sid, _ := trace.SpanIDFromHex(traceCtx[34:50])
		rsc := trace.NewSpanContext(trace.SpanContextConfig{TraceID: tid, SpanID: sid, Remote: true})
		ctx = trace.ContextWithRemoteSpanContext(ctx, rsc)
		ret0, err = handler.Service.GetFollowees(ctx, reqID, userID)
		return
	}
	var baggage map[string]string
	if traceCtx != "" {
		span_ctx_config, upstreamBaggage, _ := backend.GetSpanContext(traceCtx)
		span_ctx := trace.NewSpanContext(span_ctx_config)
		ctx = trace.ContextWithRemoteSpanContext(ctx, span_ctx)

		// Set baggage in context for span processor to read
		if upstreamBaggage != nil {
			baggage = upstreamBaggage
			ctx = backend.SetBaggageInContext(ctx, baggage)
		}
	}

	// Fanout ordinal: the caller stamped this span's child ordinal in baggage
	// ("__seq"). Set it on ctx BEFORE the server span starts so the bridge
	// processor's OnStart reads the correct seqNum (else it defaults to 0 and
	// CGPB HA / SB ordinals are never emitted).
	if baggage != nil {
		if sv, ok := baggage["__seq"]; ok {
			if n, e := strconv.Atoi(sv); e == nil {
				ctx = context.WithValue(ctx, "seqNum", n)
			}
		}
	}

	tp, _ := handler.CollClient.GetTracerProvider(ctx)
	tr := tp.Tracer("SocialGraphService")
	ctx, span := tr.Start(ctx, "SocialGraphServiceServer_GetFollowees", trace.WithSpanKind(trace.SpanKindServer))
	defer span.End()

	// Extract new baggage from span attributes by casting to ReadWriteSpan
	if baggage == nil {
		baggage = make(map[string]string)
	}
	if rwSpan, ok := span.(trace2.ReadWriteSpan); ok {
		for _, attr := range rwSpan.Attributes() {
			if strings.HasPrefix(string(attr.Key), "__bag.") {
				key := strings.TrimPrefix(string(attr.Key), "__bag.")
				// Convert value to string for baggage based on attribute type
				switch attr.Value.Type() {
				case attribute.INT64:
					baggage[key] = strconv.FormatInt(attr.Value.AsInt64(), 10)
				case attribute.STRING:
					baggage[key] = attr.Value.AsString()
				default:
					baggage[key] = attr.Value.AsString()
				}
			} else if strings.HasPrefix(string(attr.Key), "__bagdel.") {
				key := strings.TrimPrefix(string(attr.Key), "__bagdel.")
				delete(baggage, key)
			}
		}
	}

	// Update context with merged baggage BEFORE calling the service
	if baggage != nil {
		ctx = backend.SetBaggageInContext(ctx, baggage)
	}

	childCount := atomic.Uint64{}
	ctx = context.WithValue(ctx, "childCount", &childCount)

	ret0, err = handler.Service.GetFollowees(ctx, reqID, userID)
	if err != nil {
		span.RecordError(err)
	}

	span.SetAttributes(attribute.Bool("hasChildren", int(childCount.Load()) > 0))

	return
}

func (handler *SocialGraphService_OTServerWrapper) GetFollowers(ctx context.Context, reqID int64, userID int64, traceCtx string) (ret0 []int64, err error) {
	// Sampling-aware fast path: compact "U:" carrier = head-unsampled upstream ->
	// skip JSON deserialize/baggage/span; restore remote ctx and call the service.
	if len(traceCtx) >= 50 && traceCtx[0:2] == "U:" {
		tid, _ := trace.TraceIDFromHex(traceCtx[2:34])
		sid, _ := trace.SpanIDFromHex(traceCtx[34:50])
		rsc := trace.NewSpanContext(trace.SpanContextConfig{TraceID: tid, SpanID: sid, Remote: true})
		ctx = trace.ContextWithRemoteSpanContext(ctx, rsc)
		ret0, err = handler.Service.GetFollowers(ctx, reqID, userID)
		return
	}
	var baggage map[string]string
	if traceCtx != "" {
		span_ctx_config, upstreamBaggage, _ := backend.GetSpanContext(traceCtx)
		span_ctx := trace.NewSpanContext(span_ctx_config)
		ctx = trace.ContextWithRemoteSpanContext(ctx, span_ctx)

		// Set baggage in context for span processor to read
		if upstreamBaggage != nil {
			baggage = upstreamBaggage
			ctx = backend.SetBaggageInContext(ctx, baggage)
		}
	}

	// Fanout ordinal: the caller stamped this span's child ordinal in baggage
	// ("__seq"). Set it on ctx BEFORE the server span starts so the bridge
	// processor's OnStart reads the correct seqNum (else it defaults to 0 and
	// CGPB HA / SB ordinals are never emitted).
	if baggage != nil {
		if sv, ok := baggage["__seq"]; ok {
			if n, e := strconv.Atoi(sv); e == nil {
				ctx = context.WithValue(ctx, "seqNum", n)
			}
		}
	}

	tp, _ := handler.CollClient.GetTracerProvider(ctx)
	tr := tp.Tracer("SocialGraphService")
	ctx, span := tr.Start(ctx, "SocialGraphServiceServer_GetFollowers", trace.WithSpanKind(trace.SpanKindServer))
	defer span.End()

	// Extract new baggage from span attributes by casting to ReadWriteSpan
	if baggage == nil {
		baggage = make(map[string]string)
	}
	if rwSpan, ok := span.(trace2.ReadWriteSpan); ok {
		for _, attr := range rwSpan.Attributes() {
			if strings.HasPrefix(string(attr.Key), "__bag.") {
				key := strings.TrimPrefix(string(attr.Key), "__bag.")
				// Convert value to string for baggage based on attribute type
				switch attr.Value.Type() {
				case attribute.INT64:
					baggage[key] = strconv.FormatInt(attr.Value.AsInt64(), 10)
				case attribute.STRING:
					baggage[key] = attr.Value.AsString()
				default:
					baggage[key] = attr.Value.AsString()
				}
			} else if strings.HasPrefix(string(attr.Key), "__bagdel.") {
				key := strings.TrimPrefix(string(attr.Key), "__bagdel.")
				delete(baggage, key)
			}
		}
	}

	// Update context with merged baggage BEFORE calling the service
	if baggage != nil {
		ctx = backend.SetBaggageInContext(ctx, baggage)
	}

	childCount := atomic.Uint64{}
	ctx = context.WithValue(ctx, "childCount", &childCount)

	ret0, err = handler.Service.GetFollowers(ctx, reqID, userID)
	if err != nil {
		span.RecordError(err)
	}

	span.SetAttributes(attribute.Bool("hasChildren", int(childCount.Load()) > 0))

	return
}

func (handler *SocialGraphService_OTServerWrapper) InsertUser(ctx context.Context, reqID int64, userID int64, traceCtx string) (err error) {
	// Sampling-aware fast path: compact "U:" carrier = head-unsampled upstream ->
	// skip JSON deserialize/baggage/span; restore remote ctx and call the service.
	if len(traceCtx) >= 50 && traceCtx[0:2] == "U:" {
		tid, _ := trace.TraceIDFromHex(traceCtx[2:34])
		sid, _ := trace.SpanIDFromHex(traceCtx[34:50])
		rsc := trace.NewSpanContext(trace.SpanContextConfig{TraceID: tid, SpanID: sid, Remote: true})
		ctx = trace.ContextWithRemoteSpanContext(ctx, rsc)
		err = handler.Service.InsertUser(ctx, reqID, userID)
		return
	}
	var baggage map[string]string
	if traceCtx != "" {
		span_ctx_config, upstreamBaggage, _ := backend.GetSpanContext(traceCtx)
		span_ctx := trace.NewSpanContext(span_ctx_config)
		ctx = trace.ContextWithRemoteSpanContext(ctx, span_ctx)

		// Set baggage in context for span processor to read
		if upstreamBaggage != nil {
			baggage = upstreamBaggage
			ctx = backend.SetBaggageInContext(ctx, baggage)
		}
	}

	// Fanout ordinal: the caller stamped this span's child ordinal in baggage
	// ("__seq"). Set it on ctx BEFORE the server span starts so the bridge
	// processor's OnStart reads the correct seqNum (else it defaults to 0 and
	// CGPB HA / SB ordinals are never emitted).
	if baggage != nil {
		if sv, ok := baggage["__seq"]; ok {
			if n, e := strconv.Atoi(sv); e == nil {
				ctx = context.WithValue(ctx, "seqNum", n)
			}
		}
	}

	tp, _ := handler.CollClient.GetTracerProvider(ctx)
	tr := tp.Tracer("SocialGraphService")
	ctx, span := tr.Start(ctx, "SocialGraphServiceServer_InsertUser", trace.WithSpanKind(trace.SpanKindServer))
	defer span.End()

	// Extract new baggage from span attributes by casting to ReadWriteSpan
	if baggage == nil {
		baggage = make(map[string]string)
	}
	if rwSpan, ok := span.(trace2.ReadWriteSpan); ok {
		for _, attr := range rwSpan.Attributes() {
			if strings.HasPrefix(string(attr.Key), "__bag.") {
				key := strings.TrimPrefix(string(attr.Key), "__bag.")
				// Convert value to string for baggage based on attribute type
				switch attr.Value.Type() {
				case attribute.INT64:
					baggage[key] = strconv.FormatInt(attr.Value.AsInt64(), 10)
				case attribute.STRING:
					baggage[key] = attr.Value.AsString()
				default:
					baggage[key] = attr.Value.AsString()
				}
			} else if strings.HasPrefix(string(attr.Key), "__bagdel.") {
				key := strings.TrimPrefix(string(attr.Key), "__bagdel.")
				delete(baggage, key)
			}
		}
	}

	// Update context with merged baggage BEFORE calling the service
	if baggage != nil {
		ctx = backend.SetBaggageInContext(ctx, baggage)
	}

	childCount := atomic.Uint64{}
	ctx = context.WithValue(ctx, "childCount", &childCount)

	err = handler.Service.InsertUser(ctx, reqID, userID)
	if err != nil {
		span.RecordError(err)
	}

	span.SetAttributes(attribute.Bool("hasChildren", int(childCount.Load()) > 0))

	return
}

func (handler *SocialGraphService_OTServerWrapper) Unfollow(ctx context.Context, reqID int64, userID int64, followeeID int64, traceCtx string) (err error) {
	// Sampling-aware fast path: compact "U:" carrier = head-unsampled upstream ->
	// skip JSON deserialize/baggage/span; restore remote ctx and call the service.
	if len(traceCtx) >= 50 && traceCtx[0:2] == "U:" {
		tid, _ := trace.TraceIDFromHex(traceCtx[2:34])
		sid, _ := trace.SpanIDFromHex(traceCtx[34:50])
		rsc := trace.NewSpanContext(trace.SpanContextConfig{TraceID: tid, SpanID: sid, Remote: true})
		ctx = trace.ContextWithRemoteSpanContext(ctx, rsc)
		err = handler.Service.Unfollow(ctx, reqID, userID, followeeID)
		return
	}
	var baggage map[string]string
	if traceCtx != "" {
		span_ctx_config, upstreamBaggage, _ := backend.GetSpanContext(traceCtx)
		span_ctx := trace.NewSpanContext(span_ctx_config)
		ctx = trace.ContextWithRemoteSpanContext(ctx, span_ctx)

		// Set baggage in context for span processor to read
		if upstreamBaggage != nil {
			baggage = upstreamBaggage
			ctx = backend.SetBaggageInContext(ctx, baggage)
		}
	}

	// Fanout ordinal: the caller stamped this span's child ordinal in baggage
	// ("__seq"). Set it on ctx BEFORE the server span starts so the bridge
	// processor's OnStart reads the correct seqNum (else it defaults to 0 and
	// CGPB HA / SB ordinals are never emitted).
	if baggage != nil {
		if sv, ok := baggage["__seq"]; ok {
			if n, e := strconv.Atoi(sv); e == nil {
				ctx = context.WithValue(ctx, "seqNum", n)
			}
		}
	}

	tp, _ := handler.CollClient.GetTracerProvider(ctx)
	tr := tp.Tracer("SocialGraphService")
	ctx, span := tr.Start(ctx, "SocialGraphServiceServer_Unfollow", trace.WithSpanKind(trace.SpanKindServer))
	defer span.End()

	// Extract new baggage from span attributes by casting to ReadWriteSpan
	if baggage == nil {
		baggage = make(map[string]string)
	}
	if rwSpan, ok := span.(trace2.ReadWriteSpan); ok {
		for _, attr := range rwSpan.Attributes() {
			if strings.HasPrefix(string(attr.Key), "__bag.") {
				key := strings.TrimPrefix(string(attr.Key), "__bag.")
				// Convert value to string for baggage based on attribute type
				switch attr.Value.Type() {
				case attribute.INT64:
					baggage[key] = strconv.FormatInt(attr.Value.AsInt64(), 10)
				case attribute.STRING:
					baggage[key] = attr.Value.AsString()
				default:
					baggage[key] = attr.Value.AsString()
				}
			} else if strings.HasPrefix(string(attr.Key), "__bagdel.") {
				key := strings.TrimPrefix(string(attr.Key), "__bagdel.")
				delete(baggage, key)
			}
		}
	}

	// Update context with merged baggage BEFORE calling the service
	if baggage != nil {
		ctx = backend.SetBaggageInContext(ctx, baggage)
	}

	childCount := atomic.Uint64{}
	ctx = context.WithValue(ctx, "childCount", &childCount)

	err = handler.Service.Unfollow(ctx, reqID, userID, followeeID)
	if err != nil {
		span.RecordError(err)
	}

	span.SetAttributes(attribute.Bool("hasChildren", int(childCount.Load()) > 0))

	return
}

func (handler *SocialGraphService_OTServerWrapper) UnfollowWithUsername(ctx context.Context, reqID int64, userUsername string, followeeUsername string, traceCtx string) (err error) {
	// Sampling-aware fast path: compact "U:" carrier = head-unsampled upstream ->
	// skip JSON deserialize/baggage/span; restore remote ctx and call the service.
	if len(traceCtx) >= 50 && traceCtx[0:2] == "U:" {
		tid, _ := trace.TraceIDFromHex(traceCtx[2:34])
		sid, _ := trace.SpanIDFromHex(traceCtx[34:50])
		rsc := trace.NewSpanContext(trace.SpanContextConfig{TraceID: tid, SpanID: sid, Remote: true})
		ctx = trace.ContextWithRemoteSpanContext(ctx, rsc)
		err = handler.Service.UnfollowWithUsername(ctx, reqID, userUsername, followeeUsername)
		return
	}
	var baggage map[string]string
	if traceCtx != "" {
		span_ctx_config, upstreamBaggage, _ := backend.GetSpanContext(traceCtx)
		span_ctx := trace.NewSpanContext(span_ctx_config)
		ctx = trace.ContextWithRemoteSpanContext(ctx, span_ctx)

		// Set baggage in context for span processor to read
		if upstreamBaggage != nil {
			baggage = upstreamBaggage
			ctx = backend.SetBaggageInContext(ctx, baggage)
		}
	}

	// Fanout ordinal: the caller stamped this span's child ordinal in baggage
	// ("__seq"). Set it on ctx BEFORE the server span starts so the bridge
	// processor's OnStart reads the correct seqNum (else it defaults to 0 and
	// CGPB HA / SB ordinals are never emitted).
	if baggage != nil {
		if sv, ok := baggage["__seq"]; ok {
			if n, e := strconv.Atoi(sv); e == nil {
				ctx = context.WithValue(ctx, "seqNum", n)
			}
		}
	}

	tp, _ := handler.CollClient.GetTracerProvider(ctx)
	tr := tp.Tracer("SocialGraphService")
	ctx, span := tr.Start(ctx, "SocialGraphServiceServer_UnfollowWithUsername", trace.WithSpanKind(trace.SpanKindServer))
	defer span.End()

	// Extract new baggage from span attributes by casting to ReadWriteSpan
	if baggage == nil {
		baggage = make(map[string]string)
	}
	if rwSpan, ok := span.(trace2.ReadWriteSpan); ok {
		for _, attr := range rwSpan.Attributes() {
			if strings.HasPrefix(string(attr.Key), "__bag.") {
				key := strings.TrimPrefix(string(attr.Key), "__bag.")
				// Convert value to string for baggage based on attribute type
				switch attr.Value.Type() {
				case attribute.INT64:
					baggage[key] = strconv.FormatInt(attr.Value.AsInt64(), 10)
				case attribute.STRING:
					baggage[key] = attr.Value.AsString()
				default:
					baggage[key] = attr.Value.AsString()
				}
			} else if strings.HasPrefix(string(attr.Key), "__bagdel.") {
				key := strings.TrimPrefix(string(attr.Key), "__bagdel.")
				delete(baggage, key)
			}
		}
	}

	// Update context with merged baggage BEFORE calling the service
	if baggage != nil {
		ctx = backend.SetBaggageInContext(ctx, baggage)
	}

	childCount := atomic.Uint64{}
	ctx = context.WithValue(ctx, "childCount", &childCount)

	err = handler.Service.UnfollowWithUsername(ctx, reqID, userUsername, followeeUsername)
	if err != nil {
		span.RecordError(err)
	}

	span.SetAttributes(attribute.Bool("hasChildren", int(childCount.Load()) > 0))

	return
}
