// Blueprint: Auto-generated by OpenTelemetry Plugin
package ot

import (
	"context"
	"strconv"
	"strings"

	"github.com/blueprint-uservices/blueprint/examples/dsb_sn/workflow/snnw"
	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.opentelemetry.io/otel/attribute"
	trace2 "go.opentelemetry.io/otel/sdk/trace"
	"go.opentelemetry.io/otel/trace"
)

type TracePressureService_OTServerWrapperInterface interface {
	Spam(ctx context.Context, n int64, traceCtx string) (int64, error)
}

type TracePressureService_OTServerWrapper struct {
	Service    snnw.TracePressureService
	CollClient backend.Tracer
}

func New_TracePressureService_OTServerWrapper(ctx context.Context, service snnw.TracePressureService, coll_client backend.Tracer) (*TracePressureService_OTServerWrapper, error) {
	handler := &TracePressureService_OTServerWrapper{}
	handler.Service = service
	handler.CollClient = coll_client
	return handler, nil
}

func (handler *TracePressureService_OTServerWrapper) Spam(ctx context.Context, n int64, traceCtx string) (ret0 int64, err error) {
	// Sampling-aware fast path: a compact "U:<traceid><spanid>" carrier means the
	// trace was head-unsampled upstream. Skip the JSON deserialize, baggage, and
	// span start entirely; just restore the (unsampled) remote span context so
	// downstream hops stay consistent, then call the service.
	if len(traceCtx) >= 50 && traceCtx[0:2] == "U:" {
		tid, _ := trace.TraceIDFromHex(traceCtx[2:34])
		sid, _ := trace.SpanIDFromHex(traceCtx[34:50])
		rsc := trace.NewSpanContext(trace.SpanContextConfig{TraceID: tid, SpanID: sid, Remote: true})
		ctx = trace.ContextWithRemoteSpanContext(ctx, rsc)
		ret0, err = handler.Service.Spam(ctx, n)
		return
	}

	var baggage map[string]string
	if traceCtx != "" {
		span_ctx_config, upstreamBaggage, _ := backend.GetSpanContext(traceCtx)
		span_ctx := trace.NewSpanContext(span_ctx_config)
		ctx = trace.ContextWithRemoteSpanContext(ctx, span_ctx)

		// Set baggage in context for span processor to read
		if upstreamBaggage != nil {
			baggage = upstreamBaggage
			ctx = backend.SetBaggageInContext(ctx, baggage)
		}
	}

	// Fanout ordinal: the caller stamped this span's child ordinal in baggage
	// ("__seq"). Set it on ctx BEFORE the server span starts so the bridge
	// processor's OnStart reads the correct seqNum (else it defaults to 0 and
	// CGPB HA / SB ordinals are never emitted).
	if baggage != nil {
		if sv, ok := baggage["__seq"]; ok {
			if n, e := strconv.Atoi(sv); e == nil {
				ctx = context.WithValue(ctx, "seqNum", n)
			}
		}
	}

	tp, _ := handler.CollClient.GetTracerProvider(ctx)
	tr := tp.Tracer("TracePressureService")
	ctx, span := tr.Start(ctx, "TracePressureServiceServer_Spam", trace.WithSpanKind(trace.SpanKindServer))
	defer span.End()

	// Extract new baggage from span attributes by casting to ReadWriteSpan
	if baggage == nil {
		baggage = make(map[string]string)
	}
	if rwSpan, ok := span.(trace2.ReadWriteSpan); ok {
		for _, attr := range rwSpan.Attributes() {
			if strings.HasPrefix(string(attr.Key), "__bag.") {
				key := strings.TrimPrefix(string(attr.Key), "__bag.")
				// Convert value to string for baggage based on attribute type
				switch attr.Value.Type() {
				case attribute.INT64:
					baggage[key] = strconv.FormatInt(attr.Value.AsInt64(), 10)
				case attribute.STRING:
					baggage[key] = attr.Value.AsString()
				default:
					baggage[key] = attr.Value.AsString()
				}
			} else if strings.HasPrefix(string(attr.Key), "__bagdel.") {
				key := strings.TrimPrefix(string(attr.Key), "__bagdel.")
				delete(baggage, key)
			}
		}
	}

	// Update context with merged baggage BEFORE calling the service
	if baggage != nil {
		ctx = backend.SetBaggageInContext(ctx, baggage)
	}

	ret0, err = handler.Service.Spam(ctx, n)
	if err != nil {
		span.RecordError(err)
	}

	return
}
