apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_v5/k8s
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: user-service-v5-ctr
  name: user-service-v5-ctr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-service-v5-ctr
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_v5/k8s
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: user-service-v5-ctr
    spec:
      containers:
      - env:
        - name: OTELCOL_V5_DIAL_ADDR
          value: otelcol-v5-ctr:4317
        - name: SOCIALGRAPH_SERVICE_V5_GRPC_DIAL_ADDR
          value: socialgraph-service-v5-ctr:12345
        - name: USER_CACHE_V5_DIAL_ADDR
          value: user-cache-v5-ctr:6379
        - name: USER_DB_V5_DIAL_ADDR
          value: user-db-v5-ctr:27017
        - name: USER_SERVICE_V5_GRPC_BIND_ADDR
          value: 0.0.0.0:12345
        image: 10.10.1.1:30000/user-service-v5-ctr:latest
        name: user-service-v5-ctr
        ports:
        - containerPort: 12345
          protocol: TCP
        resources:
          requests:
            cpu: 3000m
      hostname: user-service-v5-ctr
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: node-8
