// post_storage_service_v2_proc runs the post_storage_service_v2_proc Golang process.
//
// post_storage_service_v2_proc is auto-generated by Blueprint's goproc plugin (goproc/goprocgen/main.go.go)
//
// Usage:
//
//   go run main.go --post_cache_v2.dial_addr=value --post_db_v2.dial_addr=value --otelcol_v2.dial_addr=value --post_storage_service_v2.grpc.bind_addr=value 
//
// post_storage_service_v2_proc requires the following arguments are passed:
//
//   --post_cache_v2.dial_addr
//       Auto-generated by Blueprint IR node:
//       post_cache_v2.dial_addr = AddressConfig()
//
//   --post_db_v2.dial_addr
//       Auto-generated by Blueprint IR node:
//       post_db_v2.dial_addr = AddressConfig()
//
//   --otelcol_v2.dial_addr
//       Auto-generated by Blueprint IR node:
//       otelcol_v2.dial_addr = AddressConfig()
//
//   --post_storage_service_v2.grpc.bind_addr
//       Auto-generated by Blueprint IR node:
//       post_storage_service_v2.grpc.bind_addr = AddressConfig()
//
// post_storage_service_v2_proc will instantiate the following IR nodes:
//   post_storage_service_v2_proc.stdoutmetriccollector
//   post_storage_service_v2_proc.logger
//   post_cache_v2.client
//   post_db_v2.client
//   post_storage_service_v2
//   otelcol_v2.client
//   post_storage_service_v2.server.ot
//   post_storage_service_v2.grpc_server
package main

import (
	"context"
	"os"

	"log/slog"
)

func main() {
	slog.Info("Running post_storage_service_v2_proc")
	n, err := New_post_storage_service_v2_proc("post_storage_service_v2_proc").Build(context.Background())
	if err != nil {
		slog.Error(err.Error())
		os.Exit(1)
	}
	n.Await()
	slog.Info("post_storage_service_v2_proc exiting")
}