// usertimeline_service_v2_proc runs the usertimeline_service_v2_proc Golang process.
//
// usertimeline_service_v2_proc is auto-generated by Blueprint's goproc plugin (goproc/goprocgen/main.go.go)
//
// Usage:
//
//   go run main.go --usertimeline_cache_v2.dial_addr=value --usertimeline_db_v2.dial_addr=value --post_storage_service_v2.grpc.dial_addr=value --otelcol_v2.dial_addr=value --usertimeline_service_v2.grpc.bind_addr=value 
//
// usertimeline_service_v2_proc requires the following arguments are passed:
//
//   --usertimeline_cache_v2.dial_addr
//       Auto-generated by Blueprint IR node:
//       usertimeline_cache_v2.dial_addr = AddressConfig()
//
//   --usertimeline_db_v2.dial_addr
//       Auto-generated by Blueprint IR node:
//       usertimeline_db_v2.dial_addr = AddressConfig()
//
//   --post_storage_service_v2.grpc.dial_addr
//       Auto-generated by Blueprint IR node:
//       post_storage_service_v2.grpc.dial_addr = AddressConfig()
//
//   --otelcol_v2.dial_addr
//       Auto-generated by Blueprint IR node:
//       otelcol_v2.dial_addr = AddressConfig()
//
//   --usertimeline_service_v2.grpc.bind_addr
//       Auto-generated by Blueprint IR node:
//       usertimeline_service_v2.grpc.bind_addr = AddressConfig()
//
// usertimeline_service_v2_proc will instantiate the following IR nodes:
//   usertimeline_service_v2_proc.stdoutmetriccollector
//   usertimeline_service_v2_proc.logger
//   usertimeline_cache_v2.client
//   usertimeline_db_v2.client
//   post_storage_service_v2.grpc_client
//   otelcol_v2.client
//   post_storage_service_v2.client.ot
//   post_storage_service_v2.client.retrier
//   post_storage_service_v2.client
//   usertimeline_service_v2
//   usertimeline_service_v2.server.ot
//   usertimeline_service_v2.grpc_server
package main

import (
	"context"
	"os"

	"log/slog"
)

func main() {
	slog.Info("Running usertimeline_service_v2_proc")
	n, err := New_usertimeline_service_v2_proc("usertimeline_service_v2_proc").Build(context.Background())
	if err != nil {
		slog.Error(err.Error())
		os.Exit(1)
	}
	n.Await()
	slog.Info("usertimeline_service_v2_proc exiting")
}