// Package main is auto-generated by gogen/namespacebuilder.go
//
// It provides funcs for instantiating the usertimeline_service_v2_proc namespace.
//
// To instantiate the usertimeline_service_v2_proc namespace, first call [New_usertimeline_service_v2_proc] and then either call 
// [Build] or [BuildWithParent].
// 
// See [golang.NamespaceBuilder] docs for more information about the behavior of [Build]
package main

import (
	"github.com/blueprint-uservices/blueprint/runtime/plugins/golang"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/opentelemetry"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/slogger"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/redis"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/otelcol"
	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"github.com/blueprint-uservices/blueprint/examples/dsb_sn/workflow/socialnetwork"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/mongodb"
	"blueprint/goproc/usertimeline_service_v2_proc/grpc"
	"blueprint/goproc/usertimeline_service_v2_proc/ot"
	"blueprint/goproc/usertimeline_service_v2_proc/retries"
)

// Initializes the usertimeline_service_v2_proc namespace by defining all of the nodes that run
// within the namespace.
//
// [Build] or [BuildWithParent] must be called on the return value of this func
// to actually build and run the nodes in the namespace.
func New_usertimeline_service_v2_proc(name string) *golang.NamespaceBuilder {
	b := golang.NewNamespaceBuilder(name)
	set_usertimeline_service_v2_proc_Args(b)
	set_usertimeline_service_v2_proc_Instances(b)
	set_usertimeline_service_v2_proc_Definitions(b)
	return b
}

// usertimeline_service_v2_proc requires that its arguments are either:
//  - explicitly set with [golang.NamespaceBuilder.Set]
//  - passed on the command line (if built using [golang.NamespaceBuilder.Build])
//  - are defined in parent (if built using [golang.NamespaceBuilder.BuildWithParent])
//
// The following arguments will be eagerly checked and building the namespace
// will fail if they haven't been provided:
//   otelcol_v2.dial_addr
//   post_storage_service_v2.grpc.dial_addr
//   usertimeline_cache_v2.dial_addr
//   usertimeline_db_v2.dial_addr
//   usertimeline_service_v2.grpc.bind_addr
//
// The following arguments are optional and a failure will only occur if the client
// tries to build a node that needs the argument to be set
func set_usertimeline_service_v2_proc_Args(b *golang.NamespaceBuilder) {
	b.Required("otelcol_v2.dial_addr", "Argument generated by Blueprint IR: otelcol_v2.dial_addr = AddressConfig()")
	b.Required("post_storage_service_v2.grpc.dial_addr", "Argument generated by Blueprint IR: post_storage_service_v2.grpc.dial_addr = AddressConfig()")
	b.Required("usertimeline_cache_v2.dial_addr", "Argument generated by Blueprint IR: usertimeline_cache_v2.dial_addr = AddressConfig()")
	b.Required("usertimeline_db_v2.dial_addr", "Argument generated by Blueprint IR: usertimeline_db_v2.dial_addr = AddressConfig()")
	b.Required("usertimeline_service_v2.grpc.bind_addr", "Argument generated by Blueprint IR: usertimeline_service_v2.grpc.bind_addr = AddressConfig()")
}

// When the usertimeline_service_v2_proc namespace is built it will automatically instantiate
// the following nodes:
//   usertimeline_service_v2_proc.stdoutmetriccollector
//   usertimeline_service_v2_proc.logger
//   usertimeline_cache_v2.client
//   usertimeline_db_v2.client
//   post_storage_service_v2.grpc_client
//   otelcol_v2.client
//   post_storage_service_v2.client.ot
//   post_storage_service_v2.client.retrier
//   post_storage_service_v2.client
//   usertimeline_service_v2
//   usertimeline_service_v2.server.ot
//   usertimeline_service_v2.grpc_server
func set_usertimeline_service_v2_proc_Instances(b *golang.NamespaceBuilder) {
	b.Instantiate("usertimeline_service_v2_proc.stdoutmetriccollector")
	b.Instantiate("usertimeline_service_v2_proc.logger")
	b.Instantiate("usertimeline_cache_v2.client")
	b.Instantiate("usertimeline_db_v2.client")
	b.Instantiate("post_storage_service_v2.grpc_client")
	b.Instantiate("otelcol_v2.client")
	b.Instantiate("post_storage_service_v2.client.ot")
	b.Instantiate("post_storage_service_v2.client.retrier")
	b.Instantiate("post_storage_service_v2.client")
	b.Instantiate("usertimeline_service_v2")
	b.Instantiate("usertimeline_service_v2.server.ot")
	b.Instantiate("usertimeline_service_v2.grpc_server")
}

// The usertimeline_service_v2_proc namespace contains definitions for instantiating
// the following nodes:
//   otelcol_v2.client
//   post_storage_service_v2.client
//   post_storage_service_v2.client.ot
//   post_storage_service_v2.client.retrier
//   post_storage_service_v2.grpc_client
//   usertimeline_cache_v2.client
//   usertimeline_db_v2.client
//   usertimeline_service_v2
//   usertimeline_service_v2.grpc_server
//   usertimeline_service_v2.server.ot
//   usertimeline_service_v2_proc.logger
//   usertimeline_service_v2_proc.stdoutmetriccollector
func set_usertimeline_service_v2_proc_Definitions(b *golang.NamespaceBuilder) {
	b.Define("otelcol_v2.client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var addr string
		if err := n.Get("otelcol_v2.dial_addr", &addr); err != nil {
			return nil, err
		}
		
		return otelcol.NewOTCollectorTracer(n.Context(), addr, "8080")
	})
	
	b.Define("post_storage_service_v2.client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin workflow/ir_workflowservice.go
		var client socialnetwork.PostStorageService
		err := n.Get("post_storage_service_v2.client.retrier", &client)
		return client, err
	})
	
	b.Define("post_storage_service_v2.client.ot", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var client ot.PostStorageService_OTServerWrapperInterface
		if err := n.Get("post_storage_service_v2.grpc_client", &client); err != nil {
			return nil, err
		}
		
		var coll_client backend.Tracer
		if err := n.Get("otelcol_v2.client", &coll_client); err != nil {
			return nil, err
		}
		
		return ot.New_PostStorageService_OTClientWrapper(n.Context(), client, coll_client)
	})
	
	b.Define("post_storage_service_v2.client.retrier", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var client ot.PostStorageService_OTClientWrapperInterface
		if err := n.Get("post_storage_service_v2.client.ot", &client); err != nil {
			return nil, err
		}
		
		return retries.New_PostStorageService_RetrierClient(n.Context(), client)
	})
	
	b.Define("post_storage_service_v2.grpc_client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var addr string
		if err := n.Get("post_storage_service_v2.grpc.dial_addr", &addr); err != nil {
			return nil, err
		}
		
		return grpc.New_PostStorageService_GRPCClient(n.Context(), addr)
	})
	
	b.Define("usertimeline_cache_v2.client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var addr string
		if err := n.Get("usertimeline_cache_v2.dial_addr", &addr); err != nil {
			return nil, err
		}
		
		return redis.NewRedisCacheClient(n.Context(), addr)
	})
	
	b.Define("usertimeline_db_v2.client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var addr string
		if err := n.Get("usertimeline_db_v2.dial_addr", &addr); err != nil {
			return nil, err
		}
		
		return mongodb.NewMongoDB(n.Context(), addr)
	})
	
	b.Define("usertimeline_service_v2", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var userTimelineCache backend.Cache
		if err := n.Get("usertimeline_cache_v2.client", &userTimelineCache); err != nil {
			return nil, err
		}
		
		var userTimelineDB backend.NoSQLDatabase
		if err := n.Get("usertimeline_db_v2.client", &userTimelineDB); err != nil {
			return nil, err
		}
		
		var postStorageService socialnetwork.PostStorageService
		if err := n.Get("post_storage_service_v2.client", &postStorageService); err != nil {
			return nil, err
		}
		
		return socialnetwork.NewUserTimelineServiceImpl(n.Context(), userTimelineCache, userTimelineDB, postStorageService)
	})
	
	b.Define("usertimeline_service_v2.grpc_server", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var service ot.UserTimelineService_OTServerWrapperInterface
		if err := n.Get("usertimeline_service_v2.server.ot", &service); err != nil {
			return nil, err
		}
		
		var serverAddr string
		if err := n.Get("usertimeline_service_v2.grpc.bind_addr", &serverAddr); err != nil {
			return nil, err
		}
		
		return grpc.New_UserTimelineService_GRPCServerHandler(n.Context(), service, serverAddr)
	})
	
	b.Define("usertimeline_service_v2.server.ot", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var service socialnetwork.UserTimelineService
		if err := n.Get("usertimeline_service_v2", &service); err != nil {
			return nil, err
		}
		
		var otCollectorClient backend.Tracer
		if err := n.Get("otelcol_v2.client", &otCollectorClient); err != nil {
			return nil, err
		}
		
		return ot.New_UserTimelineService_OTServerWrapper(n.Context(), service, otCollectorClient)
	})
	
	b.Define("usertimeline_service_v2_proc.logger", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		return slogger.NewSLogger(n.Context())
	})
	
	b.Define("usertimeline_service_v2_proc.stdoutmetriccollector", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		return opentelemetry.NewStdoutMetricCollector(n.Context())
	})
	
}
