// userid_service_v_proc runs the userid_service_v_proc Golang process.
//
// userid_service_v_proc is auto-generated by Blueprint's goproc plugin (goproc/goprocgen/main.go.go)
//
// Usage:
//
//   go run main.go --user_cache_v.dial_addr=value --user_db_v.dial_addr=value --otelcol_v.dial_addr=value --userid_service_v.grpc.bind_addr=value 
//
// userid_service_v_proc requires the following arguments are passed:
//
//   --user_cache_v.dial_addr
//       Auto-generated by Blueprint IR node:
//       user_cache_v.dial_addr = AddressConfig()
//
//   --user_db_v.dial_addr
//       Auto-generated by Blueprint IR node:
//       user_db_v.dial_addr = AddressConfig()
//
//   --otelcol_v.dial_addr
//       Auto-generated by Blueprint IR node:
//       otelcol_v.dial_addr = AddressConfig()
//
//   --userid_service_v.grpc.bind_addr
//       Auto-generated by Blueprint IR node:
//       userid_service_v.grpc.bind_addr = AddressConfig()
//
// userid_service_v_proc will instantiate the following IR nodes:
//   userid_service_v_proc.stdoutmetriccollector
//   userid_service_v_proc.logger
//   user_cache_v.client
//   user_db_v.client
//   userid_service_v
//   otelcol_v.client
//   userid_service_v.server.ot
//   userid_service_v.grpc_server
package main

import (
	"context"
	"os"

	"log/slog"
)

func main() {
	slog.Info("Running userid_service_v_proc")
	n, err := New_userid_service_v_proc("userid_service_v_proc").Build(context.Background())
	if err != nil {
		slog.Error(err.Error())
		os.Exit(1)
	}
	n.Await()
	slog.Info("userid_service_v_proc exiting")
}