exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: ${JAEGER_CGPB_ESREV2C6_OTLP_DIAL_ADDR}
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_elapsed_time: 0
      max_interval: 30s
    sending_queue:
      enabled: true
      num_consumers: 10
      queue_size: 1000
    tls:
      insecure: true
processors:
  batch: {}
receivers:
  configdiscovery:
    config_map:
      cpd: 6
    endpoint: :8080
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
  otlp/highprio:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        include_metadata: true
      http:
        endpoint: 0.0.0.0:4318
        include_metadata: true
service:
  extensions: []
  pipelines:
    logs/configdiscovery:
      exporters:
      - debug
      processors: []
      receivers:
      - configdiscovery
    traces:
      exporters:
      - otlp
      processors:
      - batch
      receivers:
      - otlp
  telemetry:
    logs:
      level: DEBUG
