receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  # keep Zipkin as an exporter
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
  
  # Add Jaeger as an alternative
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      # Use one or more exporters
      exporters: [zipkin, jaeger, logging]