apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_sb4/k8s
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: social-cache-sb4-ctr
  name: social-cache-sb4-ctr
spec:
  ports:
  - name: '12358'
    port: 12358
    targetPort: 6379
  - name: '6379'
    port: 6379
    targetPort: 6379
  selector:
    io.kompose.service: social-cache-sb4-ctr
