// media_service_v5_proc runs the media_service_v5_proc Golang process.
//
// media_service_v5_proc is auto-generated by Blueprint's goproc plugin (goproc/goprocgen/main.go.go)
//
// Usage:
//
//   go run main.go --otelcol_v5.dial_addr=value --media_service_v5.grpc.bind_addr=value 
//
// media_service_v5_proc requires the following arguments are passed:
//
//   --otelcol_v5.dial_addr
//       Auto-generated by Blueprint IR node:
//       otelcol_v5.dial_addr = AddressConfig()
//
//   --media_service_v5.grpc.bind_addr
//       Auto-generated by Blueprint IR node:
//       media_service_v5.grpc.bind_addr = AddressConfig()
//
// media_service_v5_proc will instantiate the following IR nodes:
//   media_service_v5_proc.stdoutmetriccollector
//   media_service_v5_proc.logger
//   media_service_v5
//   otelcol_v5.client
//   media_service_v5.server.ot
//   media_service_v5.grpc_server
package main

import (
	"context"
	"os"

	"log/slog"
)

func main() {
	slog.Info("Running media_service_v5_proc")
	n, err := New_media_service_v5_proc("media_service_v5_proc").Build(context.Background())
	if err != nil {
		slog.Error(err.Error())
		os.Exit(1)
	}
	n.Await()
	slog.Info("media_service_v5_proc exiting")
}