// This file is auto-generated by the Blueprint clientpool plugin
package pool

import (
	"context"
	"fmt"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/clientpool"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/golang"
	"github.com/blueprint-uservices/blueprint/examples/dsb_sn/workflow/socialnetwork"
)

type ComposePostService_ClientPool struct {
	clients *clientpool.ClientPool[socialnetwork.ComposePostService]
}

func New_ComposePostService_Pool(parent *golang.Namespace) *ComposePostService_ClientPool {
	i := 0
	createClient := func() (socialnetwork.ComposePostService, error) {
		clientName := fmt.Sprintf("composepost_service_nt2.clientpool.%v", i)
		n, err := New_ComposePostService_PoolClient(clientName).BuildWithParent(parent)
		if err != nil {
			return nil, err
		}
		i++
		var client socialnetwork.ComposePostService
		err = n.Get("composepost_service_nt2.grpc_client", &client)
		return client, err
	}
	clients := clientpool.NewClientPool(10, createClient)
	return &ComposePostService_ClientPool{clients: clients}
}


func (pool *ComposePostService_ClientPool) ComposePost(ctx context.Context, reqID int64, username string, userID int64, text string, mediaIDs []int64, mediaTypes []string, postType int64) (ret0 int64, ret1 []int64, err error) {
	client, err := pool.clients.Pop(ctx)
	if err != nil {
		return
	}
	defer pool.clients.Push(client)
	return client.ComposePost(ctx, reqID, username, userID, text, mediaIDs, mediaTypes, postType)
}



