// This file is auto-generated by the Blueprint clientpool plugin
package pool

import (
	"context"
	"fmt"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/clientpool"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/golang"
	"github.com/blueprint-uservices/blueprint/examples/dsb_sn/workflow/socialnetwork"
)

type MediaService_ClientPool struct {
	clients *clientpool.ClientPool[socialnetwork.MediaService]
}

func New_MediaService_Pool(parent *golang.Namespace) *MediaService_ClientPool {
	i := 0
	createClient := func() (socialnetwork.MediaService, error) {
		clientName := fmt.Sprintf("media_service_nt2.clientpool.%v", i)
		n, err := New_MediaService_PoolClient(clientName).BuildWithParent(parent)
		if err != nil {
			return nil, err
		}
		i++
		var client socialnetwork.MediaService
		err = n.Get("media_service_nt2.grpc_client", &client)
		return client, err
	}
	clients := clientpool.NewClientPool(10, createClient)
	return &MediaService_ClientPool{clients: clients}
}


func (pool *MediaService_ClientPool) ComposeMedia(ctx context.Context, reqID int64, mediaTypes []string, mediaIds []int64) (ret0 []socialnetwork.Media, err error) {
	client, err := pool.clients.Pop(ctx)
	if err != nil {
		return
	}
	defer pool.clients.Push(client)
	return client.ComposeMedia(ctx, reqID, mediaTypes, mediaIds)
}



