// This file is auto-generated by the Blueprint clientpool plugin
package pool

import (
	"context"
	"fmt"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/clientpool"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/golang"
	"github.com/blueprint-uservices/blueprint/examples/dsb_sn/workflow/socialnetwork"
)

type UserMentionService_ClientPool struct {
	clients *clientpool.ClientPool[socialnetwork.UserMentionService]
}

func New_UserMentionService_Pool(parent *golang.Namespace) *UserMentionService_ClientPool {
	i := 0
	createClient := func() (socialnetwork.UserMentionService, error) {
		clientName := fmt.Sprintf("usermention_service_nt2.clientpool.%v", i)
		n, err := New_UserMentionService_PoolClient(clientName).BuildWithParent(parent)
		if err != nil {
			return nil, err
		}
		i++
		var client socialnetwork.UserMentionService
		err = n.Get("usermention_service_nt2.grpc_client", &client)
		return client, err
	}
	clients := clientpool.NewClientPool(10, createClient)
	return &UserMentionService_ClientPool{clients: clients}
}


func (pool *UserMentionService_ClientPool) ComposeUserMentions(ctx context.Context, reqID int64, usernames []string) (ret0 []socialnetwork.UserMention, err error) {
	client, err := pool.clients.Pop(ctx)
	if err != nil {
		return
	}
	defer pool.clients.Push(client)
	return client.ComposeUserMentions(ctx, reqID, usernames)
}



