// Blueprint: Auto-generated by Retries Plugin
package retries

import (
	"context"
	"blueprint/goproc/composepost_service_sb4_proc/ot"
)

type UserTimelineService_RetrierClient struct {
	Client ot.UserTimelineService_OTClientWrapperInterface
	MaxTries int
}

func New_UserTimelineService_RetrierClient (ctx context.Context, client ot.UserTimelineService_OTClientWrapperInterface) (*UserTimelineService_RetrierClient, error) {
	handler := &UserTimelineService_RetrierClient{}
	handler.Client = client
	handler.MaxTries = 3
	return handler, nil
}


func (client *UserTimelineService_RetrierClient) ReadUserTimeline(ctx context.Context, reqID int64, userID int64, start int64, stop int64) (ret0 []int64, err error) {
	for i := 0; i < client.MaxTries; i++ {
		ret0, err = client.Client.ReadUserTimeline(ctx, reqID, userID, start, stop)
		if err == nil {
			return
		}
	}
	return
}

func (client *UserTimelineService_RetrierClient) WriteUserTimeline(ctx context.Context, reqID int64, postID int64, userID int64, timestamp int64) (err error) {
	for i := 0; i < client.MaxTries; i++ {
		err = client.Client.WriteUserTimeline(ctx, reqID, postID, userID, timestamp)
		if err == nil {
			return
		}
	}
	return
}

