// media_service_nt4_proc runs the media_service_nt4_proc Golang process.
//
// media_service_nt4_proc is auto-generated by Blueprint's goproc plugin (goproc/goprocgen/main.go.go)
//
// Usage:
//
//   go run main.go --media_service_nt4.grpc.bind_addr=value 
//
// media_service_nt4_proc requires the following arguments are passed:
//
//   --media_service_nt4.grpc.bind_addr
//       Auto-generated by Blueprint IR node:
//       media_service_nt4.grpc.bind_addr = AddressConfig()
//
// media_service_nt4_proc will instantiate the following IR nodes:
//   media_service_nt4_proc.stdoutmetriccollector
//   media_service_nt4_proc.logger
//   media_service_nt4
//   media_service_nt4.grpc_server
package main

import (
	"context"
	"os"

	"log/slog"
)

func main() {
	slog.Info("Running media_service_nt4_proc")
	n, err := New_media_service_nt4_proc("media_service_nt4_proc").Build(context.Background())
	if err != nil {
		slog.Error(err.Error())
		os.Exit(1)
	}
	n.Await()
	slog.Info("media_service_nt4_proc exiting")
}