// Blueprint: Auto-generated by OpenTelemetry Plugin
package ot

import (
	"context"
	"strconv"
	"strings"
	"sync/atomic"

	"github.com/blueprint-uservices/blueprint/examples/dsb_sn/workflow/snnw"
	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"go.opentelemetry.io/otel/attribute"
	trace2 "go.opentelemetry.io/otel/sdk/trace"
	"go.opentelemetry.io/otel/trace"
)

type UrlShortenService_OTClientWrapperInterface interface {
	ComposeUrls(ctx context.Context, reqID int64, urls []string) ([]snnw.URL, error)
	GetExtendedUrls(ctx context.Context, reqID int64, shortenedUrls []string) ([]string, error)
}

type UrlShortenService_OTClientWrapper struct {
	Client     UrlShortenService_OTServerWrapperInterface
	CollClient backend.Tracer
}

func New_UrlShortenService_OTClientWrapper(ctx context.Context, client UrlShortenService_OTServerWrapperInterface, coll_client backend.Tracer) (*UrlShortenService_OTClientWrapper, error) {
	handler := &UrlShortenService_OTClientWrapper{}
	handler.Client = client
	handler.CollClient = coll_client
	return handler, nil
}

func (handler *UrlShortenService_OTClientWrapper) ComposeUrls(ctx context.Context, reqID int64, urls []string) (ret0 []snnw.URL, err error) {
	// Sampling-aware fast path: unsampled parent -> skip all per-request work
	// (baggage/critpath/span/JSON); forward only a compact "U:" carrier so the
	// trace stays consistent. At ratio>=1 nothing is unsampled -> unchanged.
	if psc := trace.SpanContextFromContext(ctx); psc.IsValid() && !psc.IsSampled() {
		ret0, err = handler.Client.ComposeUrls(ctx, reqID, urls, "U:"+psc.TraceID().String()+psc.SpanID().String())
		return
	}
	// Get baggage from context and create a copy to avoid mutating shared state
	upstreamBaggage := backend.GetBaggageFromContext(ctx)
	baggage := make(map[string]string)
	if upstreamBaggage != nil {
		for k, v := range upstreamBaggage {
			baggage[k] = v
		}
	}

	tp, _ := handler.CollClient.GetTracerProvider(ctx)
	tr := tp.Tracer("UrlShortenService_OTServerWrapperInterface")

	childCountPtr := ctx.Value("childCount").(*atomic.Uint64)
	ctx = context.WithValue(ctx, "seqNum", int(childCountPtr.Add(1)))

	ctx, span := tr.Start(ctx, "UrlShortenServiceClient_ComposeUrls", trace.WithSpanKind(trace.SpanKindClient))

	defer span.End()

	// Extract baggage from span attributes by casting to ReadWriteSpan
	if rwSpan, ok := span.(trace2.ReadWriteSpan); ok {
		for _, attr := range rwSpan.Attributes() {
			if strings.HasPrefix(string(attr.Key), "__bag.") {
				key := strings.TrimPrefix(string(attr.Key), "__bag.")
				// Convert value to string for baggage based on attribute type
				switch attr.Value.Type() {
				case attribute.INT64:
					baggage[key] = strconv.FormatInt(attr.Value.AsInt64(), 10)
				case attribute.STRING:
					baggage[key] = attr.Value.AsString()
				default:
					baggage[key] = attr.Value.AsString()
				}
			} else if strings.HasPrefix(string(attr.Key), "__bagdel.") {
				key := strings.TrimPrefix(string(attr.Key), "__bagdel.")
				delete(baggage, key)
			}
		}
	}

	// Combine trace context with baggage
	trace_ctx, _ := span.SpanContext().MarshalJSON()
	trace_ctx_with_baggage, _ := backend.AddBaggageToTraceContext(string(trace_ctx), baggage)

	ret0, err = handler.Client.ComposeUrls(ctx, reqID, urls, trace_ctx_with_baggage)
	if err != nil {
		span.RecordError(err)
	}

	return
}

func (handler *UrlShortenService_OTClientWrapper) GetExtendedUrls(ctx context.Context, reqID int64, shortenedUrls []string) (ret0 []string, err error) {
	// Sampling-aware fast path: unsampled parent -> skip all per-request work
	// (baggage/critpath/span/JSON); forward only a compact "U:" carrier so the
	// trace stays consistent. At ratio>=1 nothing is unsampled -> unchanged.
	if psc := trace.SpanContextFromContext(ctx); psc.IsValid() && !psc.IsSampled() {
		ret0, err = handler.Client.GetExtendedUrls(ctx, reqID, shortenedUrls, "U:"+psc.TraceID().String()+psc.SpanID().String())
		return
	}
	// Get baggage from context and create a copy to avoid mutating shared state
	upstreamBaggage := backend.GetBaggageFromContext(ctx)
	baggage := make(map[string]string)
	if upstreamBaggage != nil {
		for k, v := range upstreamBaggage {
			baggage[k] = v
		}
	}

	tp, _ := handler.CollClient.GetTracerProvider(ctx)
	tr := tp.Tracer("UrlShortenService_OTServerWrapperInterface")

	childCountPtr := ctx.Value("childCount").(*atomic.Uint64)
	ctx = context.WithValue(ctx, "seqNum", int(childCountPtr.Add(1)))

	ctx, span := tr.Start(ctx, "UrlShortenServiceClient_GetExtendedUrls", trace.WithSpanKind(trace.SpanKindClient))

	defer span.End()

	// Extract baggage from span attributes by casting to ReadWriteSpan
	if rwSpan, ok := span.(trace2.ReadWriteSpan); ok {
		for _, attr := range rwSpan.Attributes() {
			if strings.HasPrefix(string(attr.Key), "__bag.") {
				key := strings.TrimPrefix(string(attr.Key), "__bag.")
				// Convert value to string for baggage based on attribute type
				switch attr.Value.Type() {
				case attribute.INT64:
					baggage[key] = strconv.FormatInt(attr.Value.AsInt64(), 10)
				case attribute.STRING:
					baggage[key] = attr.Value.AsString()
				default:
					baggage[key] = attr.Value.AsString()
				}
			} else if strings.HasPrefix(string(attr.Key), "__bagdel.") {
				key := strings.TrimPrefix(string(attr.Key), "__bagdel.")
				delete(baggage, key)
			}
		}
	}

	// Combine trace context with baggage
	trace_ctx, _ := span.SpanContext().MarshalJSON()
	trace_ctx_with_baggage, _ := backend.AddBaggageToTraceContext(string(trace_ctx), baggage)

	ret0, err = handler.Client.GetExtendedUrls(ctx, reqID, shortenedUrls, trace_ctx_with_baggage)
	if err != nil {
		span.RecordError(err)
	}

	return
}
