// tracepressure_service_sbrev1_proc runs the tracepressure_service_sbrev1_proc Golang process.
//
// tracepressure_service_sbrev1_proc is auto-generated by Blueprint's goproc plugin (goproc/goprocgen/main.go.go)
//
// Usage:
//
//   go run main.go --otelcol_sbrev1.dial_addr=value --tracepressure_service_sbrev1.http.bind_addr=value 
//
// Optional env: GC_INTERVAL_SEC=N (e.g. 30, 1, 0.5, 0.1) to run GC every N seconds; fractional seconds supported. Omit or <=0 for default GC.
//
// tracepressure_service_sbrev1_proc requires the following arguments are passed:
//
//   --otelcol_sbrev1.dial_addr
//       Auto-generated by Blueprint IR node:
//       otelcol_sbrev1.dial_addr = AddressConfig()
//
//   --tracepressure_service_sbrev1.http.bind_addr
//       Auto-generated by Blueprint IR node:
//       tracepressure_service_sbrev1.http.bind_addr = AddressConfig()
//
// tracepressure_service_sbrev1_proc will instantiate the following IR nodes:
//   tracepressure_service_sbrev1_proc.stdoutmetriccollector
//   tracepressure_service_sbrev1_proc.logger
//   tracepressure_service_sbrev1
//   otelcol_sbrev1.client
//   tracepressure_service_sbrev1.server.ot
//   tracepressure_service_sbrev1.http_server
package main

import (
	"context"
	"os"
	"runtime"
	"strconv"
	"time"

	"log/slog"
)

func main() {
	// Optional: run GC on a fixed interval to normalize GC frequency (e.g. across tracing vs no-tracing).
	// Set GC_INTERVAL_SEC to a positive number (e.g. 30, 1, 0.5, 0.1) to trigger runtime.GC() every N seconds; unset or <=0 to leave default GC behavior.
	if sec := os.Getenv("GC_INTERVAL_SEC"); sec != "" {
		if secVal, err := strconv.ParseFloat(sec, 64); err == nil && secVal > 0 && secVal < 1e15 {
			interval := time.Duration(secVal * float64(time.Second))
			if interval > 0 {
				go func() {
					ticker := time.NewTicker(interval)
					defer ticker.Stop()
					for range ticker.C {
						runtime.GC()
					}
				}()
			}
		}
	}
	slog.Info("Running tracepressure_service_sbrev1_proc")
	n, err := New_tracepressure_service_sbrev1_proc("tracepressure_service_sbrev1_proc").Build(context.Background())
	if err != nil {
		slog.Error(err.Error())
		os.Exit(1)
	}
	n.Await()
	slog.Info("tracepressure_service_sbrev1_proc exiting")
}