// Package main is auto-generated by gogen/namespacebuilder.go
//
// It provides funcs for instantiating the hometimeline_service_nt_es_nw_proc namespace.
//
// To instantiate the hometimeline_service_nt_es_nw_proc namespace, first call [New_hometimeline_service_nt_es_nw_proc] and then either call
// [Build] or [BuildWithParent].
//
// See [golang.NamespaceBuilder] docs for more information about the behavior of [Build]
package main

import (
	"blueprint/goproc/hometimeline_service_nt_es_nw_proc/grpc"
	"blueprint/goproc/hometimeline_service_nt_es_nw_proc/retries"

	"github.com/blueprint-uservices/blueprint/examples/dsb_sn/workflow/snnw"
	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/golang"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/opentelemetry"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/redis"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/slogger"
)

// Initializes the hometimeline_service_nt_es_nw_proc namespace by defining all of the nodes that run
// within the namespace.
//
// [Build] or [BuildWithParent] must be called on the return value of this func
// to actually build and run the nodes in the namespace.
func New_hometimeline_service_nt_es_nw_proc(name string) *golang.NamespaceBuilder {
	b := golang.NewNamespaceBuilder(name)
	set_hometimeline_service_nt_es_nw_proc_Args(b)
	set_hometimeline_service_nt_es_nw_proc_Instances(b)
	set_hometimeline_service_nt_es_nw_proc_Definitions(b)
	return b
}

// hometimeline_service_nt_es_nw_proc requires that its arguments are either:
//   - explicitly set with [golang.NamespaceBuilder.Set]
//   - passed on the command line (if built using [golang.NamespaceBuilder.Build])
//   - are defined in parent (if built using [golang.NamespaceBuilder.BuildWithParent])
//
// The following arguments will be eagerly checked and building the namespace
// will fail if they haven't been provided:
//
//	hometimeline_cache_nt_es_nw.dial_addr
//	hometimeline_service_nt_es_nw.grpc.bind_addr
//	post_storage_service_nt_es_nw.grpc.dial_addr
//	socialgraph_service_nt_es_nw.grpc.dial_addr
//
// The following arguments are optional and a failure will only occur if the client
// tries to build a node that needs the argument to be set
func set_hometimeline_service_nt_es_nw_proc_Args(b *golang.NamespaceBuilder) {
	b.Required("hometimeline_cache_nt_es_nw.dial_addr", "Argument generated by Blueprint IR: hometimeline_cache_nt_es_nw.dial_addr = AddressConfig()")
	b.Required("hometimeline_service_nt_es_nw.grpc.bind_addr", "Argument generated by Blueprint IR: hometimeline_service_nt_es_nw.grpc.bind_addr = AddressConfig()")
	b.Required("post_storage_service_nt_es_nw.grpc.dial_addr", "Argument generated by Blueprint IR: post_storage_service_nt_es_nw.grpc.dial_addr = AddressConfig()")
	b.Required("socialgraph_service_nt_es_nw.grpc.dial_addr", "Argument generated by Blueprint IR: socialgraph_service_nt_es_nw.grpc.dial_addr = AddressConfig()")
}

// When the hometimeline_service_nt_es_nw_proc namespace is built it will automatically instantiate
// the following nodes:
//
//	hometimeline_service_nt_es_nw_proc.stdoutmetriccollector
//	hometimeline_service_nt_es_nw_proc.logger
//	hometimeline_cache_nt_es_nw.client
//	post_storage_service_nt_es_nw.grpc_client
//	post_storage_service_nt_es_nw.client.retrier
//	post_storage_service_nt_es_nw.client
//	socialgraph_service_nt_es_nw.grpc_client
//	socialgraph_service_nt_es_nw.client.retrier
//	socialgraph_service_nt_es_nw.client
//	hometimeline_service_nt_es_nw
//	hometimeline_service_nt_es_nw.grpc_server
func set_hometimeline_service_nt_es_nw_proc_Instances(b *golang.NamespaceBuilder) {
	b.Instantiate("hometimeline_service_nt_es_nw_proc.stdoutmetriccollector")
	b.Instantiate("hometimeline_service_nt_es_nw_proc.logger")
	b.Instantiate("hometimeline_cache_nt_es_nw.client")
	b.Instantiate("post_storage_service_nt_es_nw.grpc_client")
	b.Instantiate("post_storage_service_nt_es_nw.client.retrier")
	b.Instantiate("post_storage_service_nt_es_nw.client")
	b.Instantiate("socialgraph_service_nt_es_nw.grpc_client")
	b.Instantiate("socialgraph_service_nt_es_nw.client.retrier")
	b.Instantiate("socialgraph_service_nt_es_nw.client")
	b.Instantiate("hometimeline_service_nt_es_nw")
	b.Instantiate("hometimeline_service_nt_es_nw.grpc_server")
}

// The hometimeline_service_nt_es_nw_proc namespace contains definitions for instantiating
// the following nodes:
//
//	hometimeline_cache_nt_es_nw.client
//	hometimeline_service_nt_es_nw
//	hometimeline_service_nt_es_nw.grpc_server
//	hometimeline_service_nt_es_nw_proc.logger
//	hometimeline_service_nt_es_nw_proc.stdoutmetriccollector
//	post_storage_service_nt_es_nw.client
//	post_storage_service_nt_es_nw.client.retrier
//	post_storage_service_nt_es_nw.grpc_client
//	socialgraph_service_nt_es_nw.client
//	socialgraph_service_nt_es_nw.client.retrier
//	socialgraph_service_nt_es_nw.grpc_client
func set_hometimeline_service_nt_es_nw_proc_Definitions(b *golang.NamespaceBuilder) {
	b.Define("hometimeline_cache_nt_es_nw.client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var addr string
		if err := n.Get("hometimeline_cache_nt_es_nw.dial_addr", &addr); err != nil {
			return nil, err
		}

		return redis.NewRedisCacheClient(n.Context(), addr)
	})

	b.Define("hometimeline_service_nt_es_nw", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var homeTimelineCache backend.Cache
		if err := n.Get("hometimeline_cache_nt_es_nw.client", &homeTimelineCache); err != nil {
			return nil, err
		}

		var postStorageService snnw.PostStorageService
		if err := n.Get("post_storage_service_nt_es_nw.client", &postStorageService); err != nil {
			return nil, err
		}

		var socialGraphService snnw.SocialGraphService
		if err := n.Get("socialgraph_service_nt_es_nw.client", &socialGraphService); err != nil {
			return nil, err
		}

		return snnw.NewHomeTimelineServiceImpl(n.Context(), homeTimelineCache, postStorageService, socialGraphService)
	})

	b.Define("hometimeline_service_nt_es_nw.grpc_server", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var service snnw.HomeTimelineService
		if err := n.Get("hometimeline_service_nt_es_nw", &service); err != nil {
			return nil, err
		}

		var serverAddr string
		if err := n.Get("hometimeline_service_nt_es_nw.grpc.bind_addr", &serverAddr); err != nil {
			return nil, err
		}

		return grpc.New_HomeTimelineService_GRPCServerHandler(n.Context(), service, serverAddr)
	})

	b.Define("hometimeline_service_nt_es_nw_proc.logger", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		return slogger.NewSLogger(n.Context())
	})

	b.Define("hometimeline_service_nt_es_nw_proc.stdoutmetriccollector", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		return opentelemetry.NewStdoutMetricCollector(n.Context())
	})

	b.Define("post_storage_service_nt_es_nw.client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin workflow/ir_workflowservice.go
		var client snnw.PostStorageService
		err := n.Get("post_storage_service_nt_es_nw.client.retrier", &client)
		return client, err
	})

	b.Define("post_storage_service_nt_es_nw.client.retrier", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var client snnw.PostStorageService
		if err := n.Get("post_storage_service_nt_es_nw.grpc_client", &client); err != nil {
			return nil, err
		}

		return retries.New_PostStorageService_RetrierClient(n.Context(), client)
	})

	b.Define("post_storage_service_nt_es_nw.grpc_client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var addr string
		if err := n.Get("post_storage_service_nt_es_nw.grpc.dial_addr", &addr); err != nil {
			return nil, err
		}

		return grpc.New_PostStorageService_GRPCClient(n.Context(), addr)
	})

	b.Define("socialgraph_service_nt_es_nw.client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin workflow/ir_workflowservice.go
		var client snnw.SocialGraphService
		err := n.Get("socialgraph_service_nt_es_nw.client.retrier", &client)
		return client, err
	})

	b.Define("socialgraph_service_nt_es_nw.client.retrier", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var client snnw.SocialGraphService
		if err := n.Get("socialgraph_service_nt_es_nw.grpc_client", &client); err != nil {
			return nil, err
		}

		return retries.New_SocialGraphService_RetrierClient(n.Context(), client)
	})

	b.Define("socialgraph_service_nt_es_nw.grpc_client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var addr string
		if err := n.Get("socialgraph_service_nt_es_nw.grpc.dial_addr", &addr); err != nil {
			return nil, err
		}

		return grpc.New_SocialGraphService_GRPCClient(n.Context(), addr)
	})

}
