// Blueprint: Auto-generated by OT plugin
package ot

import (
	"context"
	"github.com/blueprint-uservices/blueprint/examples/leaf/workflow/leaf"
)

type LeafService_OTServerWrapperInterface interface {
	HelloInt(ctx context.Context, a int64, traceCtx string) (int64, string, error)
	HelloMate(ctx context.Context, a int, b int32, c string, d map[string]leaf.LeafObject, elems []string, elems2 []leaf.NestedLeafObject, traceCtx string) (string, []string, int32, int, map[string]leaf.LeafObject, string, error)
	HelloNothing(ctx context.Context, traceCtx string) (string, error)
	HelloObject(ctx context.Context, obj *leaf.LeafObject, traceCtx string) (*leaf.LeafObject, string, error)
	
}
