// Blueprint: Auto-generated by OpenTelemetry Plugin
package ot

import (
	"github.com/blueprint-uservices/blueprint/examples/leaf/workflow/leaf"
	"context"
	"go.opentelemetry.io/otel/trace"
	"go.opentelemetry.io/otel/attribute"
	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"strings"
	"sync/atomic"
	"strconv"
	trace2 "go.opentelemetry.io/otel/sdk/trace"
)

type LeafService_OTClientWrapperInterface interface {
	HelloInt(ctx context.Context, a int64) (int64, error)
	HelloMate(ctx context.Context, a int, b int32, c string, d map[string]leaf.LeafObject, elems []string, elems2 []leaf.NestedLeafObject) (string, []string, int32, int, map[string]leaf.LeafObject, error)
	HelloNothing(ctx context.Context) (error)
	HelloObject(ctx context.Context, obj *leaf.LeafObject) (*leaf.LeafObject, error)
	
}

type LeafService_OTClientWrapper struct {
	Client LeafService_OTServerWrapperInterface
	CollClient backend.Tracer
}

func New_LeafService_OTClientWrapper(ctx context.Context, client LeafService_OTServerWrapperInterface, coll_client backend.Tracer) (*LeafService_OTClientWrapper, error) {
	handler := &LeafService_OTClientWrapper{}
	handler.Client = client
	handler.CollClient = coll_client
	return handler, nil
}


func (handler *LeafService_OTClientWrapper) HelloInt(ctx context.Context, a int64) (ret0 int64, err error) {
	// Sampling-aware fast path: unsampled parent -> skip all per-request work
	// (baggage/critpath/span/JSON); forward only a compact "U:" carrier so the
	// trace stays consistent. At ratio>=1 nothing is unsampled -> unchanged.
	if psc := trace.SpanContextFromContext(ctx); psc.IsValid() && !psc.IsSampled() {
		ret0, _, err = handler.Client.HelloInt(ctx, a, "U:"+psc.TraceID().String()+psc.SpanID().String())
		return
	}
	// Get baggage from context and create a copy to avoid mutating shared state
	upstreamBaggage := backend.GetBaggageFromContext(ctx)
	baggage := make(map[string]string)
	if upstreamBaggage != nil {
		for k, v := range upstreamBaggage {
			baggage[k] = v
		}
	}
	
	tp, _ := handler.CollClient.GetTracerProvider(ctx)
	tr := tp.Tracer("LeafService_OTServerWrapperInterface")

	childCountPtr := ctx.Value("childCount").(*atomic.Uint64)
	seqNum := int(childCountPtr.Add(1))
	ctx = context.WithValue(ctx, "seqNum", seqNum)
	baggage["__seq"] = strconv.Itoa(seqNum) // propagate child ordinal to the downstream (server) span
	
	ctx, span := tr.Start(ctx, "LeafServiceClient_HelloInt", trace.WithSpanKind(trace.SpanKindClient))

	defer span.End()
	
	// Extract baggage from span attributes by casting to ReadWriteSpan
	if rwSpan, ok := span.(trace2.ReadWriteSpan); ok {
		for _, attr := range rwSpan.Attributes() {
			if strings.HasPrefix(string(attr.Key), "__bag.") {
				key := strings.TrimPrefix(string(attr.Key), "__bag.")
				// Convert value to string for baggage based on attribute type
				switch attr.Value.Type() {
				case attribute.INT64:
					baggage[key] = strconv.FormatInt(attr.Value.AsInt64(), 10)
				case attribute.STRING:
					baggage[key] = attr.Value.AsString()
				default:
					baggage[key] = attr.Value.AsString()
				}
			} else if strings.HasPrefix(string(attr.Key), "__bagdel.") {
				key := strings.TrimPrefix(string(attr.Key), "__bagdel.")
				delete(baggage, key)
			}
		}
	}
	
	// Combine trace context with baggage
	trace_ctx, _ := span.SpanContext().MarshalJSON()
	trace_ctx_with_baggage, _ := backend.AddBaggageToTraceContext(string(trace_ctx), baggage)
	
	// Capture reverse-truss that the callee returned
	ret0, retCtx, err = handler.Client.HelloInt(ctx, a, trace_ctx_with_baggage)
	if err != nil {
		span.RecordError(err)
	}
	// Record it on caller (parent) span
	span.SetAttributes(attribute.String("bridges.reverse_truss", retCtx))
	
	return
}

func (handler *LeafService_OTClientWrapper) HelloMate(ctx context.Context, a int, b int32, c string, d map[string]leaf.LeafObject, elems []string, elems2 []leaf.NestedLeafObject) (ret0 string, ret1 []string, ret2 int32, ret3 int, ret4 map[string]leaf.LeafObject, err error) {
	// Sampling-aware fast path: unsampled parent -> skip all per-request work
	// (baggage/critpath/span/JSON); forward only a compact "U:" carrier so the
	// trace stays consistent. At ratio>=1 nothing is unsampled -> unchanged.
	if psc := trace.SpanContextFromContext(ctx); psc.IsValid() && !psc.IsSampled() {
		ret0, ret1, ret2, ret3, ret4, _, err = handler.Client.HelloMate(ctx, a, b, c, d, elems, elems2, "U:"+psc.TraceID().String()+psc.SpanID().String())
		return
	}
	// Get baggage from context and create a copy to avoid mutating shared state
	upstreamBaggage := backend.GetBaggageFromContext(ctx)
	baggage := make(map[string]string)
	if upstreamBaggage != nil {
		for k, v := range upstreamBaggage {
			baggage[k] = v
		}
	}
	
	tp, _ := handler.CollClient.GetTracerProvider(ctx)
	tr := tp.Tracer("LeafService_OTServerWrapperInterface")

	childCountPtr := ctx.Value("childCount").(*atomic.Uint64)
	seqNum := int(childCountPtr.Add(1))
	ctx = context.WithValue(ctx, "seqNum", seqNum)
	baggage["__seq"] = strconv.Itoa(seqNum) // propagate child ordinal to the downstream (server) span
	
	ctx, span := tr.Start(ctx, "LeafServiceClient_HelloMate", trace.WithSpanKind(trace.SpanKindClient))

	defer span.End()
	
	// Extract baggage from span attributes by casting to ReadWriteSpan
	if rwSpan, ok := span.(trace2.ReadWriteSpan); ok {
		for _, attr := range rwSpan.Attributes() {
			if strings.HasPrefix(string(attr.Key), "__bag.") {
				key := strings.TrimPrefix(string(attr.Key), "__bag.")
				// Convert value to string for baggage based on attribute type
				switch attr.Value.Type() {
				case attribute.INT64:
					baggage[key] = strconv.FormatInt(attr.Value.AsInt64(), 10)
				case attribute.STRING:
					baggage[key] = attr.Value.AsString()
				default:
					baggage[key] = attr.Value.AsString()
				}
			} else if strings.HasPrefix(string(attr.Key), "__bagdel.") {
				key := strings.TrimPrefix(string(attr.Key), "__bagdel.")
				delete(baggage, key)
			}
		}
	}
	
	// Combine trace context with baggage
	trace_ctx, _ := span.SpanContext().MarshalJSON()
	trace_ctx_with_baggage, _ := backend.AddBaggageToTraceContext(string(trace_ctx), baggage)
	
	// Capture reverse-truss that the callee returned
	ret0, ret1, ret2, ret3, ret4, retCtx, err = handler.Client.HelloMate(ctx, a, b, c, d, elems, elems2, trace_ctx_with_baggage)
	if err != nil {
		span.RecordError(err)
	}
	// Record it on caller (parent) span
	span.SetAttributes(attribute.String("bridges.reverse_truss", retCtx))
	
	return
}

func (handler *LeafService_OTClientWrapper) HelloNothing(ctx context.Context) (err error) {
	// Sampling-aware fast path: unsampled parent -> skip all per-request work
	// (baggage/critpath/span/JSON); forward only a compact "U:" carrier so the
	// trace stays consistent. At ratio>=1 nothing is unsampled -> unchanged.
	if psc := trace.SpanContextFromContext(ctx); psc.IsValid() && !psc.IsSampled() {
		_, err = handler.Client.HelloNothing(ctx, "U:"+psc.TraceID().String()+psc.SpanID().String())
		return
	}
	// Get baggage from context and create a copy to avoid mutating shared state
	upstreamBaggage := backend.GetBaggageFromContext(ctx)
	baggage := make(map[string]string)
	if upstreamBaggage != nil {
		for k, v := range upstreamBaggage {
			baggage[k] = v
		}
	}
	
	tp, _ := handler.CollClient.GetTracerProvider(ctx)
	tr := tp.Tracer("LeafService_OTServerWrapperInterface")

	childCountPtr := ctx.Value("childCount").(*atomic.Uint64)
	seqNum := int(childCountPtr.Add(1))
	ctx = context.WithValue(ctx, "seqNum", seqNum)
	baggage["__seq"] = strconv.Itoa(seqNum) // propagate child ordinal to the downstream (server) span
	
	ctx, span := tr.Start(ctx, "LeafServiceClient_HelloNothing", trace.WithSpanKind(trace.SpanKindClient))

	defer span.End()
	
	// Extract baggage from span attributes by casting to ReadWriteSpan
	if rwSpan, ok := span.(trace2.ReadWriteSpan); ok {
		for _, attr := range rwSpan.Attributes() {
			if strings.HasPrefix(string(attr.Key), "__bag.") {
				key := strings.TrimPrefix(string(attr.Key), "__bag.")
				// Convert value to string for baggage based on attribute type
				switch attr.Value.Type() {
				case attribute.INT64:
					baggage[key] = strconv.FormatInt(attr.Value.AsInt64(), 10)
				case attribute.STRING:
					baggage[key] = attr.Value.AsString()
				default:
					baggage[key] = attr.Value.AsString()
				}
			} else if strings.HasPrefix(string(attr.Key), "__bagdel.") {
				key := strings.TrimPrefix(string(attr.Key), "__bagdel.")
				delete(baggage, key)
			}
		}
	}
	
	// Combine trace context with baggage
	trace_ctx, _ := span.SpanContext().MarshalJSON()
	trace_ctx_with_baggage, _ := backend.AddBaggageToTraceContext(string(trace_ctx), baggage)
	
	// Capture reverse-truss that the callee returned
	retCtx, err = handler.Client.HelloNothing(ctx, trace_ctx_with_baggage)
	if err != nil {
		span.RecordError(err)
	}
	// Record it on caller (parent) span
	span.SetAttributes(attribute.String("bridges.reverse_truss", retCtx))
	
	return
}

func (handler *LeafService_OTClientWrapper) HelloObject(ctx context.Context, obj *leaf.LeafObject) (ret0 *leaf.LeafObject, err error) {
	// Sampling-aware fast path: unsampled parent -> skip all per-request work
	// (baggage/critpath/span/JSON); forward only a compact "U:" carrier so the
	// trace stays consistent. At ratio>=1 nothing is unsampled -> unchanged.
	if psc := trace.SpanContextFromContext(ctx); psc.IsValid() && !psc.IsSampled() {
		ret0, _, err = handler.Client.HelloObject(ctx, obj, "U:"+psc.TraceID().String()+psc.SpanID().String())
		return
	}
	// Get baggage from context and create a copy to avoid mutating shared state
	upstreamBaggage := backend.GetBaggageFromContext(ctx)
	baggage := make(map[string]string)
	if upstreamBaggage != nil {
		for k, v := range upstreamBaggage {
			baggage[k] = v
		}
	}
	
	tp, _ := handler.CollClient.GetTracerProvider(ctx)
	tr := tp.Tracer("LeafService_OTServerWrapperInterface")

	childCountPtr := ctx.Value("childCount").(*atomic.Uint64)
	seqNum := int(childCountPtr.Add(1))
	ctx = context.WithValue(ctx, "seqNum", seqNum)
	baggage["__seq"] = strconv.Itoa(seqNum) // propagate child ordinal to the downstream (server) span
	
	ctx, span := tr.Start(ctx, "LeafServiceClient_HelloObject", trace.WithSpanKind(trace.SpanKindClient))

	defer span.End()
	
	// Extract baggage from span attributes by casting to ReadWriteSpan
	if rwSpan, ok := span.(trace2.ReadWriteSpan); ok {
		for _, attr := range rwSpan.Attributes() {
			if strings.HasPrefix(string(attr.Key), "__bag.") {
				key := strings.TrimPrefix(string(attr.Key), "__bag.")
				// Convert value to string for baggage based on attribute type
				switch attr.Value.Type() {
				case attribute.INT64:
					baggage[key] = strconv.FormatInt(attr.Value.AsInt64(), 10)
				case attribute.STRING:
					baggage[key] = attr.Value.AsString()
				default:
					baggage[key] = attr.Value.AsString()
				}
			} else if strings.HasPrefix(string(attr.Key), "__bagdel.") {
				key := strings.TrimPrefix(string(attr.Key), "__bagdel.")
				delete(baggage, key)
			}
		}
	}
	
	// Combine trace context with baggage
	trace_ctx, _ := span.SpanContext().MarshalJSON()
	trace_ctx_with_baggage, _ := backend.AddBaggageToTraceContext(string(trace_ctx), baggage)
	
	// Capture reverse-truss that the callee returned
	ret0, retCtx, err = handler.Client.HelloObject(ctx, obj, trace_ctx_with_baggage)
	if err != nil {
		span.RecordError(err)
	}
	// Record it on caller (parent) span
	span.SetAttributes(attribute.String("bridges.reverse_truss", retCtx))
	
	return
}

