// Blueprint: Auto-generated by OpenTelemetry Plugin
package ot

import (
	"go.opentelemetry.io/otel/attribute"
	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"strings"
	"strconv"
	"github.com/blueprint-uservices/blueprint/examples/dsb_sn/workflow/socialnetwork"
	"context"
	"go.opentelemetry.io/otel/trace"
	trace2 "go.opentelemetry.io/otel/sdk/trace"
)

type UserMentionService_OTClientWrapperInterface interface {
	ComposeUserMentions(ctx context.Context, reqID int64, usernames []string) ([]socialnetwork.UserMention, error)
	
}

type UserMentionService_OTClientWrapper struct {
	Client UserMentionService_OTServerWrapperInterface
	CollClient backend.Tracer
}

func New_UserMentionService_OTClientWrapper(ctx context.Context, client UserMentionService_OTServerWrapperInterface, coll_client backend.Tracer) (*UserMentionService_OTClientWrapper, error) {
	handler := &UserMentionService_OTClientWrapper{}
	handler.Client = client
	handler.CollClient = coll_client
	return handler, nil
}


func (handler *UserMentionService_OTClientWrapper) ComposeUserMentions(ctx context.Context, reqID int64, usernames []string) (ret0 []socialnetwork.UserMention, err error) {
	// Get baggage from context and create a copy to avoid mutating shared state
	upstreamBaggage := backend.GetBaggageFromContext(ctx)
	baggage := make(map[string]string)
	if upstreamBaggage != nil {
		for k, v := range upstreamBaggage {
			baggage[k] = v
		}
	}
	
	tp, _ := handler.CollClient.GetTracerProvider(ctx)
	tr := tp.Tracer("UserMentionService_OTServerWrapperInterface")
	
	ctx, span := tr.Start(ctx, "UserMentionServiceClient_ComposeUserMentions", trace.WithSpanKind(trace.SpanKindClient))

	defer span.End()
	
	// Extract baggage from span attributes by casting to ReadWriteSpan
	if rwSpan, ok := span.(trace2.ReadWriteSpan); ok {
		for _, attr := range rwSpan.Attributes() {
			if strings.HasPrefix(string(attr.Key), "__bag.") {
				key := strings.TrimPrefix(string(attr.Key), "__bag.")
				// Convert value to string for baggage based on attribute type
				switch attr.Value.Type() {
				case attribute.INT64:
					baggage[key] = strconv.FormatInt(attr.Value.AsInt64(), 10)
				case attribute.STRING:
					baggage[key] = attr.Value.AsString()
				default:
					baggage[key] = attr.Value.AsString()
				}
			} else if strings.HasPrefix(string(attr.Key), "__bagdel.") {
				key := strings.TrimPrefix(string(attr.Key), "__bagdel.")
				delete(baggage, key)
			}
		}
	}
	
	// Combine trace context with baggage
	trace_ctx, _ := span.SpanContext().MarshalJSON()
	trace_ctx_with_baggage, _ := backend.AddBaggageToTraceContext(string(trace_ctx), baggage)
	
	ret0, err = handler.Client.ComposeUserMentions(ctx, reqID, usernames, trace_ctx_with_baggage)
	if err != nil {
		span.RecordError(err)
	}
	
	return
}

