apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_v7/k8s
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: text-service-v7-ctr
  name: text-service-v7-ctr
spec:
  ports:
  - name: '12361'
    port: 12361
    targetPort: 12345
  - name: '12345'
    port: 12345
    targetPort: 12345
  selector:
    io.kompose.service: text-service-v7-ctr
