// media_service_v_proc runs the media_service_v_proc Golang process.
//
// media_service_v_proc is auto-generated by Blueprint's goproc plugin (goproc/goprocgen/main.go.go)
//
// Usage:
//
//   go run main.go --otelcol_v.dial_addr=value --media_service_v.grpc.bind_addr=value 
//
// media_service_v_proc requires the following arguments are passed:
//
//   --otelcol_v.dial_addr
//       Auto-generated by Blueprint IR node:
//       otelcol_v.dial_addr = AddressConfig()
//
//   --media_service_v.grpc.bind_addr
//       Auto-generated by Blueprint IR node:
//       media_service_v.grpc.bind_addr = AddressConfig()
//
// media_service_v_proc will instantiate the following IR nodes:
//   media_service_v_proc.stdoutmetriccollector
//   media_service_v_proc.logger
//   media_service_v
//   otelcol_v.client
//   media_service_v.server.ot
//   media_service_v.grpc_server
package main

import (
	"context"
	"os"

	"log/slog"
)

func main() {
	slog.Info("Running media_service_v_proc")
	n, err := New_media_service_v_proc("media_service_v_proc").Build(context.Background())
	if err != nil {
		slog.Error(err.Error())
		os.Exit(1)
	}
	n.Await()
	slog.Info("media_service_v_proc exiting")
}