apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_sb_ctl/k8s
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: usertimeline-db-sb-es-ctr
  name: usertimeline-db-sb-es-ctr
spec:
  ports:
  - name: '12373'
    port: 12373
    targetPort: 27017
  - name: '27017'
    port: 27017
    targetPort: 27017
  selector:
    io.kompose.service: usertimeline-db-sb-es-ctr
