apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_sb/k8s
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: media-service-sb-ctr
  name: media-service-sb-ctr
spec:
  ports:
  - name: '12352'
    port: 12352
    targetPort: 12345
  - name: '12345'
    port: 12345
    targetPort: 12345
  selector:
    io.kompose.service: media-service-sb-ctr
