apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_sb/k8s
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: post-cache-sb-ctr
  name: post-cache-sb-ctr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: post-cache-sb-ctr
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_sb/k8s
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: post-cache-sb-ctr
    spec:
      containers:
      - image: 10.10.1.1:30000/redis:latest
        name: post-cache-sb-ctr
        ports:
        - containerPort: 6379
          protocol: TCP
        resources:
          requests:
            cpu: 1000m
      hostname: post-cache-sb-ctr
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: node-6
