apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_sb/k8s
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: post-cache-sb-ctr
  name: post-cache-sb-ctr
spec:
  ports:
  - name: '12355'
    port: 12355
    targetPort: 6379
  - name: '6379'
    port: 6379
    targetPort: 6379
  selector:
    io.kompose.service: post-cache-sb-ctr
