apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_sb/k8s
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: uniqueid-service-sb-ctr
  name: uniqueid-service-sb-ctr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: uniqueid-service-sb-ctr
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_sb/k8s
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: uniqueid-service-sb-ctr
    spec:
      containers:
      - env:
        - name: OTELCOL_SB_DIAL_ADDR
          value: otelcol-sb-ctr:4317
        - name: UNIQUEID_SERVICE_SB_GRPC_BIND_ADDR
          value: 0.0.0.0:12345
        image: 10.10.1.1:30000/uniqueid-service-sb-ctr:latest
        name: uniqueid-service-sb-ctr
        ports:
        - containerPort: 12345
          protocol: TCP
        resources:
          requests:
            cpu: 2000m
      hostname: uniqueid-service-sb-ctr
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: node-3
