// Blueprint: Auto-generated by GRPC Plugin
package grpc

import (
	"google.golang.org/grpc/credentials/insecure"
	"blueprint/testclients/ot"
	"context"
	"time"
	"google.golang.org/grpc"
)

type UniqueIdService_GRPCClient struct {
	ot.UniqueIdService_OTServerWrapperInterface
	Client UniqueIdService_OTServerWrapperInterfaceClient // The actual GRPC-generated client
	Timeout time.Duration
}

func New_UniqueIdService_GRPCClient(ctx context.Context, serverAddress string) (*UniqueIdService_GRPCClient, error) {
	var opts []grpc.DialOption
	opts = append(opts, grpc.WithTransportCredentials(insecure.NewCredentials()))
	duration, err := time.ParseDuration("1s")
	if err != nil {
		return nil, err
	}
	opts = append(opts, grpc.WithTimeout(duration))
	conn, err := grpc.Dial(serverAddress, opts...)
	if err != nil {
		return nil, err
	}

	c := &UniqueIdService_GRPCClient{}
	c.Client = NewUniqueIdService_OTServerWrapperInterfaceClient(conn)
	c.Timeout = duration
	return c, nil
}


func (client *UniqueIdService_GRPCClient) ComposeUniqueId(ctx context.Context, reqID int64, postType int64, traceCtx string) (ret0 int64, err error) {
	// Create and marshall the GRPC Request object
	req := &UniqueIdService_OTServerWrapperInterface_ComposeUniqueId_Request{}
	req.marshall(reqID, postType, traceCtx)

	// Configure the client-side request timeout
	ctx, cancel := context.WithTimeout(ctx, client.Timeout)
	defer cancel()

	// Make the remote call
	rsp, err := client.Client.ComposeUniqueId(ctx, req)
	if err == nil {
		err = ctx.Err()
	}
	if err != nil {
		return
	}

	ret0 =  rsp.unmarshall()
	return
}

