apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o /users/tomislav/blueprint-docc-mod/examples/dsb_sn/build_v_esrev2c6/k8s
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: tracepressure-service-v-esrev2c6-ctr
  name: tracepressure-service-v-esrev2c6-ctr
spec:
  ports:
  - name: '12363'
    port: 12363
    targetPort: 2000
  - name: '2000'
    port: 2000
    targetPort: 2000
  selector:
    io.kompose.service: tracepressure-service-v-esrev2c6-ctr
