// Package main is auto-generated by gogen/namespacebuilder.go
//
// It provides funcs for instantiating the usermention_service_sb4_proc namespace.
//
// To instantiate the usermention_service_sb4_proc namespace, first call [New_usermention_service_sb4_proc] and then either call 
// [Build] or [BuildWithParent].
// 
// See [golang.NamespaceBuilder] docs for more information about the behavior of [Build]
package main

import (
	"github.com/blueprint-uservices/blueprint/runtime/plugins/slogger"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/redis"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/mongodb"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/otelcol"
	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"github.com/blueprint-uservices/blueprint/examples/dsb_sn/workflow/socialnetwork"
	"blueprint/goproc/usermention_service_sb4_proc/ot"
	"blueprint/goproc/usermention_service_sb4_proc/grpc"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/golang"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/opentelemetry"
)

// Initializes the usermention_service_sb4_proc namespace by defining all of the nodes that run
// within the namespace.
//
// [Build] or [BuildWithParent] must be called on the return value of this func
// to actually build and run the nodes in the namespace.
func New_usermention_service_sb4_proc(name string) *golang.NamespaceBuilder {
	b := golang.NewNamespaceBuilder(name)
	set_usermention_service_sb4_proc_Args(b)
	set_usermention_service_sb4_proc_Instances(b)
	set_usermention_service_sb4_proc_Definitions(b)
	return b
}

// usermention_service_sb4_proc requires that its arguments are either:
//  - explicitly set with [golang.NamespaceBuilder.Set]
//  - passed on the command line (if built using [golang.NamespaceBuilder.Build])
//  - are defined in parent (if built using [golang.NamespaceBuilder.BuildWithParent])
//
// The following arguments will be eagerly checked and building the namespace
// will fail if they haven't been provided:
//   otelcol_sb4.dial_addr
//   user_cache_sb4.dial_addr
//   user_db_sb4.dial_addr
//   usermention_service_sb4.grpc.bind_addr
//
// The following arguments are optional and a failure will only occur if the client
// tries to build a node that needs the argument to be set
func set_usermention_service_sb4_proc_Args(b *golang.NamespaceBuilder) {
	b.Required("otelcol_sb4.dial_addr", "Argument generated by Blueprint IR: otelcol_sb4.dial_addr = AddressConfig()")
	b.Required("user_cache_sb4.dial_addr", "Argument generated by Blueprint IR: user_cache_sb4.dial_addr = AddressConfig()")
	b.Required("user_db_sb4.dial_addr", "Argument generated by Blueprint IR: user_db_sb4.dial_addr = AddressConfig()")
	b.Required("usermention_service_sb4.grpc.bind_addr", "Argument generated by Blueprint IR: usermention_service_sb4.grpc.bind_addr = AddressConfig()")
}

// When the usermention_service_sb4_proc namespace is built it will automatically instantiate
// the following nodes:
//   usermention_service_sb4_proc.stdoutmetriccollector
//   usermention_service_sb4_proc.logger
//   user_cache_sb4.client
//   user_db_sb4.client
//   usermention_service_sb4
//   otelcol_sb4.client
//   usermention_service_sb4.server.ot
//   usermention_service_sb4.grpc_server
func set_usermention_service_sb4_proc_Instances(b *golang.NamespaceBuilder) {
	b.Instantiate("usermention_service_sb4_proc.stdoutmetriccollector")
	b.Instantiate("usermention_service_sb4_proc.logger")
	b.Instantiate("user_cache_sb4.client")
	b.Instantiate("user_db_sb4.client")
	b.Instantiate("usermention_service_sb4")
	b.Instantiate("otelcol_sb4.client")
	b.Instantiate("usermention_service_sb4.server.ot")
	b.Instantiate("usermention_service_sb4.grpc_server")
}

// The usermention_service_sb4_proc namespace contains definitions for instantiating
// the following nodes:
//   otelcol_sb4.client
//   user_cache_sb4.client
//   user_db_sb4.client
//   usermention_service_sb4
//   usermention_service_sb4.grpc_server
//   usermention_service_sb4.server.ot
//   usermention_service_sb4_proc.logger
//   usermention_service_sb4_proc.stdoutmetriccollector
func set_usermention_service_sb4_proc_Definitions(b *golang.NamespaceBuilder) {
	b.Define("otelcol_sb4.client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var addr string
		if err := n.Get("otelcol_sb4.dial_addr", &addr); err != nil {
			return nil, err
		}
		
		return otelcol.NewOTCollectorTracer(n.Context(), addr, "8080")
	})
	
	b.Define("user_cache_sb4.client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var addr string
		if err := n.Get("user_cache_sb4.dial_addr", &addr); err != nil {
			return nil, err
		}
		
		return redis.NewRedisCacheClient(n.Context(), addr)
	})
	
	b.Define("user_db_sb4.client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var addr string
		if err := n.Get("user_db_sb4.dial_addr", &addr); err != nil {
			return nil, err
		}
		
		return mongodb.NewMongoDB(n.Context(), addr)
	})
	
	b.Define("usermention_service_sb4", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var userCache backend.Cache
		if err := n.Get("user_cache_sb4.client", &userCache); err != nil {
			return nil, err
		}
		
		var userDB backend.NoSQLDatabase
		if err := n.Get("user_db_sb4.client", &userDB); err != nil {
			return nil, err
		}
		
		return socialnetwork.NewUserMentionServiceImpl(n.Context(), userCache, userDB)
	})
	
	b.Define("usermention_service_sb4.grpc_server", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var service ot.UserMentionService_OTServerWrapperInterface
		if err := n.Get("usermention_service_sb4.server.ot", &service); err != nil {
			return nil, err
		}
		
		var serverAddr string
		if err := n.Get("usermention_service_sb4.grpc.bind_addr", &serverAddr); err != nil {
			return nil, err
		}
		
		return grpc.New_UserMentionService_GRPCServerHandler(n.Context(), service, serverAddr)
	})
	
	b.Define("usermention_service_sb4.server.ot", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var service socialnetwork.UserMentionService
		if err := n.Get("usermention_service_sb4", &service); err != nil {
			return nil, err
		}
		
		var otCollectorClient backend.Tracer
		if err := n.Get("otelcol_sb4.client", &otCollectorClient); err != nil {
			return nil, err
		}
		
		return ot.New_UserMentionService_OTServerWrapper(n.Context(), service, otCollectorClient)
	})
	
	b.Define("usermention_service_sb4_proc.logger", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		return slogger.NewSLogger(n.Context())
	})
	
	b.Define("usermention_service_sb4_proc.stdoutmetriccollector", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		return opentelemetry.NewStdoutMetricCollector(n.Context())
	})
	
}
