package grpccodegen

import (
	"fmt"
	"path/filepath"

	"github.com/blueprint-uservices/blueprint/plugins/golang"
	"github.com/blueprint-uservices/blueprint/plugins/golang/gocode"
	"github.com/blueprint-uservices/blueprint/plugins/golang/gogen"
	"golang.org/x/exp/slog"
)

// Generates a gRPC client for the specified service
func GenerateClient(builder golang.ModuleBuilder, service *gocode.ServiceInterface, outputPackage string) error {
	pkg, err := builder.CreatePackage(outputPackage)
	if err != nil {
		return err
	}

	client := &clientArgs{
		Package: pkg,
		Service: service,
		Name:    service.BaseName + "_GRPCClient",
		Imports: gogen.NewImports(pkg.Name),
	}

	client.Imports.AddPackages(
		"context", "time", "os", "strconv", "sync/atomic",
		"google.golang.org/grpc",
		"google.golang.org/grpc/credentials/insecure",
	)

	slog.Info(fmt.Sprintf("Generating %v/%v.go", client.Package.PackageName, client.Name))
	outputFile := filepath.Join(client.Package.Path, client.Name+".go")
	return gogen.ExecuteTemplateToFile("GRPCClient", clientTemplate, client, outputFile)
}

/*
Arguments to the template code
*/
type clientArgs struct {
	Package golang.PackageInfo
	Service *gocode.ServiceInterface
	Name    string         // Name of the generated client class
	Imports *gogen.Imports // Manages imports for us
}

var clientTemplate = `// Blueprint: Auto-generated by GRPC Plugin
package {{.Package.ShortName}}

{{.Imports}}

type {{.Name}} struct {
	{{.Imports.NameOf .Service.UserType}}
	Client {{.Service.Name}}Client // The actual GRPC-generated client (clients[0])
	// clients holds one client per underlying ClientConn. HTTP/2 carries one
	// ordered frame stream per TCP connection, so grpc-go runs exactly ONE
	// loopyWriter goroutine per connection to serialize all writes (grpc-go
	// internal/transport/http2_client.go, in newHTTP2Client: a single
	// "go func() { ... t.loopy.run() ... }()" per transport). A goroutine uses
	// at most one core, so a single connection caps a service-to-service edge
	// at the rate one goroutine can frame and write. Spreading calls over K
	// connections gives K independent writers (measured: +17% at K=4, after
	// which the edge service becomes CPU-bound at ~93%).
	// See https://grpc.io/docs/guides/performance/ ("use a pool of channels").
	clients []{{.Service.Name}}Client
	next    atomic.Uint32
	Timeout time.Duration
}

// pick returns the next client, round-robin. Deliberately an atomic increment
// rather than a channel/mutex handoff: the goal is fan-out with NO concurrency
// cap. (Contrast the clientpool plugin, whose purpose is the opposite -- it
// caps outstanding calls at N and blocks beyond that, which measured WORSE at
// every size tested.)
func (client *{{.Name}}) pick() {{.Service.Name}}Client {
	if len(client.clients) == 1 {
		return client.clients[0]
	}
	return client.clients[client.next.Add(1)%uint32(len(client.clients))]
}

func New_{{.Name}}(ctx context.Context, serverAddress string) (*{{.Name}}, error) {
	var opts []grpc.DialOption
	opts = append(opts, grpc.WithTransportCredentials(insecure.NewCredentials()))
	duration, err := time.ParseDuration("1s")
	if err != nil {
		return nil, err
	}
	opts = append(opts, grpc.WithTimeout(duration))

	// Number of connections per service edge. Default 1 preserves the
	// historical single-connection behaviour exactly; raise it only for edges
	// that are throughput-bound on transport write serialization.
	numConns := 1
	if v := os.Getenv("GRPC_CLIENT_CONNS"); v != "" {
		if n, err := strconv.Atoi(v); err == nil && n > 0 {
			numConns = n
		}
	}

	c := &{{.Name}}{}
	for i := 0; i < numConns; i++ {
		conn, err := grpc.Dial(serverAddress, opts...)
		if err != nil {
			return nil, err
		}
		c.clients = append(c.clients, New{{.Service.Name}}Client(conn))
	}
	c.Client = c.clients[0]
	c.Timeout = duration
	return c, nil
}

{{$service := .Service.Name -}}
{{$receiver := .Name -}}
{{- range $_, $f := .Service.Methods }}
func (client *{{$receiver}}) {{SignatureWithRetVars $f}} {
	// Create and marshall the GRPC Request object
	req := &{{$service}}_{{$f.Name}}_Request{}
	req.marshall({{ArgVars $f}})

	// Configure the client-side request timeout
	ctx, cancel := context.WithTimeout(ctx, client.Timeout)
	defer cancel()

	// Make the remote call
	rsp, err := client.pick().{{$f.Name}}(ctx, req)
	if err == nil {
		err = ctx.Err()
	}
	if err != nil {
		return
	}

	{{RetVarsEquals $f}} rsp.unmarshall()
	return
}
{{end}}
`
