package grpccodegen

import (
	"fmt"
	"path/filepath"

	"github.com/blueprint-uservices/blueprint/plugins/golang"
	"github.com/blueprint-uservices/blueprint/plugins/golang/gocode"
	"github.com/blueprint-uservices/blueprint/plugins/golang/gogen"
	"golang.org/x/exp/slog"
)

// Generates a gRPC client for the specified service
func GenerateClient(builder golang.ModuleBuilder, service *gocode.ServiceInterface, outputPackage string) error {
	pkg, err := builder.CreatePackage(outputPackage)
	if err != nil {
		return err
	}

	client := &clientArgs{
		Package: pkg,
		Service: service,
		Name:    service.BaseName + "_GRPCClient",
		Imports: gogen.NewImports(pkg.Name),
	}

	client.Imports.AddPackages(
		"context", "fmt", "time",
		"google.golang.org/grpc",
		"google.golang.org/grpc/credentials/insecure",
	)

	slog.Info(fmt.Sprintf("Generating %v/%v.go", client.Package.PackageName, client.Name))
	outputFile := filepath.Join(client.Package.Path, client.Name+".go")
	return gogen.ExecuteTemplateToFile("GRPCClient", clientTemplate, client, outputFile)
}

/*
Arguments to the template code
*/
type clientArgs struct {
	Package golang.PackageInfo
	Service *gocode.ServiceInterface
	Name    string         // Name of the generated client class
	Imports *gogen.Imports // Manages imports for us
}

var clientTemplate = `// Blueprint: Auto-generated by GRPC Plugin
package {{.Package.ShortName}}

{{.Imports}}

type {{.Name}} struct {
	{{.Imports.NameOf .Service.UserType}}
	Client {{.Service.Name}}Client // The actual GRPC-generated client
	Timeout time.Duration
}

// Tomislav-RetCtx: optional wiring timeout; existing two-argument calls keep 1s.
func New_{{.Name}}(ctx context.Context, serverAddress string, timeout ...string) (*{{.Name}}, error) {
	var opts []grpc.DialOption
	opts = append(opts, grpc.WithTransportCredentials(insecure.NewCredentials()))
	if len(timeout) > 1 {
		return nil, fmt.Errorf("expected at most one gRPC timeout")
	}
	timeoutValue := "1s"
	if len(timeout) == 1 {
		timeoutValue = timeout[0]
	}
	duration, err := time.ParseDuration(timeoutValue)
	if err != nil {
		return nil, err
	}
	if duration <= 0 {
		return nil, fmt.Errorf("gRPC timeout must be positive")
	}
	opts = append(opts, grpc.WithTimeout(duration))
	conn, err := grpc.Dial(serverAddress, opts...)
	if err != nil {
		return nil, err
	}

	c := &{{.Name}}{}
	c.Client = New{{.Service.Name}}Client(conn)
	c.Timeout = duration
	return c, nil
}

{{$service := .Service.Name -}}
{{$receiver := .Name -}}
{{- range $_, $f := .Service.Methods }}
func (client *{{$receiver}}) {{SignatureWithRetVars $f}} {
	// Create and marshall the GRPC Request object
	req := &{{$service}}_{{$f.Name}}_Request{}
	req.marshall({{ArgVars $f}})

	// Configure the client-side request timeout
	ctx, cancel := context.WithTimeout(ctx, client.Timeout)
	defer cancel()

	// Make the remote call
	rsp, err := client.Client.{{$f.Name}}(ctx, req)
	if err == nil {
		err = ctx.Err()
	}
	if err != nil {
		return
	}

	{{RetVarsEquals $f}} rsp.unmarshall()
	return
}
{{end}}
`
