// Package main is auto-generated by gogen/namespacebuilder.go
//
// It provides funcs for instantiating the urlshorten_service_pb_proc namespace.
//
// To instantiate the urlshorten_service_pb_proc namespace, first call [New_urlshorten_service_pb_proc] and then either call 
// [Build] or [BuildWithParent].
// 
// See [golang.NamespaceBuilder] docs for more information about the behavior of [Build]
package main

import (
	"github.com/blueprint-uservices/blueprint/runtime/plugins/slogger"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/otelcol"
	"blueprint/goproc/urlshorten_service_pb_proc/ot"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/mongodb"
	"github.com/blueprint-uservices/blueprint/runtime/core/backend"
	"github.com/blueprint-uservices/blueprint/examples/dsb_sn/workflow/socialnetwork"
	"blueprint/goproc/urlshorten_service_pb_proc/grpc"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/golang"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/opentelemetry"
)

// Initializes the urlshorten_service_pb_proc namespace by defining all of the nodes that run
// within the namespace.
//
// [Build] or [BuildWithParent] must be called on the return value of this func
// to actually build and run the nodes in the namespace.
func New_urlshorten_service_pb_proc(name string) *golang.NamespaceBuilder {
	b := golang.NewNamespaceBuilder(name)
	set_urlshorten_service_pb_proc_Args(b)
	set_urlshorten_service_pb_proc_Instances(b)
	set_urlshorten_service_pb_proc_Definitions(b)
	return b
}

// urlshorten_service_pb_proc requires that its arguments are either:
//  - explicitly set with [golang.NamespaceBuilder.Set]
//  - passed on the command line (if built using [golang.NamespaceBuilder.Build])
//  - are defined in parent (if built using [golang.NamespaceBuilder.BuildWithParent])
//
// The following arguments will be eagerly checked and building the namespace
// will fail if they haven't been provided:
//   otelcol_pb.dial_addr
//   urlshorten_db_pb.dial_addr
//   urlshorten_service_pb.grpc.bind_addr
//
// The following arguments are optional and a failure will only occur if the client
// tries to build a node that needs the argument to be set
func set_urlshorten_service_pb_proc_Args(b *golang.NamespaceBuilder) {
	b.Required("otelcol_pb.dial_addr", "Argument generated by Blueprint IR: otelcol_pb.dial_addr = AddressConfig()")
	b.Required("urlshorten_db_pb.dial_addr", "Argument generated by Blueprint IR: urlshorten_db_pb.dial_addr = AddressConfig()")
	b.Required("urlshorten_service_pb.grpc.bind_addr", "Argument generated by Blueprint IR: urlshorten_service_pb.grpc.bind_addr = AddressConfig()")
}

// When the urlshorten_service_pb_proc namespace is built it will automatically instantiate
// the following nodes:
//   urlshorten_service_pb_proc.stdoutmetriccollector
//   urlshorten_service_pb_proc.logger
//   urlshorten_db_pb.client
//   urlshorten_service_pb
//   otelcol_pb.client
//   urlshorten_service_pb.server.ot
//   urlshorten_service_pb.grpc_server
func set_urlshorten_service_pb_proc_Instances(b *golang.NamespaceBuilder) {
	b.Instantiate("urlshorten_service_pb_proc.stdoutmetriccollector")
	b.Instantiate("urlshorten_service_pb_proc.logger")
	b.Instantiate("urlshorten_db_pb.client")
	b.Instantiate("urlshorten_service_pb")
	b.Instantiate("otelcol_pb.client")
	b.Instantiate("urlshorten_service_pb.server.ot")
	b.Instantiate("urlshorten_service_pb.grpc_server")
}

// The urlshorten_service_pb_proc namespace contains definitions for instantiating
// the following nodes:
//   otelcol_pb.client
//   urlshorten_db_pb.client
//   urlshorten_service_pb
//   urlshorten_service_pb.grpc_server
//   urlshorten_service_pb.server.ot
//   urlshorten_service_pb_proc.logger
//   urlshorten_service_pb_proc.stdoutmetriccollector
func set_urlshorten_service_pb_proc_Definitions(b *golang.NamespaceBuilder) {
	b.Define("otelcol_pb.client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var addr string
		if err := n.Get("otelcol_pb.dial_addr", &addr); err != nil {
			return nil, err
		}
		
		return otelcol.NewOTCollectorTracer(n.Context(), addr, "8080")
	})
	
	b.Define("urlshorten_db_pb.client", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var addr string
		if err := n.Get("urlshorten_db_pb.dial_addr", &addr); err != nil {
			return nil, err
		}
		
		return mongodb.NewMongoDB(n.Context(), addr)
	})
	
	b.Define("urlshorten_service_pb", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var urlShortenDB backend.NoSQLDatabase
		if err := n.Get("urlshorten_db_pb.client", &urlShortenDB); err != nil {
			return nil, err
		}
		
		return socialnetwork.NewUrlShortenServiceImpl(n.Context(), urlShortenDB)
	})
	
	b.Define("urlshorten_service_pb.grpc_server", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var service ot.UrlShortenService_OTServerWrapperInterface
		if err := n.Get("urlshorten_service_pb.server.ot", &service); err != nil {
			return nil, err
		}
		
		var serverAddr string
		if err := n.Get("urlshorten_service_pb.grpc.bind_addr", &serverAddr); err != nil {
			return nil, err
		}
		
		return grpc.New_UrlShortenService_GRPCServerHandler(n.Context(), service, serverAddr)
	})
	
	b.Define("urlshorten_service_pb.server.ot", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		var service socialnetwork.UrlShortenService
		if err := n.Get("urlshorten_service_pb", &service); err != nil {
			return nil, err
		}
		
		var otCollectorClient backend.Tracer
		if err := n.Get("otelcol_pb.client", &otCollectorClient); err != nil {
			return nil, err
		}
		
		return ot.New_UrlShortenService_OTServerWrapper(n.Context(), service, otCollectorClient)
	})
	
	b.Define("urlshorten_service_pb_proc.logger", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		return slogger.NewSLogger(n.Context())
	})
	
	b.Define("urlshorten_service_pb_proc.stdoutmetriccollector", func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin gogen/namespacebuilder.go
		return opentelemetry.NewStdoutMetricCollector(n.Context())
	})
	
}
