// Blueprint: Auto-generated by GRPC Plugin
package grpc

import (
	"google.golang.org/grpc"
	"github.com/blueprint-uservices/blueprint/examples/dsb_sn/workflow/socialnetwork"
	"context"
	"net"
)

type UrlShortenService_GRPCServerHandler struct {
	UnimplementedUrlShortenServiceServer
	Service socialnetwork.UrlShortenService
	Address string
}

func New_UrlShortenService_GRPCServerHandler(ctx context.Context, service socialnetwork.UrlShortenService, serverAddress string) (*UrlShortenService_GRPCServerHandler, error) {
	handler := &UrlShortenService_GRPCServerHandler{}
	handler.Service = service
	handler.Address = serverAddress
	return handler, nil
}

// Blueprint: Run is called automatically in a separate goroutine by runtime/plugins/golang/di.go
func (handler *UrlShortenService_GRPCServerHandler) Run(ctx context.Context) error {
	lis, err := net.Listen("tcp", handler.Address)
	if err != nil {
		return err
	}

	s := grpc.NewServer()
	RegisterUrlShortenServiceServer(s, handler)

	go func() {
		select {
		case <-ctx.Done():
			s.GracefulStop()
		}
	}()

	return s.Serve(lis)
}


func (handler *UrlShortenService_GRPCServerHandler) ComposeUrls(ctx context.Context, req *UrlShortenService_ComposeUrls_Request) (*UrlShortenService_ComposeUrls_Response, error) {
	reqID, urls := req.unmarshall()
	ret0, err := handler.Service.ComposeUrls(ctx, reqID, urls)
	if err != nil {
		return nil, err
	}

	rsp := &UrlShortenService_ComposeUrls_Response{}
	rsp.marshall(ret0)
	return rsp, nil
}

func (handler *UrlShortenService_GRPCServerHandler) GetExtendedUrls(ctx context.Context, req *UrlShortenService_GetExtendedUrls_Request) (*UrlShortenService_GetExtendedUrls_Response, error) {
	reqID, shortenedUrls := req.unmarshall()
	ret0, err := handler.Service.GetExtendedUrls(ctx, reqID, shortenedUrls)
	if err != nil {
		return nil, err
	}

	rsp := &UrlShortenService_GetExtendedUrls_Response{}
	rsp.marshall(ret0)
	return rsp, nil
}

