// Blueprint: Auto-generated by Retries Plugin
package retries

import (
	"github.com/blueprint-uservices/blueprint/examples/dsb_sn/workflow/socialnetwork"
	"context"
)

type ComposePostService_RetrierClient struct {
	Client socialnetwork.ComposePostService
	MaxTries int
}

func New_ComposePostService_RetrierClient (ctx context.Context, client socialnetwork.ComposePostService) (*ComposePostService_RetrierClient, error) {
	handler := &ComposePostService_RetrierClient{}
	handler.Client = client
	handler.MaxTries = 3
	return handler, nil
}


func (client *ComposePostService_RetrierClient) ComposePost(ctx context.Context, reqID int64, username string, userID int64, text string, mediaIDs []int64, mediaTypes []string, postType int64) (ret0 int64, ret1 []int64, err error) {
	for i := 0; i < client.MaxTries; i++ {
		ret0, ret1, err = client.Client.ComposePost(ctx, reqID, username, userID, text, mediaIDs, mediaTypes, postType)
		if err == nil {
			return
		}
	}
	return
}

