// This file is auto-generated by the Blueprint clientpool plugin
package pool

import (
	"github.com/blueprint-uservices/blueprint/runtime/plugins/golang"
	"github.com/blueprint-uservices/blueprint/examples/dsb_sn/workflow/socialnetwork"
	"context"
	"fmt"
	"github.com/blueprint-uservices/blueprint/runtime/plugins/clientpool"
)

type SocialGraphService_ClientPool struct {
	clients *clientpool.ClientPool[socialnetwork.SocialGraphService]
}

func New_SocialGraphService_Pool(parent *golang.Namespace) *SocialGraphService_ClientPool {
	i := 0
	createClient := func() (socialnetwork.SocialGraphService, error) {
		clientName := fmt.Sprintf("socialgraph_service_nt2.clientpool.%v", i)
		n, err := New_SocialGraphService_PoolClient(clientName).BuildWithParent(parent)
		if err != nil {
			return nil, err
		}
		i++
		var client socialnetwork.SocialGraphService
		err = n.Get("socialgraph_service_nt2.grpc_client", &client)
		return client, err
	}
	clients := clientpool.NewClientPool(10, createClient)
	return &SocialGraphService_ClientPool{clients: clients}
}


func (pool *SocialGraphService_ClientPool) Follow(ctx context.Context, reqID int64, userID int64, followeeID int64) (err error) {
	client, err := pool.clients.Pop(ctx)
	if err != nil {
		return
	}
	defer pool.clients.Push(client)
	return client.Follow(ctx, reqID, userID, followeeID)
}

func (pool *SocialGraphService_ClientPool) FollowWithUsername(ctx context.Context, reqID int64, userUsername string, followeeUsername string) (err error) {
	client, err := pool.clients.Pop(ctx)
	if err != nil {
		return
	}
	defer pool.clients.Push(client)
	return client.FollowWithUsername(ctx, reqID, userUsername, followeeUsername)
}

func (pool *SocialGraphService_ClientPool) GetFollowees(ctx context.Context, reqID int64, userID int64) (ret0 []int64, err error) {
	client, err := pool.clients.Pop(ctx)
	if err != nil {
		return
	}
	defer pool.clients.Push(client)
	return client.GetFollowees(ctx, reqID, userID)
}

func (pool *SocialGraphService_ClientPool) GetFollowers(ctx context.Context, reqID int64, userID int64) (ret0 []int64, err error) {
	client, err := pool.clients.Pop(ctx)
	if err != nil {
		return
	}
	defer pool.clients.Push(client)
	return client.GetFollowers(ctx, reqID, userID)
}

func (pool *SocialGraphService_ClientPool) InsertUser(ctx context.Context, reqID int64, userID int64) (err error) {
	client, err := pool.clients.Pop(ctx)
	if err != nil {
		return
	}
	defer pool.clients.Push(client)
	return client.InsertUser(ctx, reqID, userID)
}

func (pool *SocialGraphService_ClientPool) Unfollow(ctx context.Context, reqID int64, userID int64, followeeID int64) (err error) {
	client, err := pool.clients.Pop(ctx)
	if err != nil {
		return
	}
	defer pool.clients.Push(client)
	return client.Unfollow(ctx, reqID, userID, followeeID)
}

func (pool *SocialGraphService_ClientPool) UnfollowWithUsername(ctx context.Context, reqID int64, userUsername string, followeeUsername string) (err error) {
	client, err := pool.clients.Pop(ctx)
	if err != nil {
		return
	}
	defer pool.clients.Push(client)
	return client.UnfollowWithUsername(ctx, reqID, userUsername, followeeUsername)
}



