// Blueprint: Auto-generated by Retries Plugin
package retries

import (
	"context"
	"blueprint/goproc/socialgraph_service_v7_proc/ot"
)

type UserIDService_RetrierClient struct {
	Client ot.UserIDService_OTClientWrapperInterface
	MaxTries int
}

func New_UserIDService_RetrierClient (ctx context.Context, client ot.UserIDService_OTClientWrapperInterface) (*UserIDService_RetrierClient, error) {
	handler := &UserIDService_RetrierClient{}
	handler.Client = client
	handler.MaxTries = 3
	return handler, nil
}


func (client *UserIDService_RetrierClient) GetUserId(ctx context.Context, reqID int64, username string) (ret0 int64, err error) {
	for i := 0; i < client.MaxTries; i++ {
		ret0, err = client.Client.GetUserId(ctx, reqID, username)
		if err == nil {
			return
		}
	}
	return
}

