// Blueprint: Auto-generated by the HTTP Plugin
package http

import (
	"net/http"
	"encoding/json"
	"context"
	"net/url"
	"fmt"
	"io"
	"errors"
)

type Wrk2APIService_HTTPClient struct {
	Client *http.Client
	ServerAddress string
}

func New_Wrk2APIService_HTTPClient(ctx context.Context, serverAddress string) (*Wrk2APIService_HTTPClient, error) {
	defaultRoundTripper := http.DefaultTransport
	defaultTransportPointer, ok := defaultRoundTripper.(*http.Transport)
	if !ok {
		return nil, errors.New("defaultRoundTripper not an *http.Transport")
	}
	defaultTransport := *defaultTransportPointer // dereference it to get a copy of the struct that the pointer points to
	defaultTransport.MaxIdleConns = 60000
	defaultTransport.MaxIdleConnsPerHost = 60000
	defaultTransport.MaxConnsPerHost = 10000
	client := &http.Client{
		Transport: &defaultTransport,
	}
	c := &Wrk2APIService_HTTPClient{}
	c.Client = client
	c.ServerAddress = "http://" + serverAddress
	return c, nil
}


func (client *Wrk2APIService_HTTPClient) ComposePost(ctx context.Context, userId int64, username string, post_type int64, text string, media_types []string, media_ids []int64, traceCtx string) (ret0 int64, ret1 []int64, err error) {
	vals := url.Values{}
	
	bytes_userId, err := json.Marshal(userId)
	if err != nil {
		return
	}
	vals.Add("userId", string(bytes_userId))
	
	vals.Add("username", username)
	
	bytes_post_type, err := json.Marshal(post_type)
	if err != nil {
		return
	}
	vals.Add("post_type", string(bytes_post_type))
	
	vals.Add("text", text)
	
	bytes_media_types, err := json.Marshal(media_types)
	if err != nil {
		return
	}
	vals.Add("media_types", string(bytes_media_types))
	
	bytes_media_ids, err := json.Marshal(media_ids)
	if err != nil {
		return
	}
	vals.Add("media_ids", string(bytes_media_ids))
	
	vals.Add("traceCtx", traceCtx)
	

	encoded_url, err := url.Parse(client.ServerAddress + "/ComposePost")
	if err != nil {
		return
	}
	encoded_url.RawQuery = vals.Encode()

	resp, err := client.Client.Get(encoded_url.String())
	if err != nil {
		return
	}
	defer resp.Body.Close()
	statusOk := resp.StatusCode >= 200 && resp.StatusCode < 300
	if !statusOk {
		err = fmt.Errorf("StatusCode was %d", resp.StatusCode)
		return
	}
	response := struct {
		
		Ret0 int64
		
		Ret1 []int64
		
	}{}
	resp_bytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return
	}
	err = json.Unmarshal(resp_bytes, &response)
	if err != nil {
		return
	}
	
	ret0 = response.Ret0
	
	ret1 = response.Ret1
	
	return
}

func (client *Wrk2APIService_HTTPClient) Follow(ctx context.Context, username string, followeeName string, userId int64, followeeID int64, traceCtx string) (err error) {
	vals := url.Values{}
	
	vals.Add("username", username)
	
	vals.Add("followeeName", followeeName)
	
	bytes_userId, err := json.Marshal(userId)
	if err != nil {
		return
	}
	vals.Add("userId", string(bytes_userId))
	
	bytes_followeeID, err := json.Marshal(followeeID)
	if err != nil {
		return
	}
	vals.Add("followeeID", string(bytes_followeeID))
	
	vals.Add("traceCtx", traceCtx)
	

	encoded_url, err := url.Parse(client.ServerAddress + "/Follow")
	if err != nil {
		return
	}
	encoded_url.RawQuery = vals.Encode()

	resp, err := client.Client.Get(encoded_url.String())
	if err != nil {
		return
	}
	defer resp.Body.Close()
	statusOk := resp.StatusCode >= 200 && resp.StatusCode < 300
	if !statusOk {
		err = fmt.Errorf("StatusCode was %d", resp.StatusCode)
		return
	}
	response := struct {
		
	}{}
	resp_bytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return
	}
	err = json.Unmarshal(resp_bytes, &response)
	if err != nil {
		return
	}
	
	return
}

func (client *Wrk2APIService_HTTPClient) ReadHomeTimeline(ctx context.Context, userId int64, start int64, stop int64, traceCtx string) (ret0 []int64, err error) {
	vals := url.Values{}
	
	bytes_userId, err := json.Marshal(userId)
	if err != nil {
		return
	}
	vals.Add("userId", string(bytes_userId))
	
	bytes_start, err := json.Marshal(start)
	if err != nil {
		return
	}
	vals.Add("start", string(bytes_start))
	
	bytes_stop, err := json.Marshal(stop)
	if err != nil {
		return
	}
	vals.Add("stop", string(bytes_stop))
	
	vals.Add("traceCtx", traceCtx)
	

	encoded_url, err := url.Parse(client.ServerAddress + "/ReadHomeTimeline")
	if err != nil {
		return
	}
	encoded_url.RawQuery = vals.Encode()

	resp, err := client.Client.Get(encoded_url.String())
	if err != nil {
		return
	}
	defer resp.Body.Close()
	statusOk := resp.StatusCode >= 200 && resp.StatusCode < 300
	if !statusOk {
		err = fmt.Errorf("StatusCode was %d", resp.StatusCode)
		return
	}
	response := struct {
		
		Ret0 []int64
		
	}{}
	resp_bytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return
	}
	err = json.Unmarshal(resp_bytes, &response)
	if err != nil {
		return
	}
	
	ret0 = response.Ret0
	
	return
}

func (client *Wrk2APIService_HTTPClient) ReadUserTimeline(ctx context.Context, userId int64, start int64, stop int64, traceCtx string) (ret0 []int64, err error) {
	vals := url.Values{}
	
	bytes_userId, err := json.Marshal(userId)
	if err != nil {
		return
	}
	vals.Add("userId", string(bytes_userId))
	
	bytes_start, err := json.Marshal(start)
	if err != nil {
		return
	}
	vals.Add("start", string(bytes_start))
	
	bytes_stop, err := json.Marshal(stop)
	if err != nil {
		return
	}
	vals.Add("stop", string(bytes_stop))
	
	vals.Add("traceCtx", traceCtx)
	

	encoded_url, err := url.Parse(client.ServerAddress + "/ReadUserTimeline")
	if err != nil {
		return
	}
	encoded_url.RawQuery = vals.Encode()

	resp, err := client.Client.Get(encoded_url.String())
	if err != nil {
		return
	}
	defer resp.Body.Close()
	statusOk := resp.StatusCode >= 200 && resp.StatusCode < 300
	if !statusOk {
		err = fmt.Errorf("StatusCode was %d", resp.StatusCode)
		return
	}
	response := struct {
		
		Ret0 []int64
		
	}{}
	resp_bytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return
	}
	err = json.Unmarshal(resp_bytes, &response)
	if err != nil {
		return
	}
	
	ret0 = response.Ret0
	
	return
}

func (client *Wrk2APIService_HTTPClient) Register(ctx context.Context, firstName string, lastName string, username string, password string, userId int64, traceCtx string) (err error) {
	vals := url.Values{}
	
	vals.Add("firstName", firstName)
	
	vals.Add("lastName", lastName)
	
	vals.Add("username", username)
	
	vals.Add("password", password)
	
	bytes_userId, err := json.Marshal(userId)
	if err != nil {
		return
	}
	vals.Add("userId", string(bytes_userId))
	
	vals.Add("traceCtx", traceCtx)
	

	encoded_url, err := url.Parse(client.ServerAddress + "/Register")
	if err != nil {
		return
	}
	encoded_url.RawQuery = vals.Encode()

	resp, err := client.Client.Get(encoded_url.String())
	if err != nil {
		return
	}
	defer resp.Body.Close()
	statusOk := resp.StatusCode >= 200 && resp.StatusCode < 300
	if !statusOk {
		err = fmt.Errorf("StatusCode was %d", resp.StatusCode)
		return
	}
	response := struct {
		
	}{}
	resp_bytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return
	}
	err = json.Unmarshal(resp_bytes, &response)
	if err != nil {
		return
	}
	
	return
}

func (client *Wrk2APIService_HTTPClient) Unfollow(ctx context.Context, username string, followeeName string, userId int64, followeeID int64, traceCtx string) (err error) {
	vals := url.Values{}
	
	vals.Add("username", username)
	
	vals.Add("followeeName", followeeName)
	
	bytes_userId, err := json.Marshal(userId)
	if err != nil {
		return
	}
	vals.Add("userId", string(bytes_userId))
	
	bytes_followeeID, err := json.Marshal(followeeID)
	if err != nil {
		return
	}
	vals.Add("followeeID", string(bytes_followeeID))
	
	vals.Add("traceCtx", traceCtx)
	

	encoded_url, err := url.Parse(client.ServerAddress + "/Unfollow")
	if err != nil {
		return
	}
	encoded_url.RawQuery = vals.Encode()

	resp, err := client.Client.Get(encoded_url.String())
	if err != nil {
		return
	}
	defer resp.Body.Close()
	statusOk := resp.StatusCode >= 200 && resp.StatusCode < 300
	if !statusOk {
		err = fmt.Errorf("StatusCode was %d", resp.StatusCode)
		return
	}
	response := struct {
		
	}{}
	resp_bytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return
	}
	err = json.Unmarshal(resp_bytes, &response)
	if err != nil {
		return
	}
	
	return
}

